/*
 Highcharts JS v6.1.0-modified (2018-05-16)

 (c) 2009-2016 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(x){"object"===typeof module&&module.exports?module.exports=x:x(Highcharts)})(function(x){(function(a){function h(a,b){this.init(a,b)}var v=a.CenteredSeriesMixin,u=a.each,m=a.extend,r=a.merge,t=a.splat;m(h.prototype,{coll:"pane",init:function(a,b){this.chart=b;this.background=[];b.pane.push(this);this.setOptions(a)},setOptions:function(a){this.options=r(this.defaultOptions,this.chart.angular?{background:{}}:void 0,a)},render:function(){var a=this.options,b=this.options.background,c=this.chart.renderer;
this.group||(this.group=c.g("pane-group").attr({zIndex:a.zIndex||0}).add());this.updateCenter();if(b)for(b=t(b),a=Math.max(b.length,this.background.length||0),c=0;c<a;c++)b[c]&&this.axis?this.renderBackground(r(this.defaultBackgroundOptions,b[c]),c):this.background[c]&&(this.background[c]=this.background[c].destroy(),this.background.splice(c,1))},renderBackground:function(a,b){var c="animate";this.background[b]||(this.background[b]=this.chart.renderer.path().add(this.group),c="attr");this.background[b][c]({d:this.axis.getPlotBandPath(a.from,
a.to,a)}).attr({"class":"highcharts-pane "+(a.className||"")})},defaultOptions:{center:["50%","50%"],size:"85%",startAngle:0},defaultBackgroundOptions:{shape:"circle",from:-Number.MAX_VALUE,innerRadius:0,to:Number.MAX_VALUE,outerRadius:"105%"},updateCenter:function(a){this.center=(a||this.axis||{}).center=v.getCenter.call(this)},update:function(a,b){r(!0,this.options,a);this.setOptions(this.options);this.render();u(this.chart.axes,function(c){c.pane===this&&(c.pane=null,c.update({},b))},this)}});
a.Pane=h})(x);(function(a){var h=a.addEvent,v=a.Axis,u=a.each,m=a.extend,r=a.map,t=a.merge,p=a.noop,b=a.pick,c=a.pInt,f=a.Tick,g=a.wrap,d=a.correctFloat,e,q,l=v.prototype,k=f.prototype;a.radialAxisExtended||(a.radialAxisExtended=!0,e={getOffset:p,redraw:function(){this.isDirty=!1},render:function(){this.isDirty=!1},setScale:p,setCategories:p,setTitle:p},q={defaultRadialGaugeOptions:{labels:{align:"center",x:0,y:null},minorGridLineWidth:0,minorTickInterval:"auto",minorTickLength:10,minorTickPosition:"inside",
minorTickWidth:1,tickLength:10,tickPosition:"inside",tickWidth:2,title:{rotation:0},zIndex:2},defaultRadialXOptions:{gridLineWidth:1,labels:{align:null,distance:15,x:0,y:null,style:{textOverflow:"none"}},maxPadding:0,minPadding:0,showLastLabel:!1,tickLength:0},defaultRadialYOptions:{gridLineInterpolation:"circle",labels:{align:"right",x:-3,y:-2},showLastLabel:!1,title:{x:4,text:null,rotation:90}},setOptions:function(b){b=this.options=t(this.defaultOptions,this.defaultRadialOptions,b);b.plotBands||
(b.plotBands=[])},getOffset:function(){l.getOffset.call(this);this.chart.axisOffset[this.side]=0},getLinePath:function(c,d){c=this.center;var e=this.chart,f=b(d,c[2]/2-this.offset);this.isCircular||void 0!==d?(d=this.chart.renderer.symbols.arc(this.left+c[0],this.top+c[1],f,f,{start:this.startAngleRad,end:this.endAngleRad,open:!0,innerR:0}),d.xBounds=[this.left+c[0]],d.yBounds=[this.top+c[1]-f]):(d=this.postTranslate(this.angleRad,f),d=["M",c[0]+e.plotLeft,c[1]+e.plotTop,"L",d.x,d.y]);return d},setAxisTranslation:function(){l.setAxisTranslation.call(this);
this.center&&(this.transA=this.isCircular?(this.endAngleRad-this.startAngleRad)/(this.max-this.min||1):this.center[2]/2/(this.max-this.min||1),this.minPixelPadding=this.isXAxis?this.transA*this.minPointOffset:0)},beforeSetTickPositions:function(){if(this.autoConnect=this.isCircular&&void 0===b(this.userMax,this.options.max)&&d(this.endAngleRad-this.startAngleRad)===d(2*Math.PI))this.max+=this.categories&&1||this.pointRange||this.closestPointRange||0},setAxisSize:function(){l.setAxisSize.call(this);
this.isRadial&&(this.pane.updateCenter(this),this.isCircular&&(this.sector=this.endAngleRad-this.startAngleRad),this.len=this.width=this.height=this.center[2]*b(this.sector,1)/2)},getPosition:function(c,d){return this.postTranslate(this.isCircular?this.translate(c):this.angleRad,b(this.isCircular?d:this.translate(c),this.center[2]/2)-this.offset)},postTranslate:function(b,c){var d=this.chart,e=this.center;b=this.startAngleRad+b;return{x:d.plotLeft+e[0]+Math.cos(b)*c,y:d.plotTop+e[1]+Math.sin(b)*c}},
getPlotBandPath:function(d,e,f){var a=this.center,g=this.startAngleRad,w=a[2]/2,n=[b(f.outerRadius,"100%"),f.innerRadius,b(f.thickness,10)],q=Math.min(this.offset,0),l=/%$/,k,A=this.isCircular;"polygon"===this.options.gridLineInterpolation?a=this.getPlotLinePath(d).concat(this.getPlotLinePath(e,!0)):(d=Math.max(d,this.min),e=Math.min(e,this.max),A||(n[0]=this.translate(d),n[1]=this.translate(e)),n=r(n,function(b){l.test(b)&&(b=c(b,10)*w/100);return b}),"circle"!==f.shape&&A?(d=g+this.translate(d),
e=g+this.translate(e)):(d=-Math.PI/2,e=1.5*Math.PI,k=!0),n[0]-=q,n[2]-=q,a=this.chart.renderer.symbols.arc(this.left+a[0],this.top+a[1],n[0],n[0],{start:Math.min(d,e),end:Math.max(d,e),innerR:b(n[1],n[0]-n[2]),open:k}));return a},getPlotLinePath:function(b,c){var d=this,e=d.center,f=d.chart,a=d.getPosition(b),g,n,w;d.isCircular?w=["M",e[0]+f.plotLeft,e[1]+f.plotTop,"L",a.x,a.y]:"circle"===d.options.gridLineInterpolation?(b=d.translate(b))&&(w=d.getLinePath(0,b)):(u(f.xAxis,function(b){b.pane===d.pane&&
(g=b)}),w=[],b=d.translate(b),e=g.tickPositions,g.autoConnect&&(e=e.concat([e[0]])),c&&(e=[].concat(e).reverse()),u(e,function(c,d){n=g.getPosition(c,b);w.push(d?"L":"M",n.x,n.y)}));return w},getTitlePosition:function(){var b=this.center,c=this.chart,d=this.options.title;return{x:c.plotLeft+b[0]+(d.x||0),y:c.plotTop+b[1]-{high:.5,middle:.25,low:0}[d.align]*b[2]+(d.y||0)}}},h(v,"init",function(b){var c=this.chart,d=c.angular,f=c.polar,a=this.isXAxis,g=d&&a,n,l=c.options;b=b.userOptions.pane||0;b=this.pane=
c.pane&&c.pane[b];if(d){if(m(this,g?e:q),n=!a)this.defaultRadialOptions=this.defaultRadialGaugeOptions}else f&&(m(this,q),this.defaultRadialOptions=(n=a)?this.defaultRadialXOptions:t(this.defaultYAxisOptions,this.defaultRadialYOptions));d||f?(this.isRadial=!0,c.inverted=!1,l.chart.zoomType=null):this.isRadial=!1;b&&n&&(b.axis=this);this.isCircular=n}),h(v,"afterInit",function(){var c=this.chart,d=this.options,e=this.pane,f=e&&e.options;c.angular&&this.isXAxis||!e||!c.angular&&!c.polar||(this.angleRad=
(d.angle||0)*Math.PI/180,this.startAngleRad=(f.startAngle-90)*Math.PI/180,this.endAngleRad=(b(f.endAngle,f.startAngle+360)-90)*Math.PI/180,this.offset=d.offset||0)}),g(l,"autoLabelAlign",function(b){if(!this.isRadial)return b.apply(this,[].slice.call(arguments,1))}),h(f,"afterGetPosition",function(b){this.axis.getPosition&&m(b.pos,this.axis.getPosition(this.pos))}),h(f,"afterGetLabelPosition",function(c){var d=this.axis,e=this.label,f=d.options.labels,a=f.y,g,q=20,l=f.align,k=(d.translate(this.pos)+
d.startAngleRad+Math.PI/2)/Math.PI*180%360;d.isRadial&&(g=d.getPosition(this.pos,d.center[2]/2+b(f.distance,-25)),"auto"===f.rotation?e.attr({rotation:k}):null===a&&(a=d.chart.renderer.fontMetrics(e.styles&&e.styles.fontSize).b-e.getBBox().height/2),null===l&&(d.isCircular?(this.label.getBBox().width>d.len*d.tickInterval/(d.max-d.min)&&(q=0),l=k>q&&k<180-q?"left":k>180+q&&k<360-q?"right":"center"):l="center",e.attr({align:l})),c.pos.x=g.x+f.x,c.pos.y=g.y+a)}),g(k,"getMarkPath",function(b,c,d,e,f,
a,g){var q=this.axis;q.isRadial?(b=q.getPosition(this.pos,q.center[2]/2+e),c=["M",c,d,"L",b.x,b.y]):c=b.call(this,c,d,e,f,a,g);return c}))})(x);(function(a){var h=a.each,v=a.pick,u=a.defined,m=a.seriesType,r=a.seriesTypes,t=a.Series.prototype,p=a.Point.prototype;m("arearange","area",{threshold:null,tooltip:{pointFormat:'\x3cspan class\x3d"highcharts-color-{series.colorIndex}"\x3e\u25cf\x3c/span\x3e {series.name}: \x3cb\x3e{point.low}\x3c/b\x3e - \x3cb\x3e{point.high}\x3c/b\x3e\x3cbr/\x3e'},trackByArea:!0,
dataLabels:{align:null,verticalAlign:null,xLow:0,xHigh:0,yLow:0,yHigh:0}},{pointArrayMap:["low","high"],dataLabelCollections:["dataLabel","dataLabelUpper"],toYData:function(b){return[b.low,b.high]},pointValKey:"low",deferTranslatePolar:!0,highToXY:function(b){var c=this.chart,f=this.xAxis.postTranslate(b.rectPlotX,this.yAxis.len-b.plotHigh);b.plotHighX=f.x-c.plotLeft;b.plotHigh=f.y-c.plotTop;b.plotLowX=b.plotX},translate:function(){var b=this,c=b.yAxis,f=!!b.modifyValue;r.area.prototype.translate.apply(b);
h(b.points,function(a){var d=a.low,e=a.high,g=a.plotY;null===e||null===d?(a.isNull=!0,a.plotY=null):(a.plotLow=g,a.plotHigh=c.translate(f?b.modifyValue(e,a):e,0,1,0,1),f&&(a.yBottom=a.plotHigh))});this.chart.polar&&h(this.points,function(c){b.highToXY(c);c.tooltipPos=[(c.plotHighX+c.plotLowX)/2,(c.plotHigh+c.plotLow)/2]})},getGraphPath:function(b){var c=[],f=[],a,d=r.area.prototype.getGraphPath,e,q,l;l=this.options;var k=this.chart.polar&&!1!==l.connectEnds,n=l.connectNulls,w=l.step;b=b||this.points;
for(a=b.length;a--;)e=b[a],e.isNull||k||n||b[a+1]&&!b[a+1].isNull||f.push({plotX:e.plotX,plotY:e.plotY,doCurve:!1}),q={polarPlotY:e.polarPlotY,rectPlotX:e.rectPlotX,yBottom:e.yBottom,plotX:v(e.plotHighX,e.plotX),plotY:e.plotHigh,isNull:e.isNull},f.push(q),c.push(q),e.isNull||k||n||b[a-1]&&!b[a-1].isNull||f.push({plotX:e.plotX,plotY:e.plotY,doCurve:!1});b=d.call(this,b);w&&(!0===w&&(w="left"),l.step={left:"right",center:"center",right:"left"}[w]);c=d.call(this,c);f=d.call(this,f);l.step=w;l=[].concat(b,
c);this.chart.polar||"M"!==f[0]||(f[0]="L");this.graphPath=l;this.areaPath=b.concat(f);l.isArea=!0;l.xMap=b.xMap;this.areaPath.xMap=b.xMap;return l},drawDataLabels:function(){var b=this.data,c=b.length,a,g=[],d=this.options.dataLabels,e=d.align,q=d.verticalAlign,l=d.inside,k,n,w=this.chart.inverted;if(d.enabled||this._hasPointLabels){for(a=c;a--;)if(k=b[a])n=l?k.plotHigh<k.plotLow:k.plotHigh>k.plotLow,k.y=k.high,k._plotY=k.plotY,k.plotY=k.plotHigh,g[a]=k.dataLabel,k.dataLabel=k.dataLabelUpper,k.below=
n,w?e||(d.align=n?"right":"left"):q||(d.verticalAlign=n?"top":"bottom"),d.x=d.xHigh,d.y=d.yHigh;t.drawDataLabels&&t.drawDataLabels.apply(this,arguments);for(a=c;a--;)if(k=b[a])n=l?k.plotHigh<k.plotLow:k.plotHigh>k.plotLow,k.dataLabelUpper=k.dataLabel,k.dataLabel=g[a],k.y=k.low,k.plotY=k._plotY,k.below=!n,w?e||(d.align=n?"left":"right"):q||(d.verticalAlign=n?"bottom":"top"),d.x=d.xLow,d.y=d.yLow;t.drawDataLabels&&t.drawDataLabels.apply(this,arguments)}d.align=e;d.verticalAlign=q},alignDataLabel:function(){r.column.prototype.alignDataLabel.apply(this,
arguments)},drawPoints:function(){var b=this.points.length,c,f;t.drawPoints.apply(this,arguments);for(f=0;f<b;)c=this.points[f],c.origProps={plotY:c.plotY,plotX:c.plotX,isInside:c.isInside,negative:c.negative,zone:c.zone,y:c.y},c.lowerGraphic=c.graphic,c.graphic=c.upperGraphic,c.plotY=c.plotHigh,u(c.plotHighX)&&(c.plotX=c.plotHighX),c.y=c.high,c.negative=c.high<(this.options.threshold||0),c.zone=this.zones.length&&c.getZone(),this.chart.polar||(c.isInside=c.isTopInside=void 0!==c.plotY&&0<=c.plotY&&
c.plotY<=this.yAxis.len&&0<=c.plotX&&c.plotX<=this.xAxis.len),f++;t.drawPoints.apply(this,arguments);for(f=0;f<b;)c=this.points[f],c.upperGraphic=c.graphic,c.graphic=c.lowerGraphic,a.extend(c,c.origProps),delete c.origProps,f++},setStackedPoints:a.noop},{setState:function(){var b=this.state,c=this.series,a=c.chart.polar;u(this.plotHigh)||(this.plotHigh=c.yAxis.toPixels(this.high,!0));u(this.plotLow)||(this.plotLow=this.plotY=c.yAxis.toPixels(this.low,!0));c.stateMarkerGraphic&&(c.lowerStateMarkerGraphic=
c.stateMarkerGraphic,c.stateMarkerGraphic=c.upperStateMarkerGraphic);this.graphic=this.upperGraphic;this.plotY=this.plotHigh;a&&(this.plotX=this.plotHighX);p.setState.apply(this,arguments);this.state=b;this.plotY=this.plotLow;this.graphic=this.lowerGraphic;a&&(this.plotX=this.plotLowX);c.stateMarkerGraphic&&(c.upperStateMarkerGraphic=c.stateMarkerGraphic,c.stateMarkerGraphic=c.lowerStateMarkerGraphic,c.lowerStateMarkerGraphic=void 0);p.setState.apply(this,arguments)},haloPath:function(){var b=this.series.chart.polar,
c=[];this.plotY=this.plotLow;b&&(this.plotX=this.plotLowX);this.isInside&&(c=p.haloPath.apply(this,arguments));this.plotY=this.plotHigh;b&&(this.plotX=this.plotHighX);this.isTopInside&&(c=c.concat(p.haloPath.apply(this,arguments)));return c},destroyElements:function(){h(["lowerGraphic","upperGraphic"],function(b){this[b]&&(this[b]=this[b].destroy())},this);this.graphic=null;return p.destroyElements.apply(this,arguments)}})})(x);(function(a){var h=a.seriesType;h("areasplinerange","arearange",null,
{getPointSpline:a.seriesTypes.spline.prototype.getPointSpline})})(x);(function(a){var h=a.defaultPlotOptions,v=a.each,u=a.merge,m=a.noop,r=a.pick,t=a.seriesType,p=a.seriesTypes.column.prototype;t("columnrange","arearange",u(h.column,h.arearange,{pointRange:null,marker:null,states:{hover:{halo:!1}}}),{translate:function(){var b=this,c=b.yAxis,a=b.xAxis,g=a.startAngleRad,d,e=b.chart,q=b.xAxis.isRadial,l=Math.max(e.chartWidth,e.chartHeight)+999,k;p.translate.apply(b);v(b.points,function(f){var n=f.shapeArgs,
m=b.options.minPointLength,p,y;f.plotHigh=k=Math.min(Math.max(-l,c.translate(f.high,0,1,0,1)),l);f.plotLow=Math.min(Math.max(-l,f.plotY),l);y=k;p=r(f.rectPlotY,f.plotY)-k;Math.abs(p)<m?(m-=p,p+=m,y-=m/2):0>p&&(p*=-1,y-=p);q?(d=f.barX+g,f.shapeType="path",f.shapeArgs={d:b.polarArc(y+p,y,d,d+f.pointWidth)}):(n.height=p,n.y=y,f.tooltipPos=e.inverted?[c.len+c.pos-e.plotLeft-y-p/2,a.len+a.pos-e.plotTop-n.x-n.width/2,p]:[a.left-e.plotLeft+n.x+n.width/2,c.pos-e.plotTop+y+p/2,p])})},directTouch:!0,trackerGroups:["group",
"dataLabelsGroup"],drawGraph:m,getSymbol:m,crispCol:p.crispCol,drawPoints:p.drawPoints,drawTracker:p.drawTracker,getColumnMetrics:p.getColumnMetrics,pointAttribs:p.pointAttribs,animate:function(){return p.animate.apply(this,arguments)},polarArc:function(){return p.polarArc.apply(this,arguments)},translate3dPoints:function(){return p.translate3dPoints.apply(this,arguments)},translate3dShapes:function(){return p.translate3dShapes.apply(this,arguments)}},{setState:p.pointClass.prototype.setState})})(x);
(function(a){var h=a.each,v=a.isNumber,u=a.merge,m=a.pick,r=a.pInt,t=a.Series,p=a.seriesType,b=a.TrackerMixin;p("gauge","line",{dataLabels:{enabled:!0,defer:!1,y:15,borderRadius:3,crop:!1,verticalAlign:"top",zIndex:2},dial:{},pivot:{},tooltip:{headerFormat:""},showInLegend:!1},{angular:!0,directTouch:!0,drawGraph:a.noop,fixedBox:!0,forceDL:!0,noSharedTooltip:!0,trackerGroups:["group","dataLabelsGroup"],translate:function(){var b=this.yAxis,a=this.options,g=b.center;this.generatePoints();h(this.points,
function(c){var d=u(a.dial,c.dial),f=r(m(d.radius,80))*g[2]/200,l=r(m(d.baseLength,70))*f/100,k=r(m(d.rearLength,10))*f/100,n=d.baseWidth||3,w=d.topWidth||1,p=a.overshoot,h=b.startAngleRad+b.translate(c.y,null,null,null,!0);v(p)?(p=p/180*Math.PI,h=Math.max(b.startAngleRad-p,Math.min(b.endAngleRad+p,h))):!1===a.wrap&&(h=Math.max(b.startAngleRad,Math.min(b.endAngleRad,h)));h=180*h/Math.PI;c.shapeType="path";c.shapeArgs={d:d.path||["M",-k,-n/2,"L",l,-n/2,f,-w/2,f,w/2,l,n/2,-k,n/2,"z"],translateX:g[0],
translateY:g[1],rotation:h};c.plotX=g[0];c.plotY=g[1]})},drawPoints:function(){var b=this,a=b.yAxis.center,g=b.pivot,d=b.options,e=d.pivot,q=b.chart.renderer;h(b.points,function(c){var a=c.graphic,e=c.shapeArgs,f=e.d;u(d.dial,c.dial);a?(a.animate(e),e.d=f):c.graphic=q[c.shapeType](e).attr({rotation:e.rotation,zIndex:1}).addClass("highcharts-dial").add(b.group)});g?g.animate({translateX:a[0],translateY:a[1]}):b.pivot=q.circle(0,0,m(e.radius,5)).attr({zIndex:2}).addClass("highcharts-pivot").translate(a[0],
a[1]).add(b.group)},animate:function(b){var c=this;b||(h(c.points,function(b){var d=b.graphic;d&&(d.attr({rotation:180*c.yAxis.startAngleRad/Math.PI}),d.animate({rotation:b.shapeArgs.rotation},c.options.animation))}),c.animate=null)},render:function(){this.group=this.plotGroup("group","series",this.visible?"visible":"hidden",this.options.zIndex,this.chart.seriesGroup);t.prototype.render.call(this);this.group.clip(this.chart.clipRect)},setData:function(b,a){t.prototype.setData.call(this,b,!1);this.processData();
this.generatePoints();m(a,!0)&&this.chart.redraw()},drawTracker:b&&b.drawTrackerPoint},{setState:function(b){this.state=b}})})(x);(function(a){var h=a.each,v=a.noop,u=a.seriesType,m=a.seriesTypes;u("boxplot","column",{threshold:null,tooltip:{pointFormat:'\x3cspan class\x3d"highcharts-color-{point.colorIndex}"\x3e\u25cf\x3c/span\x3e \x3cb\x3e {series.name}\x3c/b\x3e\x3cbr/\x3eMaximum: {point.high}\x3cbr/\x3eUpper quartile: {point.q3}\x3cbr/\x3eMedian: {point.median}\x3cbr/\x3eLower quartile: {point.q1}\x3cbr/\x3eMinimum: {point.low}\x3cbr/\x3e'},
whiskerLength:"50%"},{pointArrayMap:["low","q1","median","q3","high"],toYData:function(a){return[a.low,a.q1,a.median,a.q3,a.high]},pointValKey:"high",drawDataLabels:v,translate:function(){var a=this.yAxis,t=this.pointArrayMap;m.column.prototype.translate.apply(this);h(this.points,function(p){h(t,function(b){null!==p[b]&&(p[b+"Plot"]=a.translate(p[b],0,1,0,1))})})},drawPoints:function(){var a=this,m=a.chart.renderer,p,b,c,f,g,d,e=0,q,l,k,n,w=!1!==a.doQuartiles,u,v=a.options.whiskerLength;h(a.points,
function(h){var r=h.graphic,t=r?"animate":"attr",A=h.shapeArgs;void 0!==h.plotY&&(q=A.width,l=Math.floor(A.x),k=l+q,n=Math.round(q/2),p=Math.floor(w?h.q1Plot:h.lowPlot),b=Math.floor(w?h.q3Plot:h.lowPlot),c=Math.floor(h.highPlot),f=Math.floor(h.lowPlot),r||(h.graphic=r=m.g("point").add(a.group),h.stem=m.path().addClass("highcharts-boxplot-stem").add(r),v&&(h.whiskers=m.path().addClass("highcharts-boxplot-whisker").add(r)),w&&(h.box=m.path(void 0).addClass("highcharts-boxplot-box").add(r)),h.medianShape=
m.path(void 0).addClass("highcharts-boxplot-median").add(r)),d=h.stem.strokeWidth()%2/2,e=l+n+d,h.stem[t]({d:["M",e,b,"L",e,c,"M",e,p,"L",e,f]}),w&&(d=h.box.strokeWidth()%2/2,p=Math.floor(p)+d,b=Math.floor(b)+d,l+=d,k+=d,h.box[t]({d:["M",l,b,"L",l,p,"L",k,p,"L",k,b,"L",l,b,"z"]})),v&&(d=h.whiskers.strokeWidth()%2/2,c+=d,f+=d,u=/%$/.test(v)?n*parseFloat(v)/100:v/2,h.whiskers[t]({d:["M",e-u,c,"L",e+u,c,"M",e-u,f,"L",e+u,f]})),g=Math.round(h.medianPlot),d=h.medianShape.strokeWidth()%2/2,g+=d,h.medianShape[t]({d:["M",
l,g,"L",k,g]}))})},setStackedPoints:v})})(x);(function(a){var h=a.each,v=a.noop,u=a.seriesType,m=a.seriesTypes;u("errorbar","boxplot",{grouping:!1,linkedTo:":previous",tooltip:{pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e {series.name}: \x3cb\x3e{point.low}\x3c/b\x3e - \x3cb\x3e{point.high}\x3c/b\x3e\x3cbr/\x3e'},whiskerWidth:null},{type:"errorbar",pointArrayMap:["low","high"],toYData:function(a){return[a.low,a.high]},pointValKey:"high",doQuartiles:!1,drawDataLabels:m.arearange?
function(){var a=this.pointValKey;m.arearange.prototype.drawDataLabels.call(this);h(this.data,function(h){h.y=h[a]})}:v,getColumnMetrics:function(){return this.linkedParent&&this.linkedParent.columnMetrics||m.column.prototype.getColumnMetrics.call(this)}})})(x);(function(a){var h=a.correctFloat,v=a.isNumber,u=a.pick,m=a.Point,r=a.Series,t=a.seriesType,p=a.seriesTypes;t("waterfall","column",{dataLabels:{inside:!0}},{pointValKey:"y",showLine:!0,generatePoints:function(){var b=this.options.threshold,
c,a,g,d;p.column.prototype.generatePoints.apply(this);g=0;for(a=this.points.length;g<a;g++)c=this.points[g],d=this.processedYData[g],c.isSum?c.y=h(d):c.isIntermediateSum&&(c.y=h(d-b),b=d)},translate:function(){var b=this.options,c=this.yAxis,a,g,d,e,q,l,k,n,h,m,r=u(b.minPointLength,5),t=r/2,v=b.threshold,x=b.stacking,z;p.column.prototype.translate.apply(this);n=h=v;g=this.points;a=0;for(b=g.length;a<b;a++)d=g[a],k=this.processedYData[a],e=d.shapeArgs,q=x&&c.stacks[(this.negStacks&&k<v?"-":"")+this.stackKey],
z=this.getStackIndicator(z,d.x,this.index),m=u(q&&q[d.x].points[z.key],[0,k]),l=Math.max(n,n+d.y)+m[0],e.y=c.translate(l,0,1,0,1),d.isSum?(e.y=c.translate(m[1],0,1,0,1),e.height=Math.min(c.translate(m[0],0,1,0,1),c.len)-e.y):d.isIntermediateSum?(e.y=c.translate(m[1],0,1,0,1),e.height=Math.min(c.translate(h,0,1,0,1),c.len)-e.y,h=m[1]):(e.height=0<k?c.translate(n,0,1,0,1)-e.y:c.translate(n,0,1,0,1)-c.translate(n-k,0,1,0,1),n+=q&&q[d.x]?q[d.x].total:k),0>e.height&&(e.y+=e.height,e.height*=-1),d.plotY=
e.y=Math.round(e.y)-this.borderWidth%2/2,e.height=Math.max(Math.round(e.height),.001),d.yBottom=e.y+e.height,e.height<=r&&!d.isNull?(e.height=r,e.y-=t,d.plotY=e.y,d.minPointLengthOffset=0>d.y?-t:t):d.minPointLengthOffset=0,e=d.plotY+(d.negative?e.height:0),this.chart.inverted?d.tooltipPos[0]=c.len-e:d.tooltipPos[1]=e},processData:function(b){var c=this.yData,a=this.options.data,g,d=c.length,e,q,l,k,n,m;q=e=l=k=this.options.threshold||0;for(m=0;m<d;m++)n=c[m],g=a&&a[m]?a[m]:{},"sum"===n||g.isSum?c[m]=
h(q):"intermediateSum"===n||g.isIntermediateSum?c[m]=h(e):(q+=n,e+=n),l=Math.min(q,l),k=Math.max(q,k);r.prototype.processData.call(this,b);this.options.stacking||(this.dataMin=l,this.dataMax=k)},toYData:function(b){return b.isSum?0===b.x?null:"sum":b.isIntermediateSum?0===b.x?null:"intermediateSum":b.y},getGraphPath:function(){return["M",0,0]},getCrispPath:function(){var b=this.data,c=b.length,a=this.graph.strokeWidth()+this.borderWidth,a=Math.round(a)%2/2,g=this.xAxis.reversed,d=this.yAxis.reversed,
e=[],q,l,k;for(k=1;k<c;k++){l=b[k].shapeArgs;q=b[k-1].shapeArgs;l=["M",q.x+(g?0:q.width),q.y+b[k-1].minPointLengthOffset+a,"L",l.x+(g?q.width:0),q.y+b[k-1].minPointLengthOffset+a];if(0>b[k-1].y&&!d||0<b[k-1].y&&d)l[2]+=q.height,l[5]+=q.height;e=e.concat(l)}return e},drawGraph:function(){r.prototype.drawGraph.call(this);this.graph.attr({d:this.getCrispPath()})},setStackedPoints:function(){var b=this.options,c,a;r.prototype.setStackedPoints.apply(this,arguments);c=this.stackedYData?this.stackedYData.length:
0;for(a=1;a<c;a++)b.data[a].isSum||b.data[a].isIntermediateSum||(this.stackedYData[a]+=this.stackedYData[a-1])},getExtremes:function(){if(this.options.stacking)return r.prototype.getExtremes.apply(this,arguments)}},{getClassName:function(){var b=m.prototype.getClassName.call(this);this.isSum?b+=" highcharts-sum":this.isIntermediateSum&&(b+=" highcharts-intermediate-sum");return b},isValid:function(){return v(this.y,!0)||this.isSum||this.isIntermediateSum}})})(x);(function(a){var h=a.Series,v=a.seriesType,
u=a.seriesTypes;v("polygon","scatter",{marker:{enabled:!1,states:{hover:{enabled:!1}}},stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:""},trackByArea:!0},{type:"polygon",getGraphPath:function(){for(var a=h.prototype.getGraphPath.call(this),r=a.length+1;r--;)(r===a.length||"M"===a[r])&&0<r&&a.splice(r,0,"z");return this.areaPath=a},drawGraph:function(){u.area.prototype.drawGraph.call(this)},drawLegendSymbol:a.LegendSymbolMixin.drawRectangle,drawTracker:h.prototype.drawTracker,setStackedPoints:a.noop})})(x);
(function(a){var h=a.arrayMax,v=a.arrayMin,u=a.Axis,m=a.each,r=a.isNumber,t=a.noop,p=a.pick,b=a.pInt,c=a.Point,f=a.seriesType,g=a.seriesTypes;f("bubble","scatter",{dataLabels:{formatter:function(){return this.point.z},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,
zoneAxis:"z"},{pointArrayMap:["y","z"],parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",bubblePadding:!0,zoneAxis:"z",directTouch:!0,getRadii:function(b,c,a,f){var d,e,g,q=this.zData,l=[],h=this.options,m="width"!==h.sizeBy,p=h.zThreshold,r=c-b;e=0;for(d=q.length;e<d;e++)g=q[e],h.sizeByAbsoluteValue&&null!==g&&(g=Math.abs(g-p),c=r=Math.max(c-p,Math.abs(b-p)),b=0),null===g?g=null:g<b?g=a/2-1:(g=0<r?(g-b)/r:.5,m&&0<=g&&(g=Math.sqrt(g)),g=Math.ceil(a+g*(f-a))/
2),l.push(g);this.radii=l},animate:function(b){!b&&this.points.length<this.options.animationLimit&&(m(this.points,function(b){var c=b.graphic,a;c&&c.width&&(a={x:c.x,y:c.y,width:c.width,height:c.height},c.attr({x:b.plotX,y:b.plotY,width:1,height:1}),c.animate(a,this.options.animation))},this),this.animate=null)},translate:function(){var b,c=this.data,f,l,k=this.radii;g.scatter.prototype.translate.call(this);for(b=c.length;b--;)f=c[b],l=k?k[b]:0,r(l)&&l>=this.minPxSize/2?(f.marker=a.extend(f.marker,
{radius:l,width:2*l,height:2*l}),f.dlBox={x:f.plotX-l,y:f.plotY-l,width:2*l,height:2*l}):f.shapeArgs=f.plotY=f.dlBox=void 0},alignDataLabel:g.column.prototype.alignDataLabel,buildKDTree:t,applyZones:t},{haloPath:function(b){return c.prototype.haloPath.call(this,0===b?0:(this.marker?this.marker.radius||0:0)+b)},ttBelow:!1});u.prototype.beforePadding=function(){var c=this,a=this.len,f=this.chart,g=0,k=a,n=this.isXAxis,t=n?"xData":"yData",u=this.min,x={},y=Math.min(f.plotWidth,f.plotHeight),C=Number.MAX_VALUE,
D=-Number.MAX_VALUE,z=this.max-u,B=a/z,E=[];m(this.series,function(a){var d=a.options;!a.bubblePadding||!a.visible&&f.options.chart.ignoreHiddenSeries||(c.allowZoomOutside=!0,E.push(a),n&&(m(["minSize","maxSize"],function(c){var a=d[c],e=/%$/.test(a),a=b(a);x[c]=e?y*a/100:a}),a.minPxSize=x.minSize,a.maxPxSize=Math.max(x.maxSize,x.minSize),a=a.zData,a.length&&(C=p(d.zMin,Math.min(C,Math.max(v(a),!1===d.displayNegative?d.zThreshold:-Number.MAX_VALUE))),D=p(d.zMax,Math.max(D,h(a))))))});m(E,function(b){var a=
b[t],d=a.length,e;n&&b.getRadii(C,D,b.minPxSize,b.maxPxSize);if(0<z)for(;d--;)r(a[d])&&c.dataMin<=a[d]&&a[d]<=c.dataMax&&(e=b.radii[d],g=Math.min((a[d]-u)*B-e,g),k=Math.max((a[d]-u)*B+e,k))});E.length&&0<z&&!this.isLog&&(k-=a,B*=(a+g-k)/a,m([["min","userMin",g],["max","userMax",k]],function(b){void 0===p(c.options[b[0]],c[b[1]])&&(c[b[0]]+=b[2]/B)}))}})(x);(function(a){var h=a.each,v=a.pick,u=a.Series,m=a.seriesTypes,r=a.wrap,t=u.prototype,p=a.Pointer.prototype;a.polarExtended||(a.polarExtended=!0,
t.searchPointByAngle=function(b){var a=this.chart,f=this.xAxis.pane.center;return this.searchKDTree({clientX:180+-180/Math.PI*Math.atan2(b.chartX-f[0]-a.plotLeft,b.chartY-f[1]-a.plotTop)})},t.getConnectors=function(b,a,f,g){var c,e,h,l,k,n,m,p;e=g?1:0;c=0<=a&&a<=b.length-1?a:0>a?b.length-1+a:0;a=0>c-1?b.length-(1+e):c-1;e=c+1>b.length-1?e:c+1;h=b[a];e=b[e];l=h.plotX;h=h.plotY;k=e.plotX;n=e.plotY;e=b[c].plotX;c=b[c].plotY;l=(1.5*e+l)/2.5;h=(1.5*c+h)/2.5;k=(1.5*e+k)/2.5;m=(1.5*c+n)/2.5;n=Math.sqrt(Math.pow(l-
e,2)+Math.pow(h-c,2));p=Math.sqrt(Math.pow(k-e,2)+Math.pow(m-c,2));l=Math.atan2(h-c,l-e);m=Math.PI/2+(l+Math.atan2(m-c,k-e))/2;Math.abs(l-m)>Math.PI/2&&(m-=Math.PI);l=e+Math.cos(m)*n;h=c+Math.sin(m)*n;k=e+Math.cos(Math.PI+m)*p;m=c+Math.sin(Math.PI+m)*p;e={rightContX:k,rightContY:m,leftContX:l,leftContY:h,plotX:e,plotY:c};f&&(e.prevPointCont=this.getConnectors(b,a,!1,g));return e},r(t,"buildKDTree",function(b){this.chart.polar&&(this.kdByAngle?this.searchPoint=this.searchPointByAngle:this.options.findNearestPointBy=
"xy");b.apply(this)}),t.toXY=function(b){var a,f=this.chart,g=b.plotX;a=b.plotY;b.rectPlotX=g;b.rectPlotY=a;a=this.xAxis.postTranslate(b.plotX,this.yAxis.len-a);b.plotX=b.polarPlotX=a.x-f.plotLeft;b.plotY=b.polarPlotY=a.y-f.plotTop;this.kdByAngle?(f=(g/Math.PI*180+this.xAxis.pane.options.startAngle)%360,0>f&&(f+=360),b.clientX=f):b.clientX=b.plotX},m.spline&&(r(m.spline.prototype,"getPointSpline",function(b,a,f,g){this.chart.polar?g?(b=this.getConnectors(a,g,!0,this.connectEnds),b=["C",b.prevPointCont.rightContX,
b.prevPointCont.rightContY,b.leftContX,b.leftContY,b.plotX,b.plotY]):b=["M",f.plotX,f.plotY]:b=b.call(this,a,f,g);return b}),m.areasplinerange&&(m.areasplinerange.prototype.getPointSpline=m.spline.prototype.getPointSpline)),a.addEvent(u,"afterTranslate",function(){var b=this.chart,c,f;if(b.polar){this.kdByAngle=b.tooltip&&b.tooltip.shared;if(!this.preventPostTranslate)for(c=this.points,f=c.length;f--;)this.toXY(c[f]);this.hasClipCircleSetter||(this.hasClipCircleSetter=!!a.addEvent(this,"afterRender",
function(){var c;b.polar&&(c=this.yAxis.center,this.group.clip(b.renderer.clipCircle(c[0],c[1],c[2]/2)),this.setClip=a.noop)}))}}),r(t,"getGraphPath",function(b,a){var c=this,g,d,e;if(this.chart.polar){a=a||this.points;for(g=0;g<a.length;g++)if(!a[g].isNull){d=g;break}!1!==this.options.connectEnds&&void 0!==d&&(this.connectEnds=!0,a.splice(a.length,0,a[d]),e=!0);h(a,function(b){void 0===b.polarPlotY&&c.toXY(b)})}g=b.apply(this,[].slice.call(arguments,1));e&&a.pop();return g}),u=function(b,a){var c=
this.chart,g=this.options.animation,d=this.group,e=this.markerGroup,h=this.xAxis.center,l=c.plotLeft,k=c.plotTop;c.polar?c.renderer.isSVG&&(!0===g&&(g={}),a?(b={translateX:h[0]+l,translateY:h[1]+k,scaleX:.001,scaleY:.001},d.attr(b),e&&e.attr(b)):(b={translateX:l,translateY:k,scaleX:1,scaleY:1},d.animate(b,g),e&&e.animate(b,g),this.animate=null)):b.call(this,a)},r(t,"animate",u),m.column&&(m=m.column.prototype,m.polarArc=function(b,a,f,g){var c=this.xAxis.center,e=this.yAxis.len;return this.chart.renderer.symbols.arc(c[0],
c[1],e-a,null,{start:f,end:g,innerR:e-v(b,e)})},r(m,"animate",u),r(m,"translate",function(b){var a=this.xAxis,f=a.startAngleRad,g,d,e;this.preventPostTranslate=!0;b.call(this);if(a.isRadial)for(g=this.points,e=g.length;e--;)d=g[e],b=d.barX+f,d.shapeType="path",d.shapeArgs={d:this.polarArc(d.yBottom,d.plotY,b,b+d.pointWidth)},this.toXY(d),d.tooltipPos=[d.plotX,d.plotY],d.ttBelow=d.plotY>a.center[1]}),r(m,"alignDataLabel",function(a,c,f,g,d,e){this.chart.polar?(a=c.rectPlotX/Math.PI*180,null===g.align&&
(g.align=20<a&&160>a?"left":200<a&&340>a?"right":"center"),null===g.verticalAlign&&(g.verticalAlign=45>a||315<a?"bottom":135<a&&225>a?"top":"middle"),t.alignDataLabel.call(this,c,f,g,d,e)):a.call(this,c,f,g,d,e)})),r(p,"getCoordinates",function(a,c){var b=this.chart,g={xAxis:[],yAxis:[]};b.polar?h(b.axes,function(a){var d=a.isXAxis,f=a.center,h=c.chartX-f[0]-b.plotLeft,f=c.chartY-f[1]-b.plotTop;g[d?"xAxis":"yAxis"].push({axis:a,value:a.translate(d?Math.PI-Math.atan2(h,f):Math.sqrt(Math.pow(h,2)+Math.pow(f,
2)),!0)})}):g=a.call(this,c);return g}),a.SVGRenderer.prototype.clipCircle=function(b,c,f){var g=a.uniqueKey(),d=this.createElement("clipPath").attr({id:g}).add(this.defs);b=this.circle(b,c,f).add(d);b.id=g;b.clipPath=d;return b},a.addEvent(a.Chart,"getAxes",function(){this.pane||(this.pane=[]);h(a.splat(this.options.pane),function(b){new a.Pane(b,this)},this)}),a.addEvent(a.Chart,"afterDrawChartBox",function(){h(this.pane,function(a){a.render()})}),r(a.Chart.prototype,"get",function(b,c){return a.find(this.pane,
function(a){return a.options.id===c})||b.call(this,c)}))})(x)});
