/*
 Highcharts JS v6.1.0-modified (2018-05-17)
 Highstock as a plugin for Highcharts

 (c) 2017 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(K){"object"===typeof module&&module.exports?module.exports=K:K(Highcharts)})(function(K){(function(a){var E=a.addEvent,z=a.Axis,D=a.Chart,A=a.css,H=a.defined,w=a.each,y=a.extend,G=a.noop,q=a.pick,u=a.timeUnits,B=a.wrap;B(a.Series.prototype,"init",function(e){var a;e.apply(this,Array.prototype.slice.call(arguments,1));(a=this.xAxis)&&a.options.ordinal&&E(this,"updatedData",function(){delete a.ordinalIndex})});B(z.prototype,"getTimeTicks",function(e,a,r,k,m,p,g,c){var b=0,f,h,d={},x,J,l,C=
[],n=-Number.MAX_VALUE,v=this.options.tickPixelInterval,t=this.chart.time;if(!this.options.ordinal&&!this.options.breaks||!p||3>p.length||void 0===r)return e.call(this,a,r,k,m);J=p.length;for(f=0;f<J;f++){l=f&&p[f-1]>k;p[f]<r&&(b=f);if(f===J-1||p[f+1]-p[f]>5*g||l){if(p[f]>n){for(h=e.call(this,a,p[b],p[f],m);h.length&&h[0]<=n;)h.shift();h.length&&(n=h[h.length-1]);C=C.concat(h)}b=f+1}if(l)break}e=h.info;if(c&&e.unitRange<=u.hour){f=C.length-1;for(b=1;b<f;b++)t.dateFormat("%d",C[b])!==t.dateFormat("%d",
C[b-1])&&(d[C[b]]="day",x=!0);x&&(d[C[0]]="day");e.higherRanks=d}C.info=e;if(c&&H(v)){c=t=C.length;f=[];var L;for(x=[];c--;)b=this.translate(C[c]),L&&(x[c]=L-b),f[c]=L=b;x.sort();x=x[Math.floor(x.length/2)];x<.6*v&&(x=null);c=C[t-1]>k?t-1:t;for(L=void 0;c--;)b=f[c],k=Math.abs(L-b),L&&k<.8*v&&(null===x||k<.8*x)?(d[C[c]]&&!d[C[c+1]]?(k=c+1,L=b):k=c,C.splice(k,1)):L=b}return C});y(z.prototype,{beforeSetTickPositions:function(){var e,a=[],r=!1,k,m=this.getExtremes(),p=m.min,g=m.max,c,b=this.isXAxis&&
!!this.options.breaks,m=this.options.ordinal,f=Number.MAX_VALUE,h=this.chart.options.chart.ignoreHiddenSeries;k="highcharts-navigator-xaxis"===this.options.className;!this.options.overscroll||this.max!==this.dataMax||this.chart.mouseIsDown&&!k||this.eventArgs&&(!this.eventArgs||"navigator"===this.eventArgs.trigger)||(this.max+=this.options.overscroll,!k&&H(this.userMin)&&(this.min+=this.options.overscroll));if(m||b){w(this.series,function(g,x){if(!(h&&!1===g.visible||!1===g.takeOrdinalPosition&&!b)&&
(a=a.concat(g.processedXData),e=a.length,a.sort(function(b,g){return b-g}),f=Math.min(f,q(g.closestPointRange,f)),e))for(x=e-1;x--;)a[x]===a[x+1]&&a.splice(x,1)});e=a.length;if(2<e){k=a[1]-a[0];for(c=e-1;c--&&!r;)a[c+1]-a[c]!==k&&(r=!0);!this.options.keepOrdinalPadding&&(a[0]-p>k||g-a[a.length-1]>k)&&(r=!0)}else this.options.overscroll&&(2===e?f=a[1]-a[0]:1===e?(f=this.options.overscroll,a=[a[0],a[0]+f]):f=this.overscrollPointsRange);r?(this.options.overscroll&&(this.overscrollPointsRange=f,a=a.concat(this.getOverscrollPositions())),
this.ordinalPositions=a,k=this.ordinal2lin(Math.max(p,a[0]),!0),c=Math.max(this.ordinal2lin(Math.min(g,a[a.length-1]),!0),1),this.ordinalSlope=g=(g-p)/(c-k),this.ordinalOffset=p-k*g):(this.overscrollPointsRange=q(this.closestPointRange,this.overscrollPointsRange),this.ordinalPositions=this.ordinalSlope=this.ordinalOffset=void 0)}this.isOrdinal=m&&r;this.groupIntervalFactor=null},val2lin:function(a,l){var e=this.ordinalPositions;if(e){var k=e.length,m,p;for(m=k;m--;)if(e[m]===a){p=m;break}for(m=k-
1;m--;)if(a>e[m]||0===m){a=(a-e[m])/(e[m+1]-e[m]);p=m+a;break}l=l?p:this.ordinalSlope*(p||0)+this.ordinalOffset}else l=a;return l},lin2val:function(a,l){var e=this.ordinalPositions;if(e){var k=this.ordinalSlope,m=this.ordinalOffset,p=e.length-1,g;if(l)0>a?a=e[0]:a>p?a=e[p]:(p=Math.floor(a),g=a-p);else for(;p--;)if(l=k*p+m,a>=l){k=k*(p+1)+m;g=(a-l)/(k-l);break}return void 0!==g&&void 0!==e[p]?e[p]+(g?g*(e[p+1]-e[p]):0):a}return a},getExtendedPositions:function(){var a=this,l=a.chart,r=a.series[0].currentDataGrouping,
k=a.ordinalIndex,m=r?r.count+r.unitName:"raw",p=a.options.overscroll,g=a.getExtremes(),c,b;k||(k=a.ordinalIndex={});k[m]||(c={series:[],chart:l,getExtremes:function(){return{min:g.dataMin,max:g.dataMax+p}},options:{ordinal:!0},val2lin:z.prototype.val2lin,ordinal2lin:z.prototype.ordinal2lin},w(a.series,function(g){b={xAxis:c,xData:g.xData.slice(),chart:l,destroyGroupedData:G};b.xData=b.xData.concat(a.getOverscrollPositions());b.options={dataGrouping:r?{enabled:!0,forced:!0,approximation:"open",units:[[r.unitName,
[r.count]]]}:{enabled:!1}};g.processData.apply(b);c.series.push(b)}),a.beforeSetTickPositions.apply(c),k[m]=c.ordinalPositions);return k[m]},getOverscrollPositions:function(){var e=this.options.overscroll,l=this.overscrollPointsRange,r=[],k=this.dataMax;if(a.defined(l))for(r.push(k);k<=this.dataMax+e;)k+=l,r.push(k);return r},getGroupIntervalFactor:function(a,l,r){var e;r=r.processedXData;var m=r.length,p=[];e=this.groupIntervalFactor;if(!e){for(e=0;e<m-1;e++)p[e]=r[e+1]-r[e];p.sort(function(a,c){return a-
c});p=p[Math.floor(m/2)];a=Math.max(a,r[0]);l=Math.min(l,r[m-1]);this.groupIntervalFactor=e=m*p/(l-a)}return e},postProcessTickInterval:function(a){var e=this.ordinalSlope;return e?this.options.breaks?this.closestPointRange||a:a/(e/this.closestPointRange):a}});z.prototype.ordinal2lin=z.prototype.val2lin;B(D.prototype,"pan",function(a,l){var e=this.xAxis[0],k=e.options.overscroll,m=l.chartX,p=!1;if(e.options.ordinal&&e.series.length){var g=this.mouseDownX,c=e.getExtremes(),b=c.dataMax,f=c.min,h=c.max,
d=this.hoverPoints,x=e.closestPointRange||e.overscrollPointsRange,g=(g-m)/(e.translationSlope*(e.ordinalSlope||x)),J={ordinalPositions:e.getExtendedPositions()},x=e.lin2val,M=e.val2lin,C;J.ordinalPositions?1<Math.abs(g)&&(d&&w(d,function(n){n.setState()}),0>g?(d=J,C=e.ordinalPositions?e:J):(d=e.ordinalPositions?e:J,C=J),J=C.ordinalPositions,b>J[J.length-1]&&J.push(b),this.fixedRange=h-f,g=e.toFixedRange(null,null,x.apply(d,[M.apply(d,[f,!0])+g,!0]),x.apply(C,[M.apply(C,[h,!0])+g,!0])),g.min>=Math.min(c.dataMin,
f)&&g.max<=Math.max(b,h)+k&&e.setExtremes(g.min,g.max,!0,!1,{trigger:"pan"}),this.mouseDownX=m,A(this.container,{cursor:"move"})):p=!0}else p=!0;p&&(k&&(e.max=e.dataMax+k),a.apply(this,Array.prototype.slice.call(arguments,1)))})})(K);(function(a){function E(){return Array.prototype.slice.call(arguments,1)}function z(a){a.apply(this);this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,A(this.pointArrayMap,["y"]))}var D=a.addEvent,A=a.pick,H=a.wrap,w=a.each,y=a.extend,G=a.isArray,q=a.fireEvent,
u=a.Axis,B=a.Series;y(u.prototype,{isInBreak:function(a,l){var e=a.repeat||Infinity,k=a.from,m=a.to-a.from;l=l>=k?(l-k)%e:e-(k-l)%e;return a.inclusive?l<=m:l<m&&0!==l},isInAnyBreak:function(a,l){var e=this.options.breaks,k=e&&e.length,m,p,g;if(k){for(;k--;)this.isInBreak(e[k],a)&&(m=!0,p||(p=A(e[k].showPoints,this.isXAxis?!1:!0)));g=m&&l?m&&!p:m}return g}});D(u,"afterSetTickPositions",function(){if(this.options.breaks){var a=this.tickPositions,l=this.tickPositions.info,r=[],k;for(k=0;k<a.length;k++)this.isInAnyBreak(a[k])||
r.push(a[k]);this.tickPositions=r;this.tickPositions.info=l}});D(u,"afterSetOptions",function(){this.options.breaks&&this.options.breaks.length&&(this.options.ordinal=!1)});D(u,"afterInit",function(){var a=this,l;l=this.options.breaks;a.isBroken=G(l)&&!!l.length;a.isBroken&&(a.val2lin=function(e){var k=e,m,l;for(l=0;l<a.breakArray.length;l++)if(m=a.breakArray[l],m.to<=e)k-=m.len;else if(m.from>=e)break;else if(a.isInBreak(m,e)){k-=e-m.from;break}return k},a.lin2val=function(e){var k,m;for(m=0;m<a.breakArray.length&&
!(k=a.breakArray[m],k.from>=e);m++)k.to<e?e+=k.len:a.isInBreak(k,e)&&(e+=k.len);return e},a.setExtremes=function(a,e,m,l,g){for(;this.isInAnyBreak(a);)a-=this.closestPointRange;for(;this.isInAnyBreak(e);)e-=this.closestPointRange;u.prototype.setExtremes.call(this,a,e,m,l,g)},a.setAxisTranslation=function(e){u.prototype.setAxisTranslation.call(this,e);e=a.options.breaks;var k=[],m=[],l=0,g,c,b=a.userMin||a.min,f=a.userMax||a.max,h=A(a.pointRangePadding,0),d,x;w(e,function(g){c=g.repeat||Infinity;a.isInBreak(g,
b)&&(b+=g.to%c-b%c);a.isInBreak(g,f)&&(f-=f%c-g.from%c)});w(e,function(a){d=a.from;for(c=a.repeat||Infinity;d-c>b;)d-=c;for(;d<b;)d+=c;for(x=d;x<f;x+=c)k.push({value:x,move:"in"}),k.push({value:x+(a.to-a.from),move:"out",size:a.breakSize})});k.sort(function(a,b){return a.value===b.value?("in"===a.move?0:1)-("in"===b.move?0:1):a.value-b.value});g=0;d=b;w(k,function(a){g+="in"===a.move?1:-1;1===g&&"in"===a.move&&(d=a.value);0===g&&(m.push({from:d,to:a.value,len:a.value-d-(a.size||0)}),l+=a.value-d-
(a.size||0))});a.breakArray=m;a.unitLength=f-b-l+h;q(a,"afterBreaks");a.options.staticScale?a.transA=a.options.staticScale:a.unitLength&&(a.transA*=(f-a.min+h)/a.unitLength);h&&(a.minPixelPadding=a.transA*a.minPointOffset);a.min=b;a.max=f})});H(B.prototype,"generatePoints",function(a){a.apply(this,E(arguments));var e=this.xAxis,r=this.yAxis,k=this.points,m,p=k.length,g=this.options.connectNulls,c;if(e&&r&&(e.options.breaks||r.options.breaks))for(;p--;)m=k[p],c=null===m.y&&!1===g,c||!e.isInAnyBreak(m.x,
!0)&&!r.isInAnyBreak(m.y,!0)||(k.splice(p,1),this.data[p]&&this.data[p].destroyElements())});a.Series.prototype.drawBreaks=function(a,l){var e=this,k=e.points,m,p,g,c;a&&w(l,function(b){m=a.breakArray||[];p=a.isXAxis?a.min:A(e.options.threshold,a.min);w(k,function(f){c=A(f["stack"+b.toUpperCase()],f[b]);w(m,function(b){g=!1;if(p<b.from&&c>b.to||p>b.from&&c<b.from)g="pointBreak";else if(p<b.from&&c>b.from&&c<b.to||p>b.from&&c>b.to&&c<b.from)g="pointInBreak";g&&q(a,g,{point:f,brk:b})})})})};a.Series.prototype.gappedPath=
function(){var e=this.currentDataGrouping,l=e&&e.totalRange,e=this.options.gapSize,r=this.points.slice(),k=r.length-1,m=this.yAxis;if(e&&0<k)for("value"!==this.options.gapUnit&&(e*=this.closestPointRange),l&&l>e&&(e=l);k--;)r[k+1].x-r[k].x>e&&(l=(r[k].x+r[k+1].x)/2,r.splice(k+1,0,{isNull:!0,x:l}),this.options.stacking&&(l=m.stacks[this.stackKey][l]=new a.StackItem(m,m.options.stackLabels,!1,l,this.stack),l.total=0));return this.getGraphPath(r)};H(a.seriesTypes.column.prototype,"drawPoints",z);H(a.Series.prototype,
"drawPoints",z)})(K);(function(a){var E=a.addEvent,z=a.arrayMax,D=a.arrayMin,A=a.Axis,H=a.defaultPlotOptions,w=a.defined,y=a.each,G=a.extend,q=a.format,u=a.isNumber,B=a.merge,e=a.pick,l=a.Point,r=a.Series,k=a.Tooltip,m=a.wrap,p=r.prototype,g=p.processData,c=p.generatePoints,b={approximation:"average",groupPixelWidth:2,dateTimeLabelFormats:{millisecond:["%A, %b %e, %H:%M:%S.%L","%A, %b %e, %H:%M:%S.%L","-%H:%M:%S.%L"],second:["%A, %b %e, %H:%M:%S","%A, %b %e, %H:%M:%S","-%H:%M:%S"],minute:["%A, %b %e, %H:%M",
"%A, %b %e, %H:%M","-%H:%M"],hour:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],day:["%A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],week:["Week from %A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],month:["%B %Y","%B","-%B %Y"],year:["%Y","%Y","-%Y"]}},f={line:{},spline:{},area:{},areaspline:{},column:{approximation:"sum",groupPixelWidth:10},arearange:{approximation:"range"},areasplinerange:{approximation:"range"},columnrange:{approximation:"range",groupPixelWidth:10},candlestick:{approximation:"ohlc",
groupPixelWidth:10},ohlc:{approximation:"ohlc",groupPixelWidth:5}},h=a.defaultDataGroupingUnits=[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1]],["week",[1]],["month",[1,3,6]],["year",null]],d=a.approximations={sum:function(a){var b=a.length,g;if(!b&&a.hasNulls)g=null;else if(b)for(g=0;b--;)g+=a[b];return g},average:function(a){var b=a.length;a=d.sum(a);u(a)&&b&&(a/=b);return a},averages:function(){var a=
[];y(arguments,function(b){a.push(d.average(b))});return void 0===a[0]?void 0:a},open:function(a){return a.length?a[0]:a.hasNulls?null:void 0},high:function(a){return a.length?z(a):a.hasNulls?null:void 0},low:function(a){return a.length?D(a):a.hasNulls?null:void 0},close:function(a){return a.length?a[a.length-1]:a.hasNulls?null:void 0},ohlc:function(a,b,g,f){a=d.open(a);b=d.high(b);g=d.low(g);f=d.close(f);if(u(a)||u(b)||u(g)||u(f))return[a,b,g,f]},range:function(a,b){a=d.low(a);b=d.high(b);if(u(a)||
u(b))return[a,b];if(null===a&&null===b)return null}};p.groupData=function(a,g,h,c){var n=this.data,v=this.options.data,t=[],e=[],I=[],x=a.length,F,k,m=!!g,l=[];c="function"===typeof c?c:d[c]||f[this.type]&&d[f[this.type].approximation]||d[b.approximation];var J=this.pointArrayMap,r=J&&J.length,p=0;k=0;var M,C;r?y(J,function(){l.push([])}):l.push([]);M=r||1;for(C=0;C<=x&&!(a[C]>=h[0]);C++);for(C;C<=x;C++){for(;void 0!==h[p+1]&&a[C]>=h[p+1]||C===x;){F=h[p];this.dataGroupInfo={start:k,length:l[0].length};
k=c.apply(this,l);void 0!==k&&(t.push(F),e.push(k),I.push(this.dataGroupInfo));k=C;for(F=0;F<M;F++)l[F].length=0,l[F].hasNulls=!1;p+=1;if(C===x)break}if(C===x)break;if(J){F=this.cropStart+C;var q=n&&n[F]||this.pointClass.prototype.applyOptions.apply({series:this},[v[F]]),w;for(F=0;F<r;F++)w=q[J[F]],u(w)?l[F].push(w):null===w&&(l[F].hasNulls=!0)}else F=m?g[C]:null,u(F)?l[0].push(F):null===F&&(l[0].hasNulls=!0)}return[t,e,I]};p.processData=function(){var a=this.chart,b=this.options.dataGrouping,f=!1!==
this.allowDG&&b&&e(b.enabled,a.options.isStock),c=this.visible||!a.options.chart.ignoreHiddenSeries,n,v=this.currentDataGrouping,t;this.forceCrop=f;this.groupPixelWidth=null;this.hasProcessed=!0;if(!1!==g.apply(this,arguments)&&f){this.destroyGroupedData();var d,I=b.groupAll?this.xData:this.processedXData,k=b.groupAll?this.yData:this.processedYData,F=a.plotSizeX,a=this.xAxis,m=a.options.ordinal,l=this.groupPixelWidth=a.getGroupPixelWidth&&a.getGroupPixelWidth();if(l){this.isDirty=n=!0;this.points=
null;f=a.getExtremes();t=f.min;f=f.max;m=m&&a.getGroupIntervalFactor(t,f,this)||1;l=l*(f-t)/F*m;F=a.getTimeTicks(a.normalizeTimeTickInterval(l,b.units||h),Math.min(t,I[0]),Math.max(f,I[I.length-1]),a.options.startOfWeek,I,this.closestPointRange);k=p.groupData.apply(this,[I,k,F,b.approximation]);I=k[0];m=k[1];if(b.smoothed&&I.length){d=I.length-1;for(I[d]=Math.min(I[d],f);d--&&0<d;)I[d]+=l/2;I[0]=Math.max(I[0],t)}t=F.info;this.closestPointRange=F.info.totalRange;this.groupMap=k[2];w(I[0])&&I[0]<a.dataMin&&
c&&(a.min<=a.dataMin&&(a.min=I[0]),a.dataMin=I[0]);b.groupAll&&(b=this.cropData(I,m,a.min,a.max,1),I=b.xData,m=b.yData);this.processedXData=I;this.processedYData=m}else this.groupMap=null;this.hasGroupedData=n;this.currentDataGrouping=t;this.preventGraphAnimation=(v&&v.totalRange)!==(t&&t.totalRange)}};p.destroyGroupedData=function(){var a=this.groupedData;y(a||[],function(b,g){b&&(a[g]=b.destroy?b.destroy():null)});this.groupedData=null};p.generatePoints=function(){c.apply(this);this.destroyGroupedData();
this.groupedData=this.hasGroupedData?this.points:null};E(l,"update",function(){if(this.dataGroup)return a.error(24),!1});m(k.prototype,"tooltipFooterHeaderFormatter",function(a,b,g){var f=this.chart.time,n=b.series,v=n.tooltipOptions,t=n.options.dataGrouping,d=v.xDateFormat,h,c=n.xAxis;return c&&"datetime"===c.options.type&&t&&u(b.key)?(a=n.currentDataGrouping,t=t.dateTimeLabelFormats,a?(c=t[a.unitName],1===a.count?d=c[0]:(d=c[1],h=c[2])):!d&&t&&(d=this.getXDateFormat(b,v,c)),d=f.dateFormat(d,b.key),
h&&(d+=f.dateFormat(h,b.key+a.totalRange-1)),q(v[(g?"footer":"header")+"Format"],{point:G(b.point,{key:d}),series:n},f)):a.call(this,b,g)});E(r,"destroy",p.destroyGroupedData);E(r,"afterSetOptions",function(a){a=a.options;var g=this.type,d=this.chart.options.plotOptions,c=H[g].dataGrouping,n=this.useCommonDataGrouping&&b;if(f[g]||n)c||(c=B(b,f[g])),a.dataGrouping=B(n,c,d.series&&d.series.dataGrouping,d[g].dataGrouping,this.userOptions.dataGrouping);this.chart.options.isStock&&(this.requireSorting=
!0)});E(A,"afterSetScale",function(){y(this.series,function(a){a.hasProcessed=!1})});A.prototype.getGroupPixelWidth=function(){var a=this.series,b=a.length,g,d=0,n=!1,v;for(g=b;g--;)(v=a[g].options.dataGrouping)&&(d=Math.max(d,v.groupPixelWidth));for(g=b;g--;)(v=a[g].options.dataGrouping)&&a[g].hasProcessed&&(b=(a[g].processedXData||a[g].data).length,a[g].groupPixelWidth||b>this.chart.plotSizeX/d||b&&v.forced)&&(n=!0);return n?d:0};A.prototype.setDataGrouping=function(a,b){var g;b=e(b,!0);a||(a={forced:!1,
units:null});if(this instanceof A)for(g=this.series.length;g--;)this.series[g].update({dataGrouping:a},!1);else y(this.chart.options.series,function(b){b.dataGrouping=a},!1);this.ordinalSlope=null;b&&this.chart.redraw()}})(K);(function(a){var E=a.each,z=a.Point,D=a.seriesType,A=a.seriesTypes;D("ohlc","column",{lineWidth:1,tooltip:{pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e \x3cb\x3e {series.name}\x3c/b\x3e\x3cbr/\x3eOpen: {point.open}\x3cbr/\x3eHigh: {point.high}\x3cbr/\x3eLow: {point.low}\x3cbr/\x3eClose: {point.close}\x3cbr/\x3e'},
threshold:null,states:{hover:{lineWidth:3}},stickyTracking:!0},{directTouch:!1,pointArrayMap:["open","high","low","close"],toYData:function(a){return[a.open,a.high,a.low,a.close]},pointValKey:"close",pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},pointAttribs:function(a,w){w=A.column.prototype.pointAttribs.call(this,a,w);var y=this.options;delete w.fill;!a.options.color&&y.upColor&&a.open<a.close&&(w.stroke=y.upColor);return w},translate:function(){var a=this,w=a.yAxis,y=!!a.modifyValue,
G=["plotOpen","plotHigh","plotLow","plotClose","yBottom"];A.column.prototype.translate.apply(a);E(a.points,function(q){E([q.open,q.high,q.low,q.close,q.low],function(u,B){null!==u&&(y&&(u=a.modifyValue(u)),q[G[B]]=w.toPixels(u,!0))});q.tooltipPos[1]=q.plotHigh+w.pos-a.chart.plotTop})},drawPoints:function(){var a=this,w=a.chart;E(a.points,function(y){var G,q,u,B,e=y.graphic,l,r=!e;void 0!==y.plotY&&(e||(y.graphic=e=w.renderer.path().add(a.group)),e.attr(a.pointAttribs(y,y.selected&&"select")),q=e.strokeWidth()%
2/2,l=Math.round(y.plotX)-q,u=Math.round(y.shapeArgs.width/2),B=["M",l,Math.round(y.yBottom),"L",l,Math.round(y.plotHigh)],null!==y.open&&(G=Math.round(y.plotOpen)+q,B.push("M",l,G,"L",l-u,G)),null!==y.close&&(G=Math.round(y.plotClose)+q,B.push("M",l,G,"L",l+u,G)),e[r?"attr":"animate"]({d:B}).addClass(y.getClassName(),!0))})},animate:null},{getClassName:function(){return z.prototype.getClassName.call(this)+(this.open<this.close?" highcharts-point-up":" highcharts-point-down")}})})(K);(function(a){var E=
a.defaultPlotOptions,z=a.each,D=a.merge,A=a.seriesType,H=a.seriesTypes;A("candlestick","ohlc",D(E.column,{states:{hover:{lineWidth:2}},tooltip:E.ohlc.tooltip,threshold:null,lineColor:"#000000",lineWidth:1,upColor:"#ffffff",stickyTracking:!0}),{pointAttribs:function(a,y){var w=H.column.prototype.pointAttribs.call(this,a,y),q=this.options,u=a.open<a.close,B=q.lineColor||this.color;w["stroke-width"]=q.lineWidth;w.fill=a.options.color||(u?q.upColor||this.color:this.color);w.stroke=a.lineColor||(u?q.upLineColor||
B:B);y&&(a=q.states[y],w.fill=a.color||w.fill,w.stroke=a.lineColor||w.stroke,w["stroke-width"]=a.lineWidth||w["stroke-width"]);return w},drawPoints:function(){var a=this,y=a.chart;z(a.points,function(w){var q=w.graphic,u,B,e,l,r,k,m,p=!q;void 0!==w.plotY&&(q||(w.graphic=q=y.renderer.path().add(a.group)),q.attr(a.pointAttribs(w,w.selected&&"select")).shadow(a.options.shadow),r=q.strokeWidth()%2/2,k=Math.round(w.plotX)-r,u=w.plotOpen,B=w.plotClose,e=Math.min(u,B),u=Math.max(u,B),m=Math.round(w.shapeArgs.width/
2),B=Math.round(e)!==Math.round(w.plotHigh),l=u!==w.yBottom,e=Math.round(e)+r,u=Math.round(u)+r,r=[],r.push("M",k-m,u,"L",k-m,e,"L",k+m,e,"L",k+m,u,"Z","M",k,e,"L",k,B?Math.round(w.plotHigh):e,"M",k,u,"L",k,l?Math.round(w.yBottom):u),q[p?"attr":"animate"]({d:r}).addClass(w.getClassName(),!0))})}})})(K);var U=function(a){var E=a.each,z=a.defined,D=a.seriesTypes,A=a.stableSort;return{getPlotBox:function(){return a.Series.prototype.getPlotBox.call(this.options.onSeries&&this.chart.get(this.options.onSeries)||
this)},translate:function(){D.column.prototype.translate.apply(this);var a=this.options,w=this.chart,y=this.points,G=y.length-1,q,u,B=a.onSeries,B=B&&w.get(B),a=a.onKey||"y",e=B&&B.options.step,l=B&&B.points,r=l&&l.length,k=w.inverted,m=this.xAxis,p=this.yAxis,g=0,c,b,f,h;if(B&&B.visible&&r)for(g=(B.pointXOffset||0)+(B.barW||0)/2,q=B.currentDataGrouping,b=l[r-1].x+(q?q.totalRange:0),A(y,function(a,b){return a.x-b.x}),a="plot"+a[0].toUpperCase()+a.substr(1);r--&&y[G]&&!(c=l[r],q=y[G],q.y=c.y,c.x<=
q.x&&void 0!==c[a]&&(q.x<=b&&(q.plotY=c[a],c.x<q.x&&!e&&(f=l[r+1])&&void 0!==f[a]&&(h=(q.x-c.x)/(f.x-c.x),q.plotY+=h*(f[a]-c[a]),q.y+=h*(f.y-c.y))),G--,r++,0>G)););E(y,function(a,b){var f;a.plotX+=g;if(void 0===a.plotY||k)0<=a.plotX&&a.plotX<=m.len?k?(a.plotY=m.translate(a.x,0,1,0,1),a.plotX=z(a.y)?p.translate(a.y,0,0,0,1):0):a.plotY=w.chartHeight-m.bottom-(m.opposite?m.height:0)+m.offset-p.top:a.shapeArgs={};(u=y[b-1])&&u.plotX===a.plotX&&(void 0===u.stackIndex&&(u.stackIndex=0),f=u.stackIndex+1);
a.stackIndex=f});this.onSeries=B}}}(K);(function(a,E){function z(a){B[a+"pin"]=function(e,r,k,m,p){var g=p&&p.anchorX;p=p&&p.anchorY;"circle"===a&&m>k&&(e-=Math.round((m-k)/2),k=m);e=B[a](e,r,k,m);g&&p&&(e.push("M","circle"===a?e[1]-e[4]:e[1]+e[4]/2,r>p?r:r+m,"L",g,p),e=e.concat(B.circle(g-1,p-1,2,2)));return e}}var D=a.addEvent,A=a.each,H=a.merge,w=a.noop,y=a.Renderer,G=a.seriesType,q=a.TrackerMixin,u=a.VMLRenderer,B=a.SVGRenderer.prototype.symbols;G("flags","column",{pointRange:0,allowOverlapX:!1,
shape:"flag",stackDistance:12,textAlign:"center",tooltip:{pointFormat:"{point.text}\x3cbr/\x3e"},threshold:null,y:-30,fillColor:"#ffffff",lineWidth:1,states:{hover:{lineColor:"#000000",fillColor:"#ccd6eb"}},style:{fontSize:"11px",fontWeight:"bold"}},{sorted:!1,noSharedTooltip:!0,allowDG:!1,takeOrdinalPosition:!1,trackerGroups:["markerGroup"],forceCrop:!0,init:a.Series.prototype.init,pointAttribs:function(a,l){var e=this.options,k=a&&a.color||this.color,m=e.lineColor,p=a&&a.lineWidth;a=a&&a.fillColor||
e.fillColor;l&&(a=e.states[l].fillColor,m=e.states[l].lineColor,p=e.states[l].lineWidth);return{fill:a||k,stroke:m||k,"stroke-width":p||e.lineWidth||0}},translate:E.translate,getPlotBox:E.getPlotBox,drawPoints:function(){var e=this.points,l=this.chart,r=l.renderer,k,m,p=l.inverted,g=this.options,c=g.y,b,f,h,d,x,J,q=this.yAxis,C={},n=[];for(f=e.length;f--;)h=e[f],J=(p?h.plotY:h.plotX)>this.xAxis.len,k=h.plotX,d=h.stackIndex,b=h.options.shape||g.shape,m=h.plotY,void 0!==m&&(m=h.plotY+c-(void 0!==d&&
d*g.stackDistance)),h.anchorX=d?void 0:h.plotX,x=d?void 0:h.plotY,d=h.graphic,void 0!==m&&0<=k&&!J?(d||(d=h.graphic=r.label("",null,null,b,null,null,g.useHTML).attr(this.pointAttribs(h)).css(H(g.style,h.style)).attr({align:"flag"===b?"left":"center",width:g.width,height:g.height,"text-align":g.textAlign}).addClass("highcharts-point").add(this.markerGroup),h.graphic.div&&(h.graphic.div.point=h),d.shadow(g.shadow),d.isNew=!0),0<k&&(k-=d.strokeWidth()%2),b={y:m,anchorY:x},g.allowOverlapX&&(b.x=k,b.anchorX=
h.anchorX),d.attr({text:h.options.title||g.title||"A"})[d.isNew?"attr":"animate"](b),g.allowOverlapX||(C[h.plotX]?C[h.plotX].size=Math.max(C[h.plotX].size,d.width):C[h.plotX]={align:0,size:d.width,target:k,anchorX:k}),h.tooltipPos=[k,m+q.pos-l.plotTop]):d&&(h.graphic=d.destroy());g.allowOverlapX||(a.objectEach(C,function(a){a.plotX=a.anchorX;n.push(a)}),a.distribute(n,p?q.len:this.xAxis.len,100),A(e,function(a){var b=a.graphic&&C[a.plotX];b&&(a.graphic[a.graphic.isNew?"attr":"animate"]({x:b.pos,anchorX:a.anchorX}),
a.graphic.isNew=!1)}));g.useHTML&&a.wrap(this.markerGroup,"on",function(b){return a.SVGElement.prototype.on.apply(b.apply(this,[].slice.call(arguments,1)),[].slice.call(arguments,1))})},drawTracker:function(){var a=this.points;q.drawTrackerPoint.apply(this);A(a,function(e){var l=e.graphic;l&&D(l.element,"mouseover",function(){0<e.stackIndex&&!e.raised&&(e._y=l.y,l.attr({y:e._y-8}),e.raised=!0);A(a,function(a){a!==e&&a.raised&&a.graphic&&(a.graphic.attr({y:a._y}),a.raised=!1)})})})},animate:w,buildKDTree:w,
setClip:w,invertGroups:w});B.flag=function(a,l,r,k,m){var e=m&&m.anchorX||a;m=m&&m.anchorY||l;return B.circle(e-1,m-1,2,2).concat(["M",e,m,"L",a,l+k,a,l,a+r,l,a+r,l+k,a,l+k,"Z"])};z("circle");z("square");y===u&&A(["flag","circlepin","squarepin"],function(a){u.prototype.symbols[a]=B[a]})})(K,U);(function(a){function E(a,c,b){this.init(a,c,b)}var z=a.addEvent,D=a.Axis,A=a.correctFloat,H=a.defaultOptions,w=a.defined,y=a.destroyObjectProperties,G=a.each,q=a.fireEvent,u=a.hasTouch,B=a.isTouchDevice,e=
a.merge,l=a.pick,r=a.removeEvent,k=a.wrap,m,p={height:B?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:a.svg&&!B,margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",buttonBackgroundColor:"#e6e6e6",buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",trackBackgroundColor:"#f2f2f2",trackBorderColor:"#f2f2f2",trackBorderWidth:1};H.scrollbar=e(!0,p,H.scrollbar);a.swapXY=m=function(a,c){var b=a.length,
g;if(c)for(c=0;c<b;c+=3)g=a[c+1],a[c+1]=a[c+2],a[c+2]=g;return a};E.prototype={init:function(a,c,b){this.scrollbarButtons=[];this.renderer=a;this.userOptions=c;this.options=e(p,c);this.chart=b;this.size=l(this.options.size,this.options.height);c.enabled&&(this.render(),this.initEvents(),this.addEvents())},render:function(){var a=this.renderer,c=this.options,b=this.size,f;this.group=f=a.g("scrollbar").attr({zIndex:c.zIndex,translateY:-99999}).add();this.track=a.rect().addClass("highcharts-scrollbar-track").attr({x:0,
r:c.trackBorderRadius||0,height:b,width:b}).add(f);this.track.attr({fill:c.trackBackgroundColor,stroke:c.trackBorderColor,"stroke-width":c.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=a.g().add(f);this.scrollbar=a.rect().addClass("highcharts-scrollbar-thumb").attr({height:b,width:b,r:c.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=a.path(m(["M",-3,b/4,"L",-3,2*b/3,"M",0,b/4,"L",0,2*b/3,"M",
3,b/4,"L",3,2*b/3],c.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);this.scrollbar.attr({fill:c.barBackgroundColor,stroke:c.barBorderColor,"stroke-width":c.barBorderWidth});this.scrollbarRifles.attr({stroke:c.rifleColor,"stroke-width":1});this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)},position:function(a,c,b,f){var g=
this.options.vertical,d=0,e=this.rendered?"animate":"attr";this.x=a;this.y=c+this.trackBorderWidth;this.width=b;this.xOffset=this.height=f;this.yOffset=d;g?(this.width=this.yOffset=b=d=this.size,this.xOffset=c=0,this.barWidth=f-2*b,this.x=a+=this.options.margin):(this.height=this.xOffset=f=c=this.size,this.barWidth=b-2*f,this.y+=this.options.margin);this.group[e]({translateX:a,translateY:this.y});this.track[e]({width:b,height:f});this.scrollbarButtons[1][e]({translateX:g?0:b-c,translateY:g?f-d:0})},
drawScrollbarButton:function(a){var g=this.renderer,b=this.scrollbarButtons,f=this.options,h=this.size,d;d=g.g().add(this.group);b.push(d);d=g.rect().addClass("highcharts-scrollbar-button").add(d);d.attr({stroke:f.buttonBorderColor,"stroke-width":f.buttonBorderWidth,fill:f.buttonBackgroundColor});d.attr(d.crisp({x:-.5,y:-.5,width:h+1,height:h+1,r:f.buttonBorderRadius},d.strokeWidth()));d=g.path(m(["M",h/2+(a?-1:1),h/2-3,"L",h/2+(a?-1:1),h/2+3,"L",h/2+(a?2:-2),h/2],f.vertical)).addClass("highcharts-scrollbar-arrow").add(b[a]);
d.attr({fill:f.buttonArrowColor})},setRange:function(a,c){var b=this.options,g=b.vertical,h=b.minWidth,d=this.barWidth,e,k,m=this.rendered&&!this.hasDragged?"animate":"attr";w(d)&&(a=Math.max(a,0),e=Math.ceil(d*a),this.calculatedWidth=k=A(d*Math.min(c,1)-e),k<h&&(e=(d-h+k)*a,k=h),h=Math.floor(e+this.xOffset+this.yOffset),d=k/2-.5,this.from=a,this.to=c,g?(this.scrollbarGroup[m]({translateY:h}),this.scrollbar[m]({height:k}),this.scrollbarRifles[m]({translateY:d}),this.scrollbarTop=h,this.scrollbarLeft=
0):(this.scrollbarGroup[m]({translateX:h}),this.scrollbar[m]({width:k}),this.scrollbarRifles[m]({translateX:d}),this.scrollbarLeft=h,this.scrollbarTop=0),12>=k?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0),!1===b.showFull&&(0>=a&&1<=c?this.group.hide():this.group.show()),this.rendered=!0)},initEvents:function(){var a=this;a.mouseMoveHandler=function(c){var b=a.chart.pointer.normalize(c),f=a.options.vertical?"chartY":"chartX",h=a.initPositions;!a.grabbedCenter||c.touches&&0===c.touches[0][f]||
(b=a.cursorToScrollbarPosition(b)[f],f=a[f],f=b-f,a.hasDragged=!0,a.updatePosition(h[0]+f,h[1]+f),a.hasDragged&&q(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMType:c.type,DOMEvent:c}))};a.mouseUpHandler=function(c){a.hasDragged&&q(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMType:c.type,DOMEvent:c});a.grabbedCenter=a.hasDragged=a.chartX=a.chartY=null};a.mouseDownHandler=function(c){c=a.chart.pointer.normalize(c);c=a.cursorToScrollbarPosition(c);a.chartX=c.chartX;a.chartY=c.chartY;
a.initPositions=[a.from,a.to];a.grabbedCenter=!0};a.buttonToMinClick=function(c){var b=A(a.to-a.from)*a.options.step;a.updatePosition(A(a.from-b),A(a.to-b));q(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:c})};a.buttonToMaxClick=function(c){var b=(a.to-a.from)*a.options.step;a.updatePosition(a.from+b,a.to+b);q(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:c})};a.trackClick=function(c){var b=a.chart.pointer.normalize(c),f=a.to-a.from,h=a.y+a.scrollbarTop,d=a.x+a.scrollbarLeft;
a.options.vertical&&b.chartY>h||!a.options.vertical&&b.chartX>d?a.updatePosition(a.from+f,a.to+f):a.updatePosition(a.from-f,a.to-f);q(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:c})}},cursorToScrollbarPosition:function(a){var c=this.options,c=c.minWidth>this.calculatedWidth?c.minWidth:0;return{chartX:(a.chartX-this.x-this.xOffset)/(this.barWidth-c),chartY:(a.chartY-this.y-this.yOffset)/(this.barWidth-c)}},updatePosition:function(a,c){1<c&&(a=A(1-A(c-a)),c=1);0>a&&(c=A(c-a),a=0);
this.from=a;this.to=c},update:function(a){this.destroy();this.init(this.chart.renderer,e(!0,this.options,a),this.chart)},addEvents:function(){var a=this.options.inverted?[1,0]:[0,1],c=this.scrollbarButtons,b=this.scrollbarGroup.element,f=this.mouseDownHandler,h=this.mouseMoveHandler,d=this.mouseUpHandler,a=[[c[a[0]].element,"click",this.buttonToMinClick],[c[a[1]].element,"click",this.buttonToMaxClick],[this.track.element,"click",this.trackClick],[b,"mousedown",f],[b.ownerDocument,"mousemove",h],[b.ownerDocument,
"mouseup",d]];u&&a.push([b,"touchstart",f],[b.ownerDocument,"touchmove",h],[b.ownerDocument,"touchend",d]);G(a,function(a){z.apply(null,a)});this._events=a},removeEvents:function(){G(this._events,function(a){r.apply(null,a)});this._events.length=0},destroy:function(){var a=this.chart.scroller;this.removeEvents();G(["track","scrollbarRifles","scrollbar","scrollbarGroup","group"],function(a){this[a]&&this[a].destroy&&(this[a]=this[a].destroy())},this);a&&this===a.scrollbar&&(a.scrollbar=null,y(a.scrollbarButtons))}};
k(D.prototype,"init",function(a){var c=this;a.apply(c,Array.prototype.slice.call(arguments,1));c.options.scrollbar&&c.options.scrollbar.enabled&&(c.options.scrollbar.vertical=!c.horiz,c.options.startOnTick=c.options.endOnTick=!1,c.scrollbar=new E(c.chart.renderer,c.options.scrollbar,c.chart),z(c.scrollbar,"changed",function(a){var b=Math.min(l(c.options.min,c.min),c.min,c.dataMin),h=Math.max(l(c.options.max,c.max),c.max,c.dataMax)-b,d;c.horiz&&!c.reversed||!c.horiz&&c.reversed?(d=b+h*this.to,b+=h*
this.from):(d=b+h*(1-this.from),b+=h*(1-this.to));c.setExtremes(b,d,!0,!1,a)}))});k(D.prototype,"render",function(a){var c=Math.min(l(this.options.min,this.min),this.min,l(this.dataMin,this.min)),b=Math.max(l(this.options.max,this.max),this.max,l(this.dataMax,this.max)),f=this.scrollbar,h=this.titleOffset||0;a.apply(this,Array.prototype.slice.call(arguments,1));if(f){this.horiz?(f.position(this.left,this.top+this.height+2+this.chart.scrollbarsOffsets[1]+(this.opposite?0:h+this.axisTitleMargin+this.offset),
this.width,this.height),h=1):(f.position(this.left+this.width+2+this.chart.scrollbarsOffsets[0]+(this.opposite?h+this.axisTitleMargin+this.offset:0),this.top,this.width,this.height),h=0);if(!this.opposite&&!this.horiz||this.opposite&&this.horiz)this.chart.scrollbarsOffsets[h]+=this.scrollbar.size+this.scrollbar.options.margin;isNaN(c)||isNaN(b)||!w(this.min)||!w(this.max)?f.setRange(0,0):(h=(this.min-c)/(b-c),c=(this.max-c)/(b-c),this.horiz&&!this.reversed||!this.horiz&&this.reversed?f.setRange(h,
c):f.setRange(1-c,1-h))}});k(D.prototype,"getOffset",function(a){var c=this.horiz?2:1,b=this.scrollbar;a.apply(this,Array.prototype.slice.call(arguments,1));b&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[c]+=b.size+b.options.margin)});k(D.prototype,"destroy",function(a){this.scrollbar&&(this.scrollbar=this.scrollbar.destroy());a.apply(this,Array.prototype.slice.call(arguments,1))});a.Scrollbar=E})(K);(function(a){function E(a){this.init(a)}var z=a.addEvent,D=a.Axis,A=a.Chart,H=a.color,
w=a.defaultOptions,y=a.defined,G=a.destroyObjectProperties,q=a.each,u=a.erase,B=a.error,e=a.extend,l=a.grep,r=a.hasTouch,k=a.isArray,m=a.isNumber,p=a.isObject,g=a.isTouchDevice,c=a.merge,b=a.pick,f=a.removeEvent,h=a.Scrollbar,d=a.Series,x=a.seriesTypes,J=a.wrap,M=[].concat(a.defaultDataGroupingUnits),C=function(a){var b=l(arguments,m);if(b.length)return Math[a].apply(0,b)};M[4]=["day",[1,2,3,4]];M[5]=["week",[1,2,3]];x=void 0===x.areaspline?"line":"areaspline";e(w,{navigator:{height:40,margin:25,
maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:"#f2f2f2",borderColor:"#999999"},maskFill:H("#6685c2").setOpacity(.3).get(),outlineColor:"#cccccc",outlineWidth:1,series:{type:x,fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:M},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,
marker:{enabled:!1},pointRange:0,threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",style:{color:"#999999"},x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});a.Renderer.prototype.symbols["navigator-handle"]=
function(a,b,t,f,d){a=d.width/2;b=Math.round(a/3)+.5;d=d.height;return["M",-a-1,.5,"L",a,.5,"L",a,d+.5,"L",-a-1,d+.5,"L",-a-1,.5,"M",-b,4,"L",-b,d-3,"M",b-1,4,"L",b-1,d-3]};E.prototype={drawHandle:function(a,b,t,d){var n=this.navigatorOptions.handles.height;this.handles[b][d](t?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+parseInt(a,10)+.5-n)}:{translateX:Math.round(this.left+parseInt(a,10)),translateY:Math.round(this.top+this.height/2-n/2-1)})},drawOutline:function(a,
b,t,d){var n=this.navigatorOptions.maskInside,v=this.outline.strokeWidth(),f=v/2,v=v%2/2,c=this.outlineHeight,h=this.scrollbarHeight,e=this.size,k=this.left-h,m=this.top;t?(k-=f,t=m+b+v,b=m+a+v,a=["M",k+c,m-h-v,"L",k+c,t,"L",k,t,"L",k,b,"L",k+c,b,"L",k+c,m+e+h].concat(n?["M",k+c,t-f,"L",k+c,b+f]:[])):(a+=k+h-v,b+=k+h-v,m+=f,a=["M",k,m,"L",a,m,"L",a,m+c,"L",b,m+c,"L",b,m,"L",k+e+2*h,m].concat(n?["M",a-f,m,"L",b+f,m]:[]));this.outline[d]({d:a})},drawMasks:function(a,b,d,f){var n=this.left,v=this.top,
t=this.height,c,h,e,k;d?(e=[n,n,n],k=[v,v+a,v+b],h=[t,t,t],c=[a,b-a,this.size-b]):(e=[n,n+a,n+b],k=[v,v,v],h=[a,b-a,this.size-b],c=[t,t,t]);q(this.shades,function(a,b){a[f]({x:e[b],y:k[b],width:h[b],height:c[b]})})},renderElements:function(){var a=this,b=a.navigatorOptions,t=b.maskInside,d=a.chart,f=d.inverted,c=d.renderer,h;a.navigatorGroup=h=c.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();var e={cursor:f?"ns-resize":"ew-resize"};q([!t,t,!t],function(n,v){a.shades[v]=c.rect().addClass("highcharts-navigator-mask"+
(1===v?"-inside":"-outside")).attr({fill:n?b.maskFill:"rgba(0,0,0,0)"}).css(1===v&&e).add(h)});a.outline=c.path().addClass("highcharts-navigator-outline").attr({"stroke-width":b.outlineWidth,stroke:b.outlineColor}).add(h);b.handles.enabled&&q([0,1],function(n){b.handles.inverted=d.inverted;a.handles[n]=c.symbol(b.handles.symbols[n],-b.handles.width/2-1,0,b.handles.width,b.handles.height,b.handles);a.handles[n].attr({zIndex:7-n}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+
["left","right"][n]).add(h);var v=b.handles;a.handles[n].attr({fill:v.backgroundColor,stroke:v.borderColor,"stroke-width":v.lineWidth}).css(e)})},update:function(a){q(this.series||[],function(a){a.baseSeries&&delete a.baseSeries.navigatorSeries});this.destroy();c(!0,this.chart.options.navigator,this.options,a);this.init(this.chart)},render:function(n,v,d,c){var f=this.chart,h,t,e=this.scrollbarHeight,k,g=this.xAxis;h=g.fake?f.xAxis[0]:g;var l=this.navigatorEnabled,L,x=this.rendered;t=f.inverted;var p,
r=f.xAxis[0].minRange,q=f.xAxis[0].options.maxRange;if(!this.hasDragged||y(d)){if(!m(n)||!m(v))if(x)d=0,c=b(g.width,h.width);else return;this.left=b(g.left,f.plotLeft+e+(t?f.plotWidth:0));this.size=L=k=b(g.len,(t?f.plotHeight:f.plotWidth)-2*e);f=t?e:k+2*e;d=b(d,g.toPixels(n,!0));c=b(c,g.toPixels(v,!0));m(d)&&Infinity!==Math.abs(d)||(d=0,c=f);n=g.toValue(d,!0);v=g.toValue(c,!0);p=Math.abs(a.correctFloat(v-n));p<r?this.grabbedLeft?d=g.toPixels(v-r,!0):this.grabbedRight&&(c=g.toPixels(n+r,!0)):y(q)&&
p>q&&(this.grabbedLeft?d=g.toPixels(v-q,!0):this.grabbedRight&&(c=g.toPixels(n+q,!0)));this.zoomedMax=Math.min(Math.max(d,c,0),L);this.zoomedMin=Math.min(Math.max(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(d,c),0),L);this.range=this.zoomedMax-this.zoomedMin;L=Math.round(this.zoomedMax);d=Math.round(this.zoomedMin);l&&(this.navigatorGroup.attr({visibility:"visible"}),x=x&&!this.hasDragged?"animate":"attr",this.drawMasks(d,L,t,x),this.drawOutline(d,L,t,x),this.navigatorOptions.handles.enabled&&
(this.drawHandle(d,0,t,x),this.drawHandle(L,1,t,x)));this.scrollbar&&(t?(t=this.top-e,h=this.left-e+(l||!h.opposite?0:(h.titleOffset||0)+h.axisTitleMargin),e=k+2*e):(t=this.top+(l?this.height:-e),h=this.left-e),this.scrollbar.position(h,t,f,e),this.scrollbar.setRange(this.zoomedMin/k,this.zoomedMax/k));this.rendered=!0}},addMouseEvents:function(){var a=this,b=a.chart,d=b.container,f=[],c,h;a.mouseMoveHandler=c=function(b){a.onMouseMove(b)};a.mouseUpHandler=h=function(b){a.onMouseUp(b)};f=a.getPartsEvents("mousedown");
f.push(z(d,"mousemove",c),z(d.ownerDocument,"mouseup",h));r&&(f.push(z(d,"touchmove",c),z(d.ownerDocument,"touchend",h)),f.concat(a.getPartsEvents("touchstart")));a.eventsToUnbind=f;a.series&&a.series[0]&&f.push(z(a.series[0].xAxis,"foundExtremes",function(){b.navigator.modifyNavigatorAxisExtremes()}))},getPartsEvents:function(a){var b=this,n=[];q(["shades","handles"],function(d){q(b[d],function(v,f){n.push(z(v.element,a,function(a){b[d+"Mousedown"](a,f)}))})});return n},shadesMousedown:function(a,
b){a=this.chart.pointer.normalize(a);var n=this.chart,d=this.xAxis,f=this.zoomedMin,v=this.left,c=this.size,h=this.range,e=a.chartX,k,m;n.inverted&&(e=a.chartY,v=this.top);1===b?(this.grabbedCenter=e,this.fixedWidth=h,this.dragOffset=e-f):(a=e-v-h/2,0===b?a=Math.max(0,a):2===b&&a+h>=c&&(a=c-h,d.reversed?(a-=h,m=this.getUnionExtremes().dataMin):k=this.getUnionExtremes().dataMax),a!==f&&(this.fixedWidth=h,b=d.toFixedRange(a,a+h,m,k),y(b.min)&&n.xAxis[0].setExtremes(Math.min(b.min,b.max),Math.max(b.min,
b.max),!0,null,{trigger:"navigator"})))},handlesMousedown:function(a,b){this.chart.pointer.normalize(a);a=this.chart;var n=a.xAxis[0],d=a.inverted&&!n.reversed||!a.inverted&&n.reversed;0===b?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=d?n.min:n.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=d?n.max:n.min);a.fixedRange=null},onMouseMove:function(a){var b=this,n=b.chart,d=b.left,f=b.navigatorSize,c=b.range,h=b.dragOffset,e=n.inverted;a.touches&&
0===a.touches[0].pageX||(a=n.pointer.normalize(a),n=a.chartX,e&&(d=b.top,n=a.chartY),b.grabbedLeft?(b.hasDragged=!0,b.render(0,0,n-d,b.otherHandlePos)):b.grabbedRight?(b.hasDragged=!0,b.render(0,0,b.otherHandlePos,n-d)):b.grabbedCenter&&(b.hasDragged=!0,n<h?n=h:n>f+h-c&&(n=f+h-c),b.render(0,0,n-h,n-h+c)),b.hasDragged&&b.scrollbar&&b.scrollbar.options.liveRedraw&&(a.DOMType=a.type,setTimeout(function(){b.onMouseUp(a)},0)))},onMouseUp:function(a){var b=this.chart,n=this.xAxis,d=n&&n.reversed,f=this.scrollbar,
h,c,e=a.DOMEvent||a;(!this.hasDragged||f&&f.hasDragged)&&"scrollbar"!==a.trigger||(f=this.getUnionExtremes(),this.zoomedMin===this.otherHandlePos?h=this.fixedExtreme:this.zoomedMax===this.otherHandlePos&&(c=this.fixedExtreme),this.zoomedMax===this.size&&(c=d?f.dataMin:f.dataMax),0===this.zoomedMin&&(h=d?f.dataMax:f.dataMin),n=n.toFixedRange(this.zoomedMin,this.zoomedMax,h,c),y(n.min)&&b.xAxis[0].setExtremes(Math.min(n.min,n.max),Math.max(n.min,n.max),!0,this.hasDragged?!1:null,{trigger:"navigator",
triggerOp:"navigator-drag",DOMEvent:e}));"mousemove"!==a.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null)},removeEvents:function(){this.eventsToUnbind&&(q(this.eventsToUnbind,function(a){a()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()},removeBaseSeriesEvents:function(){var a=this.baseSeries||[];this.navigatorEnabled&&a[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&q(a,function(a){f(a,
"updatedData",this.updatedDataHandler)},this),a[0].xAxis&&f(a[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))},init:function(a){var d=a.options,f=d.navigator,n=f.enabled,e=d.scrollbar,k=e.enabled,d=n?f.height:0,m=k?e.height:0;this.handles=[];this.shades=[];this.chart=a;this.setBaseSeries();this.height=d;this.scrollbarHeight=m;this.scrollbarEnabled=k;this.navigatorEnabled=n;this.navigatorOptions=f;this.scrollbarOptions=e;this.outlineHeight=d+m;this.opposite=b(f.opposite,!n&&a.inverted);var g=
this,e=g.baseSeries,k=a.xAxis.length,l=a.yAxis.length,x=e&&e[0]&&e[0].xAxis||a.xAxis[0]||{options:{}};a.extraMargin={type:g.opposite?"plotTop":"marginBottom",value:(n||!a.inverted?g.outlineHeight:0)+f.margin};a.inverted&&(a.extraMargin.type=g.opposite?"marginRight":"plotLeft");a.isDirtyBox=!0;g.navigatorEnabled?(g.xAxis=new D(a,c({breaks:x.options.breaks,ordinal:x.options.ordinal},f.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:k,offset:0,keepOrdinalPadding:!0,
startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},a.inverted?{offsets:[m,0,-m,0],width:d}:{offsets:[0,-m,0,m],height:d})),g.yAxis=new D(a,c(f.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:l,zoomEnabled:!1},a.inverted?{width:d}:{height:d})),e||f.series.data?g.updateNavigatorSeries(!1):0===a.series.length&&(g.unbindRedraw=z(a,"beforeRedraw",function(){0<a.series.length&&!g.series&&(g.setBaseSeries(),g.unbindRedraw())})),g.renderElements(),g.addMouseEvents()):g.xAxis=
{translate:function(b,d){var f=a.xAxis[0],h=f.getExtremes(),c=f.len-2*m,n=C("min",f.options.min,h.dataMin),f=C("max",f.options.max,h.dataMax)-n;return d?b*f/c+n:c*(b-n)/f},toPixels:function(a){return this.translate(a)},toValue:function(a){return this.translate(a,!0)},toFixedRange:D.prototype.toFixedRange,fake:!0};a.options.scrollbar.enabled&&(a.scrollbar=g.scrollbar=new h(a.renderer,c(a.options.scrollbar,{margin:g.navigatorEnabled?0:10,vertical:a.inverted}),a),z(g.scrollbar,"changed",function(b){var d=
g.size,f=d*this.to,d=d*this.from;g.hasDragged=g.scrollbar.hasDragged;g.render(0,0,d,f);(a.options.scrollbar.liveRedraw||"mousemove"!==b.DOMType&&"touchmove"!==b.DOMType)&&setTimeout(function(){g.onMouseUp(b)})}));g.addBaseSeriesEvents();g.addChartEvents()},getUnionExtremes:function(a){var d=this.chart.xAxis[0],f=this.xAxis,h=f.options,c=d.options,n;a&&null===d.dataMin||(n={dataMin:b(h&&h.min,C("min",c.min,d.dataMin,f.dataMin,f.min)),dataMax:b(h&&h.max,C("max",c.max,d.dataMax,f.dataMax,f.max))});return n},
setBaseSeries:function(a,b){var d=this.chart,f=this.baseSeries=[];a=a||d.options&&d.options.navigator.baseSeries||0;q(d.series||[],function(b,d){b.options.isInternal||!b.options.showInNavigator&&(d!==a&&b.options.id!==a||!1===b.options.showInNavigator)||f.push(b)});this.xAxis&&!this.xAxis.fake&&this.updateNavigatorSeries(!0,b)},updateNavigatorSeries:function(b,d){var h=this,n=h.chart,v=h.baseSeries,m,g,l=h.navigatorOptions.series,x,p={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,
xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:!1,isInternal:!0,visible:!0},r=h.series=a.grep(h.series||[],function(b){var d=b.baseSeries;return 0>a.inArray(d,v)?(d&&(f(d,"updatedData",h.updatedDataHandler),delete d.navigatorSeries),b.destroy(),!1):!0});v&&v.length&&q(v,function(a){var b=a.navigatorSeries,f=e({color:a.color},k(l)?w.navigator.series:l);b&&!1===h.navigatorOptions.adaptToUpdatedData||(p.name="Navigator "+v.length,m=a.options||{},x=m.navigatorOptions||{},g=
c(m,p,f,x),f=x.data||f.data,h.hasNavigatorData=h.hasNavigatorData||!!f,g.data=f||m.data&&m.data.slice(0),b&&b.options?b.update(g,d):(a.navigatorSeries=n.initSeries(g),a.navigatorSeries.baseSeries=a,r.push(a.navigatorSeries)))});if(l.data&&(!v||!v.length)||k(l))h.hasNavigatorData=!1,l=a.splat(l),q(l,function(a,b){p.name="Navigator "+(r.length+1);g=c(w.navigator.series,{color:n.series[b]&&!n.series[b].options.isInternal&&n.series[b].color||n.options.colors[b]||n.options.colors[0]},p,a);g.data=a.data;
g.data&&(h.hasNavigatorData=!0,r.push(n.initSeries(g)))});b&&this.addBaseSeriesEvents()},addBaseSeriesEvents:function(){var a=this,b=a.baseSeries||[];b[0]&&b[0].xAxis&&z(b[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);q(b,function(b){z(b,"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,!1)});z(b,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&b.xAxis&&z(b,"updatedData",this.updatedDataHandler);
z(b,"remove",function(){this.navigatorSeries&&(u(a.series,this.navigatorSeries),y(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)},modifyNavigatorAxisExtremes:function(){var a=this.xAxis,b;a.getExtremes&&(!(b=this.getUnionExtremes(!0))||b.dataMin===a.min&&b.dataMax===a.max||(a.min=b.dataMin,a.max=b.dataMax))},modifyBaseAxisExtremes:function(){var a=this.chart.navigator,d=this.getExtremes(),f=d.dataMin,h=d.dataMax,d=d.max-d.min,c=a.stickToMin,e=
a.stickToMax,k=b(this.options.overscroll,0),g,l,x=a.series&&a.series[0],p=!!this.setExtremes;this.eventArgs&&"rangeSelectorButton"===this.eventArgs.trigger||(c&&(l=f,g=l+d),e&&(g=h+k,c||(l=Math.max(g-d,x&&x.xData?x.xData[0]:-Number.MAX_VALUE))),p&&(c||e)&&m(l)&&(this.min=this.userMin=l,this.max=this.userMax=g));a.stickToMin=a.stickToMax=null},updatedDataHandler:function(){var a=this.chart.navigator,b=this.navigatorSeries;a.stickToMax=a.xAxis.reversed?0===Math.round(a.zoomedMin):Math.round(a.zoomedMax)>=
Math.round(a.size);a.stickToMin=m(this.xAxis.min)&&this.xAxis.min<=this.xData[0]&&(!this.chart.fixedRange||!a.stickToMax);b&&!a.hasNavigatorData&&(b.options.pointStart=this.xData[0],b.setData(this.options.data,!1,null,!1))},addChartEvents:function(){z(this.chart,"redraw",function(){var a=this.navigator,b=a&&(a.baseSeries&&a.baseSeries[0]&&a.baseSeries[0].xAxis||a.scrollbar&&this.xAxis[0]);b&&a.render(b.min,b.max)})},destroy:function(){this.removeEvents();this.xAxis&&(u(this.chart.xAxis,this.xAxis),
u(this.chart.axes,this.xAxis));this.yAxis&&(u(this.chart.yAxis,this.yAxis),u(this.chart.axes,this.yAxis));q(this.series||[],function(a){a.destroy&&a.destroy()});q("series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" "),function(a){this[a]&&this[a].destroy&&this[a].destroy();this[a]=null},this);q([this.handles],function(a){G(a)},this)}};a.Navigator=E;J(D.prototype,"zoom",function(a,b,d){var f=this.chart,h=f.options,c=h.chart.zoomType,
e=h.chart.pinchType,n=h.navigator,h=h.rangeSelector,k;this.isXAxis&&(n&&n.enabled||h&&h.enabled)&&(!g&&"x"===c||g&&"x"===e?f.resetZoomButton="blocked":"y"===c?k=!1:(!g&&"xy"===c||g&&"xy"===e)&&this.options.range&&(f=this.previousZoom,y(b)?this.previousZoom=[this.min,this.max]:f&&(b=f[0],d=f[1],delete this.previousZoom)));return void 0!==k?k:a.call(this,b,d)});z(A,"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=this.navigator=new E(this)});z(A,
"afterSetChartSize",function(){var a=this.legend,d=this.navigator,f,h,c,e;d&&(h=a&&a.options,c=d.xAxis,e=d.yAxis,f=d.scrollbarHeight,this.inverted?(d.left=d.opposite?this.chartWidth-f-d.height:this.spacing[3]+f,d.top=this.plotTop+f):(d.left=this.plotLeft+f,d.top=d.navigatorOptions.top||this.chartHeight-d.height-f-this.spacing[2]-(this.rangeSelector&&this.extraBottomMargin?this.rangeSelector.getHeight():0)-(h&&"bottom"===h.verticalAlign&&h.enabled&&!h.floating?a.legendHeight+b(h.margin,10):0)),c&&
e&&(this.inverted?c.options.left=e.options.left=d.left:c.options.top=e.options.top=d.top,c.setAxisSize(),e.setAxisSize()))});J(d.prototype,"addPoint",function(a,b,d,f,h){var c=this.options.turboThreshold;c&&this.xData.length>c&&p(b,!0)&&this.chart.navigator&&B(20,!0);a.call(this,b,d,f,h)});z(A,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,!1)});z(d,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)});
A.prototype.callbacks.push(function(a){var b=a.navigator;b&&a.xAxis[0]&&(a=a.xAxis[0].getExtremes(),b.render(a.min,a.max))})})(K);(function(a){function E(a){this.init(a)}var z=a.addEvent,D=a.Axis,A=a.Chart,H=a.css,w=a.createElement,y=a.defaultOptions,G=a.defined,q=a.destroyObjectProperties,u=a.discardElement,B=a.each,e=a.extend,l=a.fireEvent,r=a.isNumber,k=a.merge,m=a.pick,p=a.pInt,g=a.splat,c=a.wrap;e(y,{rangeSelector:{verticalAlign:"top",buttonTheme:{"stroke-width":0,width:28,height:18,padding:2,
zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0},labelStyle:{color:"#666666"}}});y.lang=k(y.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});E.prototype={clickButton:function(a,f){var b=this,d=b.chart,c=b.buttonOptions[a],e=d.xAxis[0],k=d.scroller&&d.scroller.getUnionExtremes()||e||{},l=k.dataMin,n=k.dataMax,v,t=e&&Math.round(Math.min(e.max,m(n,e.max))),p=c.type,q,k=c._range,w,F,y,u=c.dataGrouping;
if(null!==l&&null!==n){d.fixedRange=k;u&&(this.forcedDataGrouping=!0,D.prototype.setDataGrouping.call(e||{chart:this.chart},u,!1));if("month"===p||"year"===p)e?(p={range:c,max:t,chart:d,dataMin:l,dataMax:n},v=e.minFromRange.call(p),r(p.newMax)&&(t=p.newMax)):k=c;else if(k)v=Math.max(t-k,l),t=Math.min(v+k,n);else if("ytd"===p)if(e)void 0===n&&(l=Number.MAX_VALUE,n=Number.MIN_VALUE,B(d.series,function(a){a=a.xData;l=Math.min(a[0],l);n=Math.max(a[a.length-1],n)}),f=!1),t=b.getYTDExtremes(n,l,d.time.useUTC),
v=w=t.min,t=t.max;else{z(d,"beforeRender",function(){b.clickButton(a)});return}else"all"===p&&e&&(v=l,t=n);v+=c._offsetMin;t+=c._offsetMax;b.setSelected(a);e?e.setExtremes(v,t,m(f,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:c}):(q=g(d.options.xAxis)[0],y=q.range,q.range=k,F=q.min,q.min=w,z(d,"load",function(){q.range=y;q.min=F}))}},setSelected:function(a){this.selected=this.options.selected=a},defaultButtons:[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",
count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},{type:"all",text:"All"}],init:function(a){var b=this,h=a.options.rangeSelector,d=h.buttons||[].concat(b.defaultButtons),c=h.selected,e=function(){var a=b.minInput,d=b.maxInput;a&&a.blur&&l(a,"blur");d&&d.blur&&l(d,"blur")};b.chart=a;b.options=h;b.buttons=[];a.extraTopMargin=h.height;b.buttonOptions=d;this.unMouseDown=z(a.container,"mousedown",e);this.unResize=z(a,"resize",e);B(d,b.computeButtonRange);void 0!==c&&d[c]&&this.clickButton(c,
!1);z(a,"load",function(){a.xAxis&&a.xAxis[0]&&z(a.xAxis[0],"setExtremes",function(d){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==d.trigger&&"updatedData"!==d.trigger&&b.forcedDataGrouping&&this.setDataGrouping(!1,!1)})})},updateButtonStates:function(){var a=this.chart,f=a.xAxis[0],c=Math.round(f.max-f.min),d=!f.hasVisibleSeries,e=a.scroller&&a.scroller.getUnionExtremes()||f,k=e.dataMin,g=e.dataMax,a=this.getYTDExtremes(g,k,a.time.useUTC),m=a.min,n=a.max,l=this.selected,t=r(l),p=this.options.allButtonsEnabled,
q=this.buttons;B(this.buttonOptions,function(a,b){var h=a._range,e=a.type,v=a.count||1,x=q[b],r=0;a=a._offsetMax-a._offsetMin;b=b===l;var F=h>g-k,w=h<f.minRange,I=!1,y=!1,h=h===c;("month"===e||"year"===e)&&c+36E5>=864E5*{month:28,year:365}[e]*v-a&&c-36E5<=864E5*{month:31,year:366}[e]*v+a?h=!0:"ytd"===e?(h=n-m+a===c,I=!b):"all"===e&&(h=f.max-f.min>=g-k,y=!b&&t&&h);e=!p&&(F||w||y||d);v=b&&h||h&&!t&&!I;e?r=3:v&&(t=!0,r=2);x.state!==r&&x.setState(r)})},computeButtonRange:function(a){var b=a.type,h=a.count||
1,d={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(d[b])a._range=d[b]*h;else if("month"===b||"year"===b)a._range=864E5*{month:30,year:365}[b]*h;a._offsetMin=m(a.offsetMin,0);a._offsetMax=m(a.offsetMax,0);a._range+=a._offsetMax-a._offsetMin},setInputValue:function(a,f){var b=this.chart.options.rangeSelector,d=this.chart.time,c=this[a+"Input"];G(f)&&(c.previousValue=c.HCTime,c.HCTime=f);c.value=d.dateFormat(b.inputEditDateFormat||"%Y-%m-%d",c.HCTime);this[a+"DateBox"].attr({text:d.dateFormat(b.inputDateFormat||
"%b %e, %Y",c.HCTime)})},showInput:function(a){var b=this.inputGroup,c=this[a+"DateBox"];H(this[a+"Input"],{left:b.translateX+c.x+"px",top:b.translateY+"px",width:c.width-2+"px",height:c.height-2+"px",border:"2px solid silver"})},hideInput:function(a){H(this[a+"Input"],{border:0,width:"1px",height:"1px"});this.setInputValue(a)},drawInput:function(a){function b(){var a=v.value,b=(l.inputDateParser||Date.parse)(a),f=d.xAxis[0],h=d.scroller&&d.scroller.xAxis?d.scroller.xAxis:f,e=h.dataMin,h=h.dataMax;
b!==v.previousValue&&(v.previousValue=b,r(b)||(b=a.split("-"),b=Date.UTC(p(b[0]),p(b[1])-1,p(b[2]))),r(b)&&(d.time.useUTC||(b+=6E4*(new Date).getTimezoneOffset()),n?b>c.maxInput.HCTime?b=void 0:b<e&&(b=e):b<c.minInput.HCTime?b=void 0:b>h&&(b=h),void 0!==b&&f.setExtremes(n?b:f.min,n?f.max:b,void 0,void 0,{trigger:"rangeSelectorInput"})))}var c=this,d=c.chart,g=d.renderer.style||{},m=d.renderer,l=d.options.rangeSelector,q=c.div,n="min"===a,v,t,u=this.inputGroup;this[a+"Label"]=t=m.label(y.lang[n?"rangeSelectorFrom":
"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(u);u.offset+=t.width+5;this[a+"DateBox"]=m=m.label("",u.offset).addClass("highcharts-range-input").attr({padding:2,width:l.inputBoxWidth||90,height:l.inputBoxHeight||17,stroke:l.inputBoxBorderColor||"#cccccc","stroke-width":1,"text-align":"center"}).on("click",function(){c.showInput(a);c[a+"Input"].focus()}).add(u);u.offset+=m.width+(n?10:0);this[a+"Input"]=v=w("input",{name:a,className:"highcharts-range-selector",
type:"text"},{top:d.plotTop+"px"},q);t.css(k(g,l.labelStyle));m.css(k({color:"#333333"},g,l.inputStyle));H(v,e({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:g.fontSize,fontFamily:g.fontFamily,top:"-9999em"},l.inputStyle));v.onfocus=function(){c.showInput(a)};v.onblur=function(){c.hideInput(a)};v.onchange=b;v.onkeypress=function(a){13===a.keyCode&&b()}},getPosition:function(){var a=this.chart,c=a.options.rangeSelector,a="top"===c.verticalAlign?a.plotTop-
a.axisOffset[0]:0;return{buttonTop:a+c.buttonPosition.y,inputTop:a+c.inputPosition.y-10}},getYTDExtremes:function(a,c,h){var b=this.chart.time,f=new b.Date(a),e=b.get("FullYear",f);h=h?b.Date.UTC(e,0,1):+new b.Date(e,0,1);c=Math.max(c||0,h);f=f.getTime();return{max:Math.min(a||f,f),min:c}},render:function(a,c){var b=this,d=b.chart,f=d.renderer,e=d.container,k=d.options,g=k.exporting&&!1!==k.exporting.enabled&&k.navigation&&k.navigation.buttonOptions,n=y.lang,l=b.div,t=k.rangeSelector,k=t.floating,
p=b.buttons,l=b.inputGroup,r=t.buttonTheme,q=t.buttonPosition,F=t.inputPosition,u=t.inputEnabled,z=r&&r.states,A=d.plotLeft,E,D=b.buttonGroup,G;G=b.rendered;var H=b.options.verticalAlign,R=d.legend,K=R&&R.options,S=q.y,Q=F.y,T=G||!1,P=0,N=0,O;if(!1!==t.enabled){G||(b.group=G=f.g("range-selector-group").attr({zIndex:7}).add(),b.buttonGroup=D=f.g("range-selector-buttons").add(G),b.zoomText=f.text(n.rangeSelectorZoom,m(A+q.x,A),15).css(t.labelStyle).add(D),E=m(A+q.x,A)+b.zoomText.getBBox().width+5,B(b.buttonOptions,
function(a,d){p[d]=f.button(a.text,E,0,function(){var c=a.events&&a.events.click,f;c&&(f=c.call(a));!1!==f&&b.clickButton(d);b.isActive=!0},r,z&&z.hover,z&&z.select,z&&z.disabled).attr({"text-align":"center"}).add(D);E+=p[d].width+m(t.buttonSpacing,5)}),!1!==u&&(b.div=l=w("div",null,{position:"relative",height:0,zIndex:1}),e.parentNode.insertBefore(l,e),b.inputGroup=l=f.g("input-group").add(G),l.offset=0,b.drawInput("min"),b.drawInput("max")));A=d.plotLeft-d.spacing[3];b.updateButtonStates();g&&this.titleCollision(d)&&
"top"===H&&"right"===q.align&&q.y+D.getBBox().height-12<(g.y||0)+g.height&&(P=-40);"left"===q.align?O=q.x-d.spacing[3]:"right"===q.align&&(O=q.x+P-d.spacing[1]);D.align({y:q.y,width:D.getBBox().width,align:q.align,x:O},!0,d.spacingBox);b.group.placed=T;b.buttonGroup.placed=T;!1!==u&&(P=g&&this.titleCollision(d)&&"top"===H&&"right"===F.align&&F.y-l.getBBox().height-12<(g.y||0)+g.height+d.spacing[0]?-40:0,"left"===F.align?O=A:"right"===F.align&&(O=-Math.max(d.axisOffset[1],-P)),l.align({y:F.y,width:l.getBBox().width,
align:F.align,x:F.x+O-2},!0,d.spacingBox),e=l.alignAttr.translateX+l.alignOptions.x-P+l.getBBox().x+2,g=l.alignOptions.width,n=D.alignAttr.translateX+D.getBBox().x,O=D.getBBox().width+20,(F.align===q.align||n+O>e&&e+g>n&&S<Q+l.getBBox().height)&&l.attr({translateX:l.alignAttr.translateX+(d.axisOffset[1]>=-P?0:-P),translateY:l.alignAttr.translateY+D.getBBox().height+10}),b.setInputValue("min",a),b.setInputValue("max",c),b.inputGroup.placed=T);b.group.align({verticalAlign:H},!0,d.spacingBox);a=b.group.getBBox().height+
20;c=b.group.alignAttr.translateY;"bottom"===H&&(R=K&&"bottom"===K.verticalAlign&&K.enabled&&!K.floating?R.legendHeight+m(K.margin,10):0,a=a+R-20,N=c-a-(k?0:t.y)-10);if("top"===H)k&&(N=0),d.titleOffset&&(N=d.titleOffset+d.options.title.margin),N+=d.margin[0]-d.spacing[0]||0;else if("middle"===H)if(Q===S)N=0>Q?c+void 0:c;else if(Q||S)N=0>Q||0>S?N-Math.min(Q,S):c-a+NaN;b.group.translate(t.x,t.y+Math.floor(N));!1!==u&&(b.minInput.style.marginTop=b.group.translateY+"px",b.maxInput.style.marginTop=b.group.translateY+
"px");b.rendered=!0}},getHeight:function(){var a=this.options,c=this.group,e=a.y,d=a.buttonPosition.y,a=a.inputPosition.y,c=c?c.getBBox(!0).height+13+e:0,e=Math.min(a,d);if(0>a&&0>d||0<a&&0<d)c+=Math.abs(e);return c},titleCollision:function(a){return!(a.options.title.text||a.options.subtitle.text)},update:function(a){var b=this.chart;k(!0,b.options.rangeSelector,a);this.destroy();this.init(b);b.rangeSelector.render()},destroy:function(){var b=this,c=b.minInput,e=b.maxInput;b.unMouseDown();b.unResize();
q(b.buttons);c&&(c.onfocus=c.onblur=c.onchange=null);e&&(e.onfocus=e.onblur=e.onchange=null);a.objectEach(b,function(a,c){a&&"chart"!==c&&(a.destroy?a.destroy():a.nodeType&&u(this[c]));a!==E.prototype[c]&&(b[c]=null)},this)}};D.prototype.toFixedRange=function(a,c,e,d){var b=this.chart&&this.chart.fixedRange;a=m(e,this.translate(a,!0,!this.horiz));c=m(d,this.translate(c,!0,!this.horiz));e=b&&(c-a)/b;.7<e&&1.3>e&&(d?a=c-b:c=a+b);r(a)&&r(c)||(a=c=void 0);return{min:a,max:c}};D.prototype.minFromRange=
function(){var a=this.range,c={month:"Month",year:"FullYear"}[a.type],e,d=this.max,k,g,l=function(a,b){var d=new Date(a),e=d["get"+c]();d["set"+c](e+b);e===d["get"+c]()&&d.setDate(0);return d.getTime()-a};r(a)?(e=d-a,g=a):(e=d+l(d,-a.count),this.chart&&(this.chart.fixedRange=d-e));k=m(this.dataMin,Number.MIN_VALUE);r(e)||(e=k);e<=k&&(e=k,void 0===g&&(g=l(e,a.count)),this.newMax=Math.min(e+g,this.dataMax));r(d)||(e=void 0);return e};z(A,"afterGetContainer",function(){this.options.rangeSelector.enabled&&
(this.rangeSelector=new E(this))});c(A.prototype,"render",function(a,c,e){var b=this.axes,f=this.rangeSelector;f&&(B(b,function(a){a.updateNames();a.setScale()}),this.getAxisMargins(),f.render(),b=f.options.verticalAlign,f.options.floating||("bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=!0)));a.call(this,c,e)});z(A,"update",function(a){var b=a.options;a=this.rangeSelector;this.extraTopMargin=this.extraBottomMargin=!1;this.isDirtyBox=!0;a&&(a.render(),b=b.rangeSelector&&
b.rangeSelector.verticalAlign||a.options&&a.options.verticalAlign,a.options.floating||("bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=!0)))});c(A.prototype,"redraw",function(a,c,e){var b=this.rangeSelector;b&&!b.options.floating&&(b.render(),b=b.options.verticalAlign,"bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=!0));a.call(this,c,e)});A.prototype.adjustPlotArea=function(){var a=this.rangeSelector;this.rangeSelector&&(a=a.getHeight(),this.extraTopMargin&&
(this.plotTop+=a),this.extraBottomMargin&&(this.marginBottom+=a))};A.prototype.callbacks.push(function(a){function b(){c=a.xAxis[0].getExtremes();r(c.min)&&d.render(c.min,c.max)}var c,d=a.rangeSelector,e,k;d&&(k=z(a.xAxis[0],"afterSetExtremes",function(a){d.render(a.min,a.max)}),e=z(a,"redraw",b),b());z(a,"destroy",function(){d&&(e(),k())})});a.RangeSelector=E})(K);(function(a){var E=a.addEvent,z=a.arrayMax,D=a.arrayMin,A=a.Axis,H=a.Chart,w=a.defined,y=a.each,G=a.extend,q=a.format,u=a.grep,B=a.inArray,
e=a.isNumber,l=a.isString,r=a.map,k=a.merge,m=a.pick,p=a.Point,g=a.Renderer,c=a.Series,b=a.splat,f=a.SVGRenderer,h=a.VMLRenderer,d=a.wrap,x=c.prototype,J=x.init,K=x.processData,C=p.prototype.tooltipFormatter;a.StockChart=a.stockChart=function(c,d,e){var f=l(c)||c.nodeName,g=arguments[f?1:0],h=g.series,n=a.getOptions(),v,t=m(g.navigator&&g.navigator.enabled,n.navigator.enabled,!0),p=t?{startOnTick:!1,endOnTick:!1}:null,q={marker:{enabled:!1,radius:2}},w={shadow:!1,borderWidth:0};g.xAxis=r(b(g.xAxis||
{}),function(a,b){return k({minPadding:0,maxPadding:0,overscroll:0,ordinal:!0,title:{text:null},labels:{overflow:"justify"},showLastLabel:!0},n.xAxis,n.xAxis&&n.xAxis[b],a,{type:"datetime",categories:null},p)});g.yAxis=r(b(g.yAxis||{}),function(a,b){v=m(a.opposite,!0);return k({labels:{y:-2},opposite:v,showLastLabel:!(!a.categories&&"category"!==a.type),title:{text:null}},n.yAxis,n.yAxis&&n.yAxis[b],a)});g.series=null;g=k({chart:{panning:!0,pinchType:"x"},navigator:{enabled:t},scrollbar:{enabled:m(n.scrollbar.enabled,
!0)},rangeSelector:{enabled:m(n.rangeSelector.enabled,!0)},title:{text:null},tooltip:{split:m(n.tooltip.split,!0),crosshairs:!0},legend:{enabled:!1},plotOptions:{line:q,spline:q,area:q,areaspline:q,arearange:q,areasplinerange:q,column:w,columnrange:w,candlestick:w,ohlc:w}},g,{isStock:!0});g.series=h;return f?new H(c,g,e):new H(g,d)};d(A.prototype,"autoLabelAlign",function(a){var b=this.chart,c=this.options,b=b._labelPanes=b._labelPanes||{},d=this.options.labels;return this.chart.options.isStock&&
"yAxis"===this.coll&&(c=c.top+","+c.height,!b[c]&&d.enabled)?(15===d.x&&(d.x=0),void 0===d.align&&(d.align="right"),b[c]=this,"right"):a.apply(this,[].slice.call(arguments,1))});E(A,"destroy",function(){var a=this.chart,b=this.options&&this.options.top+","+this.options.height;b&&a._labelPanes&&a._labelPanes[b]===this&&delete a._labelPanes[b]});d(A.prototype,"getPlotLinePath",function(b,c,d,f,g,k){var h=this,n=this.isLinked&&!this.series?this.linkedParent.series:this.series,p=h.chart,v=p.renderer,
t=h.left,q=h.top,u,x,z,A,C=[],I=[],D,E;if("xAxis"!==h.coll&&"yAxis"!==h.coll)return b.apply(this,[].slice.call(arguments,1));I=function(a){var b="xAxis"===a?"yAxis":"xAxis";a=h.options[b];return e(a)?[p[b][a]]:l(a)?[p.get(a)]:r(n,function(a){return a[b]})}(h.coll);y(h.isXAxis?p.yAxis:p.xAxis,function(a){if(w(a.options.id)?-1===a.options.id.indexOf("navigator"):1){var b=a.isXAxis?"yAxis":"xAxis",b=w(a.options[b])?p[b][a.options[b]]:p[b][0];h===b&&I.push(a)}});D=I.length?[]:[h.isXAxis?p.yAxis[0]:p.xAxis[0]];
y(I,function(b){-1!==B(b,D)||a.find(D,function(a){return a.pos===b.pos&&a.len&&b.len})||D.push(b)});E=m(k,h.translate(c,null,null,f));e(E)&&(h.horiz?y(D,function(a){var b;x=a.pos;A=x+a.len;u=z=Math.round(E+h.transB);if(u<t||u>t+h.width)g?u=z=Math.min(Math.max(t,u),t+h.width):b=!0;b||C.push("M",u,x,"L",z,A)}):y(D,function(a){var b;u=a.pos;z=u+a.len;x=A=Math.round(q+h.height-E);if(x<q||x>q+h.height)g?x=A=Math.min(Math.max(q,x),h.top+h.height):b=!0;b||C.push("M",u,x,"L",z,A)}));return 0<C.length?v.crispPolyLine(C,
d||1):null});f.prototype.crispPolyLine=function(a,b){var c;for(c=0;c<a.length;c+=6)a[c+1]===a[c+4]&&(a[c+1]=a[c+4]=Math.round(a[c+1])-b%2/2),a[c+2]===a[c+5]&&(a[c+2]=a[c+5]=Math.round(a[c+2])+b%2/2);return a};g===h&&(h.prototype.crispPolyLine=f.prototype.crispPolyLine);d(A.prototype,"hideCrosshair",function(a,b){a.call(this,b);this.crossLabel&&(this.crossLabel=this.crossLabel.hide())});E(A,"afterDrawCrosshair",function(a){var b,c;if(w(this.crosshair.label)&&this.crosshair.label.enabled&&this.cross){var d=
this.chart,e=this.options.crosshair.label,f=this.horiz;b=this.opposite;c=this.left;var h=this.top,g=this.crossLabel,k=e.format,l="",n="inside"===this.options.tickPosition,p=!1!==this.crosshair.snap,r=0,u=a.e||this.cross&&this.cross.e,x=a.point;a=f?"center":b?"right"===this.labelAlign?"right":"left":"left"===this.labelAlign?"left":"center";g||(g=this.crossLabel=d.renderer.label(null,null,null,e.shape||"callout").addClass("highcharts-crosshair-label"+(this.series[0]&&" highcharts-color-"+this.series[0].colorIndex)).attr({align:e.align||
a,padding:m(e.padding,8),r:m(e.borderRadius,3),zIndex:2}).add(this.labelGroup),g.attr({fill:e.backgroundColor||this.series[0]&&this.series[0].color||"#666666",stroke:e.borderColor||"","stroke-width":e.borderWidth||0}).css(G({color:"#ffffff",fontWeight:"normal",fontSize:"11px",textAlign:"center"},e.style)));f?(a=p?x.plotX+c:u.chartX,h+=b?0:this.height):(a=b?this.width+c:0,h=p?x.plotY+h:u.chartY);k||e.formatter||(this.isDatetimeAxis&&(l="%b %d, %Y"),k="{value"+(l?":"+l:"")+"}");l=p?x[this.isXAxis?"x":
"y"]:this.toValue(f?u.chartX:u.chartY);g.attr({text:k?q(k,{value:l},d.time):e.formatter.call(this,l),x:a,y:h,visibility:l<this.min||l>this.max?"hidden":"visible"});e=g.getBBox();if(f){if(n&&!b||!n&&b)h=g.y-e.height}else h=g.y-e.height/2;f?(b=c-e.x,c=c+this.width-e.x):(b="left"===this.labelAlign?c:0,c="right"===this.labelAlign?c+this.width:d.chartWidth);g.translateX<b&&(r=b-g.translateX);g.translateX+e.width>=c&&(r=-(g.translateX+e.width-c));g.attr({x:a+r,y:h,anchorX:f?a:this.opposite?0:d.chartWidth,
anchorY:f?this.opposite?d.chartHeight:0:h+e.height/2})}});x.init=function(){J.apply(this,arguments);this.setCompare(this.options.compare)};x.setCompare=function(a){this.modifyValue="value"===a||"percent"===a?function(b,c){var d=this.compareValue;if(void 0!==b&&void 0!==d)return b="value"===a?b-d:b/d*100-(100===this.options.compareBase?0:100),c&&(c.change=b),b}:null;this.userOptions.compare=a;this.chart.hasRendered&&(this.isDirty=!0)};x.processData=function(){var a,b=-1,c,d,f=!0===this.options.compareStart?
0:1,h,g;K.apply(this,arguments);if(this.xAxis&&this.processedYData)for(c=this.processedXData,d=this.processedYData,h=d.length,this.pointArrayMap&&(b=B("close",this.pointArrayMap),-1===b&&(b=B(this.pointValKey||"y",this.pointArrayMap))),a=0;a<h-f;a++)if(g=d[a]&&-1<b?d[a][b]:d[a],e(g)&&c[a+f]>=this.xAxis.min&&0!==g){this.compareValue=g;break}};d(x,"getExtremes",function(a){var b;a.apply(this,[].slice.call(arguments,1));this.modifyValue&&(b=[this.modifyValue(this.dataMin),this.modifyValue(this.dataMax)],
this.dataMin=D(b),this.dataMax=z(b))});A.prototype.setCompare=function(a,b){this.isXAxis||(y(this.series,function(b){b.setCompare(a)}),m(b,!0)&&this.chart.redraw())};p.prototype.tooltipFormatter=function(b){b=b.replace("{point.change}",(0<this.change?"+":"")+a.numberFormat(this.change,m(this.series.tooltipOptions.changeDecimals,2)));return C.apply(this,[b])};d(c.prototype,"render",function(a){var b;this.chart.is3d&&this.chart.is3d()||this.chart.polar||!this.xAxis||this.xAxis.isRadial||(b=this.yAxis.len-
(this.xAxis.axisLine?Math.floor(this.xAxis.axisLine.strokeWidth()/2):0),!this.clipBox&&this.animate?(this.clipBox=k(this.chart.clipBox),this.clipBox.width=this.xAxis.len,this.clipBox.height=b):this.chart[this.sharedClipKey]?this.chart[this.sharedClipKey].attr({width:this.xAxis.len,height:b}):this.clipBox&&(this.clipBox.width=this.xAxis.len,this.clipBox.height=b));a.call(this)});d(H.prototype,"getSelectedPoints",function(a){var b=a.call(this);y(this.series,function(a){a.hasGroupedData&&(b=b.concat(u(a.points||
[],function(a){return a.selected})))});return b});E(H,"update",function(a){a=a.options;"scrollbar"in a&&this.navigator&&(k(!0,this.options.scrollbar,a.scrollbar),this.navigator.update({},!1),delete a.scrollbar)})})(K)});
