/*
 Highcharts JS v6.1.0-modified (2018-05-16)

 (c) 2009-2016 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(w){"object"===typeof module&&module.exports?module.exports=w:w(Highcharts)})(function(w){(function(b){function q(b,a){this.init(b,a)}var v=b.CenteredSeriesMixin,u=b.each,p=b.extend,r=b.merge,g=b.splat;p(q.prototype,{coll:"pane",init:function(b,a){this.chart=a;this.background=[];a.pane.push(this);this.setOptions(b)},setOptions:function(b){this.options=r(this.defaultOptions,this.chart.angular?{background:{}}:void 0,b)},render:function(){var b=this.options,a=this.options.background,c=this.chart.renderer;
this.group||(this.group=c.g("pane-group").attr({zIndex:b.zIndex||0}).add());this.updateCenter();if(a)for(a=g(a),b=Math.max(a.length,this.background.length||0),c=0;c<b;c++)a[c]&&this.axis?this.renderBackground(r(this.defaultBackgroundOptions,a[c]),c):this.background[c]&&(this.background[c]=this.background[c].destroy(),this.background.splice(c,1))},renderBackground:function(b,a){var c="animate";this.background[a]||(this.background[a]=this.chart.renderer.path().add(this.group),c="attr");this.background[a][c]({d:this.axis.getPlotBandPath(b.from,
b.to,b)}).attr({fill:b.backgroundColor,stroke:b.borderColor,"stroke-width":b.borderWidth,"class":"highcharts-pane "+(b.className||"")})},defaultOptions:{center:["50%","50%"],size:"85%",startAngle:0},defaultBackgroundOptions:{shape:"circle",borderWidth:1,borderColor:"#cccccc",backgroundColor:{linearGradient:{x1:0,y1:0,x2:0,y2:1},stops:[[0,"#ffffff"],[1,"#e6e6e6"]]},from:-Number.MAX_VALUE,innerRadius:0,to:Number.MAX_VALUE,outerRadius:"105%"},updateCenter:function(b){this.center=(b||this.axis||{}).center=
v.getCenter.call(this)},update:function(b,a){r(!0,this.options,b);this.setOptions(this.options);this.render();u(this.chart.axes,function(c){c.pane===this&&(c.pane=null,c.update({},a))},this)}});b.Pane=q})(w);(function(b){var q=b.addEvent,v=b.Axis,u=b.each,p=b.extend,r=b.map,g=b.merge,m=b.noop,a=b.pick,c=b.pInt,d=b.Tick,k=b.wrap,e=b.correctFloat,f,h,t=v.prototype,l=d.prototype;b.radialAxisExtended||(b.radialAxisExtended=!0,f={getOffset:m,redraw:function(){this.isDirty=!1},render:function(){this.isDirty=
!1},setScale:m,setCategories:m,setTitle:m},h={defaultRadialGaugeOptions:{labels:{align:"center",x:0,y:null},minorGridLineWidth:0,minorTickInterval:"auto",minorTickLength:10,minorTickPosition:"inside",minorTickWidth:1,tickLength:10,tickPosition:"inside",tickWidth:2,title:{rotation:0},zIndex:2},defaultRadialXOptions:{gridLineWidth:1,labels:{align:null,distance:15,x:0,y:null,style:{textOverflow:"none"}},maxPadding:0,minPadding:0,showLastLabel:!1,tickLength:0},defaultRadialYOptions:{gridLineInterpolation:"circle",
labels:{align:"right",x:-3,y:-2},showLastLabel:!1,title:{x:4,text:null,rotation:90}},setOptions:function(a){a=this.options=g(this.defaultOptions,this.defaultRadialOptions,a);a.plotBands||(a.plotBands=[])},getOffset:function(){t.getOffset.call(this);this.chart.axisOffset[this.side]=0},getLinePath:function(c,d){c=this.center;var n=this.chart,e=a(d,c[2]/2-this.offset);this.isCircular||void 0!==d?(d=this.chart.renderer.symbols.arc(this.left+c[0],this.top+c[1],e,e,{start:this.startAngleRad,end:this.endAngleRad,
open:!0,innerR:0}),d.xBounds=[this.left+c[0]],d.yBounds=[this.top+c[1]-e]):(d=this.postTranslate(this.angleRad,e),d=["M",c[0]+n.plotLeft,c[1]+n.plotTop,"L",d.x,d.y]);return d},setAxisTranslation:function(){t.setAxisTranslation.call(this);this.center&&(this.transA=this.isCircular?(this.endAngleRad-this.startAngleRad)/(this.max-this.min||1):this.center[2]/2/(this.max-this.min||1),this.minPixelPadding=this.isXAxis?this.transA*this.minPointOffset:0)},beforeSetTickPositions:function(){if(this.autoConnect=
this.isCircular&&void 0===a(this.userMax,this.options.max)&&e(this.endAngleRad-this.startAngleRad)===e(2*Math.PI))this.max+=this.categories&&1||this.pointRange||this.closestPointRange||0},setAxisSize:function(){t.setAxisSize.call(this);this.isRadial&&(this.pane.updateCenter(this),this.isCircular&&(this.sector=this.endAngleRad-this.startAngleRad),this.len=this.width=this.height=this.center[2]*a(this.sector,1)/2)},getPosition:function(c,d){return this.postTranslate(this.isCircular?this.translate(c):
this.angleRad,a(this.isCircular?d:this.translate(c),this.center[2]/2)-this.offset)},postTranslate:function(a,c){var d=this.chart,e=this.center;a=this.startAngleRad+a;return{x:d.plotLeft+e[0]+Math.cos(a)*c,y:d.plotTop+e[1]+Math.sin(a)*c}},getPlotBandPath:function(d,e,f){var b=this.center,n=this.startAngleRad,k=b[2]/2,h=[a(f.outerRadius,"100%"),f.innerRadius,a(f.thickness,10)],l=Math.min(this.offset,0),x=/%$/,t,B=this.isCircular;"polygon"===this.options.gridLineInterpolation?b=this.getPlotLinePath(d).concat(this.getPlotLinePath(e,
!0)):(d=Math.max(d,this.min),e=Math.min(e,this.max),B||(h[0]=this.translate(d),h[1]=this.translate(e)),h=r(h,function(a){x.test(a)&&(a=c(a,10)*k/100);return a}),"circle"!==f.shape&&B?(d=n+this.translate(d),e=n+this.translate(e)):(d=-Math.PI/2,e=1.5*Math.PI,t=!0),h[0]-=l,h[2]-=l,b=this.chart.renderer.symbols.arc(this.left+b[0],this.top+b[1],h[0],h[0],{start:Math.min(d,e),end:Math.max(d,e),innerR:a(h[1],h[0]-h[2]),open:t}));return b},getPlotLinePath:function(a,c){var d=this,e=d.center,b=d.chart,f=d.getPosition(a),
h,k,n;d.isCircular?n=["M",e[0]+b.plotLeft,e[1]+b.plotTop,"L",f.x,f.y]:"circle"===d.options.gridLineInterpolation?(a=d.translate(a))&&(n=d.getLinePath(0,a)):(u(b.xAxis,function(a){a.pane===d.pane&&(h=a)}),n=[],a=d.translate(a),e=h.tickPositions,h.autoConnect&&(e=e.concat([e[0]])),c&&(e=[].concat(e).reverse()),u(e,function(c,d){k=h.getPosition(c,a);n.push(d?"L":"M",k.x,k.y)}));return n},getTitlePosition:function(){var a=this.center,c=this.chart,d=this.options.title;return{x:c.plotLeft+a[0]+(d.x||0),
y:c.plotTop+a[1]-{high:.5,middle:.25,low:0}[d.align]*a[2]+(d.y||0)}}},q(v,"init",function(a){var c=this.chart,d=c.angular,e=c.polar,b=this.isXAxis,k=d&&b,l,n=c.options;a=a.userOptions.pane||0;a=this.pane=c.pane&&c.pane[a];if(d){if(p(this,k?f:h),l=!b)this.defaultRadialOptions=this.defaultRadialGaugeOptions}else e&&(p(this,h),this.defaultRadialOptions=(l=b)?this.defaultRadialXOptions:g(this.defaultYAxisOptions,this.defaultRadialYOptions));d||e?(this.isRadial=!0,c.inverted=!1,n.chart.zoomType=null):
this.isRadial=!1;a&&l&&(a.axis=this);this.isCircular=l}),q(v,"afterInit",function(){var c=this.chart,d=this.options,e=this.pane,b=e&&e.options;c.angular&&this.isXAxis||!e||!c.angular&&!c.polar||(this.angleRad=(d.angle||0)*Math.PI/180,this.startAngleRad=(b.startAngle-90)*Math.PI/180,this.endAngleRad=(a(b.endAngle,b.startAngle+360)-90)*Math.PI/180,this.offset=d.offset||0)}),k(t,"autoLabelAlign",function(a){if(!this.isRadial)return a.apply(this,[].slice.call(arguments,1))}),q(d,"afterGetPosition",function(a){this.axis.getPosition&&
p(a.pos,this.axis.getPosition(this.pos))}),q(d,"afterGetLabelPosition",function(c){var d=this.axis,e=this.label,b=d.options.labels,f=b.y,h,k=20,l=b.align,n=(d.translate(this.pos)+d.startAngleRad+Math.PI/2)/Math.PI*180%360;d.isRadial&&(h=d.getPosition(this.pos,d.center[2]/2+a(b.distance,-25)),"auto"===b.rotation?e.attr({rotation:n}):null===f&&(f=d.chart.renderer.fontMetrics(e.styles&&e.styles.fontSize).b-e.getBBox().height/2),null===l&&(d.isCircular?(this.label.getBBox().width>d.len*d.tickInterval/
(d.max-d.min)&&(k=0),l=n>k&&n<180-k?"left":n>180+k&&n<360-k?"right":"center"):l="center",e.attr({align:l})),c.pos.x=h.x+b.x,c.pos.y=h.y+f)}),k(l,"getMarkPath",function(a,c,d,e,b,f,h){var k=this.axis;k.isRadial?(a=k.getPosition(this.pos,k.center[2]/2+e),c=["M",c,d,"L",a.x,a.y]):c=a.call(this,c,d,e,b,f,h);return c}))})(w);(function(b){var q=b.each,v=b.pick,u=b.defined,p=b.seriesType,r=b.seriesTypes,g=b.Series.prototype,m=b.Point.prototype;p("arearange","area",{lineWidth:1,threshold:null,tooltip:{pointFormat:'\x3cspan style\x3d"color:{series.color}"\x3e\u25cf\x3c/span\x3e {series.name}: \x3cb\x3e{point.low}\x3c/b\x3e - \x3cb\x3e{point.high}\x3c/b\x3e\x3cbr/\x3e'},
trackByArea:!0,dataLabels:{align:null,verticalAlign:null,xLow:0,xHigh:0,yLow:0,yHigh:0}},{pointArrayMap:["low","high"],dataLabelCollections:["dataLabel","dataLabelUpper"],toYData:function(a){return[a.low,a.high]},pointValKey:"low",deferTranslatePolar:!0,highToXY:function(a){var c=this.chart,d=this.xAxis.postTranslate(a.rectPlotX,this.yAxis.len-a.plotHigh);a.plotHighX=d.x-c.plotLeft;a.plotHigh=d.y-c.plotTop;a.plotLowX=a.plotX},translate:function(){var a=this,c=a.yAxis,d=!!a.modifyValue;r.area.prototype.translate.apply(a);
q(a.points,function(b){var e=b.low,f=b.high,h=b.plotY;null===f||null===e?(b.isNull=!0,b.plotY=null):(b.plotLow=h,b.plotHigh=c.translate(d?a.modifyValue(f,b):f,0,1,0,1),d&&(b.yBottom=b.plotHigh))});this.chart.polar&&q(this.points,function(c){a.highToXY(c);c.tooltipPos=[(c.plotHighX+c.plotLowX)/2,(c.plotHigh+c.plotLow)/2]})},getGraphPath:function(a){var c=[],d=[],b,e=r.area.prototype.getGraphPath,f,h,t;t=this.options;var l=this.chart.polar&&!1!==t.connectEnds,n=t.connectNulls,x=t.step;a=a||this.points;
for(b=a.length;b--;)f=a[b],f.isNull||l||n||a[b+1]&&!a[b+1].isNull||d.push({plotX:f.plotX,plotY:f.plotY,doCurve:!1}),h={polarPlotY:f.polarPlotY,rectPlotX:f.rectPlotX,yBottom:f.yBottom,plotX:v(f.plotHighX,f.plotX),plotY:f.plotHigh,isNull:f.isNull},d.push(h),c.push(h),f.isNull||l||n||a[b-1]&&!a[b-1].isNull||d.push({plotX:f.plotX,plotY:f.plotY,doCurve:!1});a=e.call(this,a);x&&(!0===x&&(x="left"),t.step={left:"right",center:"center",right:"left"}[x]);c=e.call(this,c);d=e.call(this,d);t.step=x;t=[].concat(a,
c);this.chart.polar||"M"!==d[0]||(d[0]="L");this.graphPath=t;this.areaPath=a.concat(d);t.isArea=!0;t.xMap=a.xMap;this.areaPath.xMap=a.xMap;return t},drawDataLabels:function(){var a=this.data,c=a.length,d,b=[],e=this.options.dataLabels,f=e.align,h=e.verticalAlign,t=e.inside,l,n,x=this.chart.inverted;if(e.enabled||this._hasPointLabels){for(d=c;d--;)if(l=a[d])n=t?l.plotHigh<l.plotLow:l.plotHigh>l.plotLow,l.y=l.high,l._plotY=l.plotY,l.plotY=l.plotHigh,b[d]=l.dataLabel,l.dataLabel=l.dataLabelUpper,l.below=
n,x?f||(e.align=n?"right":"left"):h||(e.verticalAlign=n?"top":"bottom"),e.x=e.xHigh,e.y=e.yHigh;g.drawDataLabels&&g.drawDataLabels.apply(this,arguments);for(d=c;d--;)if(l=a[d])n=t?l.plotHigh<l.plotLow:l.plotHigh>l.plotLow,l.dataLabelUpper=l.dataLabel,l.dataLabel=b[d],l.y=l.low,l.plotY=l._plotY,l.below=!n,x?f||(e.align=n?"left":"right"):h||(e.verticalAlign=n?"bottom":"top"),e.x=e.xLow,e.y=e.yLow;g.drawDataLabels&&g.drawDataLabels.apply(this,arguments)}e.align=f;e.verticalAlign=h},alignDataLabel:function(){r.column.prototype.alignDataLabel.apply(this,
arguments)},drawPoints:function(){var a=this.points.length,c,d;g.drawPoints.apply(this,arguments);for(d=0;d<a;)c=this.points[d],c.origProps={plotY:c.plotY,plotX:c.plotX,isInside:c.isInside,negative:c.negative,zone:c.zone,y:c.y},c.lowerGraphic=c.graphic,c.graphic=c.upperGraphic,c.plotY=c.plotHigh,u(c.plotHighX)&&(c.plotX=c.plotHighX),c.y=c.high,c.negative=c.high<(this.options.threshold||0),c.zone=this.zones.length&&c.getZone(),this.chart.polar||(c.isInside=c.isTopInside=void 0!==c.plotY&&0<=c.plotY&&
c.plotY<=this.yAxis.len&&0<=c.plotX&&c.plotX<=this.xAxis.len),d++;g.drawPoints.apply(this,arguments);for(d=0;d<a;)c=this.points[d],c.upperGraphic=c.graphic,c.graphic=c.lowerGraphic,b.extend(c,c.origProps),delete c.origProps,d++},setStackedPoints:b.noop},{setState:function(){var a=this.state,c=this.series,d=c.chart.polar;u(this.plotHigh)||(this.plotHigh=c.yAxis.toPixels(this.high,!0));u(this.plotLow)||(this.plotLow=this.plotY=c.yAxis.toPixels(this.low,!0));c.stateMarkerGraphic&&(c.lowerStateMarkerGraphic=
c.stateMarkerGraphic,c.stateMarkerGraphic=c.upperStateMarkerGraphic);this.graphic=this.upperGraphic;this.plotY=this.plotHigh;d&&(this.plotX=this.plotHighX);m.setState.apply(this,arguments);this.state=a;this.plotY=this.plotLow;this.graphic=this.lowerGraphic;d&&(this.plotX=this.plotLowX);c.stateMarkerGraphic&&(c.upperStateMarkerGraphic=c.stateMarkerGraphic,c.stateMarkerGraphic=c.lowerStateMarkerGraphic,c.lowerStateMarkerGraphic=void 0);m.setState.apply(this,arguments)},haloPath:function(){var a=this.series.chart.polar,
c=[];this.plotY=this.plotLow;a&&(this.plotX=this.plotLowX);this.isInside&&(c=m.haloPath.apply(this,arguments));this.plotY=this.plotHigh;a&&(this.plotX=this.plotHighX);this.isTopInside&&(c=c.concat(m.haloPath.apply(this,arguments)));return c},destroyElements:function(){q(["lowerGraphic","upperGraphic"],function(a){this[a]&&(this[a]=this[a].destroy())},this);this.graphic=null;return m.destroyElements.apply(this,arguments)}})})(w);(function(b){var q=b.seriesType;q("areasplinerange","arearange",null,
{getPointSpline:b.seriesTypes.spline.prototype.getPointSpline})})(w);(function(b){var q=b.defaultPlotOptions,v=b.each,u=b.merge,p=b.noop,r=b.pick,g=b.seriesType,m=b.seriesTypes.column.prototype;g("columnrange","arearange",u(q.column,q.arearange,{pointRange:null,marker:null,states:{hover:{halo:!1}}}),{translate:function(){var a=this,c=a.yAxis,d=a.xAxis,b=d.startAngleRad,e,f=a.chart,h=a.xAxis.isRadial,t=Math.max(f.chartWidth,f.chartHeight)+999,l;m.translate.apply(a);v(a.points,function(k){var n=k.shapeArgs,
m=a.options.minPointLength,y,g;k.plotHigh=l=Math.min(Math.max(-t,c.translate(k.high,0,1,0,1)),t);k.plotLow=Math.min(Math.max(-t,k.plotY),t);g=l;y=r(k.rectPlotY,k.plotY)-l;Math.abs(y)<m?(m-=y,y+=m,g-=m/2):0>y&&(y*=-1,g-=y);h?(e=k.barX+b,k.shapeType="path",k.shapeArgs={d:a.polarArc(g+y,g,e,e+k.pointWidth)}):(n.height=y,n.y=g,k.tooltipPos=f.inverted?[c.len+c.pos-f.plotLeft-g-y/2,d.len+d.pos-f.plotTop-n.x-n.width/2,y]:[d.left-f.plotLeft+n.x+n.width/2,c.pos-f.plotTop+g+y/2,y])})},directTouch:!0,trackerGroups:["group",
"dataLabelsGroup"],drawGraph:p,getSymbol:p,crispCol:m.crispCol,drawPoints:m.drawPoints,drawTracker:m.drawTracker,getColumnMetrics:m.getColumnMetrics,pointAttribs:m.pointAttribs,animate:function(){return m.animate.apply(this,arguments)},polarArc:function(){return m.polarArc.apply(this,arguments)},translate3dPoints:function(){return m.translate3dPoints.apply(this,arguments)},translate3dShapes:function(){return m.translate3dShapes.apply(this,arguments)}},{setState:m.pointClass.prototype.setState})})(w);
(function(b){var q=b.each,v=b.isNumber,u=b.merge,p=b.pick,r=b.pInt,g=b.Series,m=b.seriesType,a=b.TrackerMixin;m("gauge","line",{dataLabels:{enabled:!0,defer:!1,y:15,borderRadius:3,crop:!1,verticalAlign:"top",zIndex:2,borderWidth:1,borderColor:"#cccccc"},dial:{},pivot:{},tooltip:{headerFormat:""},showInLegend:!1},{angular:!0,directTouch:!0,drawGraph:b.noop,fixedBox:!0,forceDL:!0,noSharedTooltip:!0,trackerGroups:["group","dataLabelsGroup"],translate:function(){var a=this.yAxis,d=this.options,b=a.center;
this.generatePoints();q(this.points,function(c){var e=u(d.dial,c.dial),h=r(p(e.radius,80))*b[2]/200,k=r(p(e.baseLength,70))*h/100,l=r(p(e.rearLength,10))*h/100,n=e.baseWidth||3,x=e.topWidth||1,g=d.overshoot,m=a.startAngleRad+a.translate(c.y,null,null,null,!0);v(g)?(g=g/180*Math.PI,m=Math.max(a.startAngleRad-g,Math.min(a.endAngleRad+g,m))):!1===d.wrap&&(m=Math.max(a.startAngleRad,Math.min(a.endAngleRad,m)));m=180*m/Math.PI;c.shapeType="path";c.shapeArgs={d:e.path||["M",-l,-n/2,"L",k,-n/2,h,-x/2,h,
x/2,k,n/2,-l,n/2,"z"],translateX:b[0],translateY:b[1],rotation:m};c.plotX=b[0];c.plotY=b[1]})},drawPoints:function(){var a=this,d=a.yAxis.center,b=a.pivot,e=a.options,f=e.pivot,h=a.chart.renderer;q(a.points,function(c){var d=c.graphic,b=c.shapeArgs,f=b.d,k=u(e.dial,c.dial);d?(d.animate(b),b.d=f):(c.graphic=h[c.shapeType](b).attr({rotation:b.rotation,zIndex:1}).addClass("highcharts-dial").add(a.group),c.graphic.attr({stroke:k.borderColor||"none","stroke-width":k.borderWidth||0,fill:k.backgroundColor||
"#000000"}))});b?b.animate({translateX:d[0],translateY:d[1]}):(a.pivot=h.circle(0,0,p(f.radius,5)).attr({zIndex:2}).addClass("highcharts-pivot").translate(d[0],d[1]).add(a.group),a.pivot.attr({"stroke-width":f.borderWidth||0,stroke:f.borderColor||"#cccccc",fill:f.backgroundColor||"#000000"}))},animate:function(a){var c=this;a||(q(c.points,function(a){var d=a.graphic;d&&(d.attr({rotation:180*c.yAxis.startAngleRad/Math.PI}),d.animate({rotation:a.shapeArgs.rotation},c.options.animation))}),c.animate=
null)},render:function(){this.group=this.plotGroup("group","series",this.visible?"visible":"hidden",this.options.zIndex,this.chart.seriesGroup);g.prototype.render.call(this);this.group.clip(this.chart.clipRect)},setData:function(a,d){g.prototype.setData.call(this,a,!1);this.processData();this.generatePoints();p(d,!0)&&this.chart.redraw()},drawTracker:a&&a.drawTrackerPoint},{setState:function(a){this.state=a}})})(w);(function(b){var q=b.each,v=b.noop,u=b.pick,p=b.seriesType,r=b.seriesTypes;p("boxplot",
"column",{threshold:null,tooltip:{pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e \x3cb\x3e {series.name}\x3c/b\x3e\x3cbr/\x3eMaximum: {point.high}\x3cbr/\x3eUpper quartile: {point.q3}\x3cbr/\x3eMedian: {point.median}\x3cbr/\x3eLower quartile: {point.q1}\x3cbr/\x3eMinimum: {point.low}\x3cbr/\x3e'},whiskerLength:"50%",fillColor:"#ffffff",lineWidth:1,medianWidth:2,whiskerWidth:2},{pointArrayMap:["low","q1","median","q3","high"],toYData:function(b){return[b.low,b.q1,b.median,
b.q3,b.high]},pointValKey:"high",pointAttribs:function(){return{}},drawDataLabels:v,translate:function(){var b=this.yAxis,m=this.pointArrayMap;r.column.prototype.translate.apply(this);q(this.points,function(a){q(m,function(c){null!==a[c]&&(a[c+"Plot"]=b.translate(a[c],0,1,0,1))})})},drawPoints:function(){var b=this,m=b.options,a=b.chart.renderer,c,d,k,e,f,h,t=0,l,n,x,r,p=!1!==b.doQuartiles,v,A=b.options.whiskerLength;q(b.points,function(g){var q=g.graphic,y=q?"animate":"attr",B=g.shapeArgs,w={},D=
{},I={},J={},C=g.color||b.color;void 0!==g.plotY&&(l=B.width,n=Math.floor(B.x),x=n+l,r=Math.round(l/2),c=Math.floor(p?g.q1Plot:g.lowPlot),d=Math.floor(p?g.q3Plot:g.lowPlot),k=Math.floor(g.highPlot),e=Math.floor(g.lowPlot),q||(g.graphic=q=a.g("point").add(b.group),g.stem=a.path().addClass("highcharts-boxplot-stem").add(q),A&&(g.whiskers=a.path().addClass("highcharts-boxplot-whisker").add(q)),p&&(g.box=a.path(void 0).addClass("highcharts-boxplot-box").add(q)),g.medianShape=a.path(void 0).addClass("highcharts-boxplot-median").add(q)),
D.stroke=g.stemColor||m.stemColor||C,D["stroke-width"]=u(g.stemWidth,m.stemWidth,m.lineWidth),D.dashstyle=g.stemDashStyle||m.stemDashStyle,g.stem.attr(D),A&&(I.stroke=g.whiskerColor||m.whiskerColor||C,I["stroke-width"]=u(g.whiskerWidth,m.whiskerWidth,m.lineWidth),g.whiskers.attr(I)),p&&(w.fill=g.fillColor||m.fillColor||C,w.stroke=m.lineColor||C,w["stroke-width"]=m.lineWidth||0,g.box.attr(w)),J.stroke=g.medianColor||m.medianColor||C,J["stroke-width"]=u(g.medianWidth,m.medianWidth,m.lineWidth),g.medianShape.attr(J),
h=g.stem.strokeWidth()%2/2,t=n+r+h,g.stem[y]({d:["M",t,d,"L",t,k,"M",t,c,"L",t,e]}),p&&(h=g.box.strokeWidth()%2/2,c=Math.floor(c)+h,d=Math.floor(d)+h,n+=h,x+=h,g.box[y]({d:["M",n,d,"L",n,c,"L",x,c,"L",x,d,"L",n,d,"z"]})),A&&(h=g.whiskers.strokeWidth()%2/2,k+=h,e+=h,v=/%$/.test(A)?r*parseFloat(A)/100:A/2,g.whiskers[y]({d:["M",t-v,k,"L",t+v,k,"M",t-v,e,"L",t+v,e]})),f=Math.round(g.medianPlot),h=g.medianShape.strokeWidth()%2/2,f+=h,g.medianShape[y]({d:["M",n,f,"L",x,f]}))})},setStackedPoints:v})})(w);
(function(b){var q=b.each,v=b.noop,u=b.seriesType,p=b.seriesTypes;u("errorbar","boxplot",{color:"#000000",grouping:!1,linkedTo:":previous",tooltip:{pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e {series.name}: \x3cb\x3e{point.low}\x3c/b\x3e - \x3cb\x3e{point.high}\x3c/b\x3e\x3cbr/\x3e'},whiskerWidth:null},{type:"errorbar",pointArrayMap:["low","high"],toYData:function(b){return[b.low,b.high]},pointValKey:"high",doQuartiles:!1,drawDataLabels:p.arearange?function(){var b=
this.pointValKey;p.arearange.prototype.drawDataLabels.call(this);q(this.data,function(g){g.y=g[b]})}:v,getColumnMetrics:function(){return this.linkedParent&&this.linkedParent.columnMetrics||p.column.prototype.getColumnMetrics.call(this)}})})(w);(function(b){var q=b.correctFloat,v=b.isNumber,u=b.pick,p=b.Point,r=b.Series,g=b.seriesType,m=b.seriesTypes;g("waterfall","column",{dataLabels:{inside:!0},lineWidth:1,lineColor:"#333333",dashStyle:"dot",borderColor:"#333333",states:{hover:{lineWidthPlus:0}}},
{pointValKey:"y",showLine:!0,generatePoints:function(){var a=this.options.threshold,c,b,k,e;m.column.prototype.generatePoints.apply(this);k=0;for(b=this.points.length;k<b;k++)c=this.points[k],e=this.processedYData[k],c.isSum?c.y=q(e):c.isIntermediateSum&&(c.y=q(e-a),a=e)},translate:function(){var a=this.options,c=this.yAxis,b,k,e,f,h,t,l,n,g,p,q=u(a.minPointLength,5),r=q/2,v=a.threshold,w=a.stacking,z;m.column.prototype.translate.apply(this);n=g=v;k=this.points;b=0;for(a=k.length;b<a;b++)e=k[b],l=
this.processedYData[b],f=e.shapeArgs,h=w&&c.stacks[(this.negStacks&&l<v?"-":"")+this.stackKey],z=this.getStackIndicator(z,e.x,this.index),p=u(h&&h[e.x].points[z.key],[0,l]),t=Math.max(n,n+e.y)+p[0],f.y=c.translate(t,0,1,0,1),e.isSum?(f.y=c.translate(p[1],0,1,0,1),f.height=Math.min(c.translate(p[0],0,1,0,1),c.len)-f.y):e.isIntermediateSum?(f.y=c.translate(p[1],0,1,0,1),f.height=Math.min(c.translate(g,0,1,0,1),c.len)-f.y,g=p[1]):(f.height=0<l?c.translate(n,0,1,0,1)-f.y:c.translate(n,0,1,0,1)-c.translate(n-
l,0,1,0,1),n+=h&&h[e.x]?h[e.x].total:l),0>f.height&&(f.y+=f.height,f.height*=-1),e.plotY=f.y=Math.round(f.y)-this.borderWidth%2/2,f.height=Math.max(Math.round(f.height),.001),e.yBottom=f.y+f.height,f.height<=q&&!e.isNull?(f.height=q,f.y-=r,e.plotY=f.y,e.minPointLengthOffset=0>e.y?-r:r):e.minPointLengthOffset=0,f=e.plotY+(e.negative?f.height:0),this.chart.inverted?e.tooltipPos[0]=c.len-f:e.tooltipPos[1]=f},processData:function(a){var c=this.yData,b=this.options.data,k,e=c.length,f,h,t,l,n,g;h=f=t=
l=this.options.threshold||0;for(g=0;g<e;g++)n=c[g],k=b&&b[g]?b[g]:{},"sum"===n||k.isSum?c[g]=q(h):"intermediateSum"===n||k.isIntermediateSum?c[g]=q(f):(h+=n,f+=n),t=Math.min(h,t),l=Math.max(h,l);r.prototype.processData.call(this,a);this.options.stacking||(this.dataMin=t,this.dataMax=l)},toYData:function(a){return a.isSum?0===a.x?null:"sum":a.isIntermediateSum?0===a.x?null:"intermediateSum":a.y},pointAttribs:function(a,c){var b=this.options.upColor;b&&!a.options.color&&(a.color=0<a.y?b:null);a=m.column.prototype.pointAttribs.call(this,
a,c);delete a.dashstyle;return a},getGraphPath:function(){return["M",0,0]},getCrispPath:function(){var a=this.data,c=a.length,b=this.graph.strokeWidth()+this.borderWidth,b=Math.round(b)%2/2,k=this.xAxis.reversed,e=this.yAxis.reversed,f=[],h,g,l;for(l=1;l<c;l++){g=a[l].shapeArgs;h=a[l-1].shapeArgs;g=["M",h.x+(k?0:h.width),h.y+a[l-1].minPointLengthOffset+b,"L",g.x+(k?h.width:0),h.y+a[l-1].minPointLengthOffset+b];if(0>a[l-1].y&&!e||0<a[l-1].y&&e)g[2]+=h.height,g[5]+=h.height;f=f.concat(g)}return f},
drawGraph:function(){r.prototype.drawGraph.call(this);this.graph.attr({d:this.getCrispPath()})},setStackedPoints:function(){var a=this.options,c,b;r.prototype.setStackedPoints.apply(this,arguments);c=this.stackedYData?this.stackedYData.length:0;for(b=1;b<c;b++)a.data[b].isSum||a.data[b].isIntermediateSum||(this.stackedYData[b]+=this.stackedYData[b-1])},getExtremes:function(){if(this.options.stacking)return r.prototype.getExtremes.apply(this,arguments)}},{getClassName:function(){var a=p.prototype.getClassName.call(this);
this.isSum?a+=" highcharts-sum":this.isIntermediateSum&&(a+=" highcharts-intermediate-sum");return a},isValid:function(){return v(this.y,!0)||this.isSum||this.isIntermediateSum}})})(w);(function(b){var q=b.Series,v=b.seriesType,u=b.seriesTypes;v("polygon","scatter",{marker:{enabled:!1,states:{hover:{enabled:!1}}},stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:""},trackByArea:!0},{type:"polygon",getGraphPath:function(){for(var b=q.prototype.getGraphPath.call(this),r=b.length+1;r--;)(r===b.length||
"M"===b[r])&&0<r&&b.splice(r,0,"z");return this.areaPath=b},drawGraph:function(){this.options.fillColor=this.color;u.area.prototype.drawGraph.call(this)},drawLegendSymbol:b.LegendSymbolMixin.drawRectangle,drawTracker:q.prototype.drawTracker,setStackedPoints:b.noop})})(w);(function(b){var q=b.arrayMax,v=b.arrayMin,u=b.Axis,p=b.color,r=b.each,g=b.isNumber,m=b.noop,a=b.pick,c=b.pInt,d=b.Point,k=b.Series,e=b.seriesType,f=b.seriesTypes;e("bubble","scatter",{dataLabels:{formatter:function(){return this.point.z},
inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"},{pointArrayMap:["y","z"],parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",bubblePadding:!0,zoneAxis:"z",directTouch:!0,
pointAttribs:function(a,c){var b=this.options.marker.fillOpacity;a=k.prototype.pointAttribs.call(this,a,c);1!==b&&(a.fill=p(a.fill).setOpacity(b).get("rgba"));return a},getRadii:function(a,c,b,d){var e,f,h,k=this.zData,l=[],g=this.options,n="width"!==g.sizeBy,t=g.zThreshold,m=c-a;f=0;for(e=k.length;f<e;f++)h=k[f],g.sizeByAbsoluteValue&&null!==h&&(h=Math.abs(h-t),c=m=Math.max(c-t,Math.abs(a-t)),a=0),null===h?h=null:h<a?h=b/2-1:(h=0<m?(h-a)/m:.5,n&&0<=h&&(h=Math.sqrt(h)),h=Math.ceil(b+h*(d-b))/2),l.push(h);
this.radii=l},animate:function(a){!a&&this.points.length<this.options.animationLimit&&(r(this.points,function(a){var c=a.graphic,b;c&&c.width&&(b={x:c.x,y:c.y,width:c.width,height:c.height},c.attr({x:a.plotX,y:a.plotY,width:1,height:1}),c.animate(b,this.options.animation))},this),this.animate=null)},translate:function(){var a,c=this.data,d,e,k=this.radii;f.scatter.prototype.translate.call(this);for(a=c.length;a--;)d=c[a],e=k?k[a]:0,g(e)&&e>=this.minPxSize/2?(d.marker=b.extend(d.marker,{radius:e,width:2*
e,height:2*e}),d.dlBox={x:d.plotX-e,y:d.plotY-e,width:2*e,height:2*e}):d.shapeArgs=d.plotY=d.dlBox=void 0},alignDataLabel:f.column.prototype.alignDataLabel,buildKDTree:m,applyZones:m},{haloPath:function(a){return d.prototype.haloPath.call(this,0===a?0:(this.marker?this.marker.radius||0:0)+a)},ttBelow:!1});u.prototype.beforePadding=function(){var b=this,d=this.len,e=this.chart,f=0,k=d,m=this.isXAxis,p=m?"xData":"yData",u=this.min,w={},K=Math.min(e.plotWidth,e.plotHeight),z=Number.MAX_VALUE,F=-Number.MAX_VALUE,
G=this.max-u,E=d/G,H=[];r(this.series,function(d){var f=d.options;!d.bubblePadding||!d.visible&&e.options.chart.ignoreHiddenSeries||(b.allowZoomOutside=!0,H.push(d),m&&(r(["minSize","maxSize"],function(a){var b=f[a],d=/%$/.test(b),b=c(b);w[a]=d?K*b/100:b}),d.minPxSize=w.minSize,d.maxPxSize=Math.max(w.maxSize,w.minSize),d=d.zData,d.length&&(z=a(f.zMin,Math.min(z,Math.max(v(d),!1===f.displayNegative?f.zThreshold:-Number.MAX_VALUE))),F=a(f.zMax,Math.max(F,q(d))))))});r(H,function(a){var c=a[p],d=c.length,
e;m&&a.getRadii(z,F,a.minPxSize,a.maxPxSize);if(0<G)for(;d--;)g(c[d])&&b.dataMin<=c[d]&&c[d]<=b.dataMax&&(e=a.radii[d],f=Math.min((c[d]-u)*E-e,f),k=Math.max((c[d]-u)*E+e,k))});H.length&&0<G&&!this.isLog&&(k-=d,E*=(d+f-k)/d,r([["min","userMin",f],["max","userMax",k]],function(c){void 0===a(b.options[c[0]],b[c[1]])&&(b[c[0]]+=c[2]/E)}))}})(w);(function(b){var q=b.each,v=b.pick,u=b.Series,p=b.seriesTypes,r=b.wrap,g=u.prototype,m=b.Pointer.prototype;b.polarExtended||(b.polarExtended=!0,g.searchPointByAngle=
function(a){var c=this.chart,b=this.xAxis.pane.center;return this.searchKDTree({clientX:180+-180/Math.PI*Math.atan2(a.chartX-b[0]-c.plotLeft,a.chartY-b[1]-c.plotTop)})},g.getConnectors=function(a,c,b,k){var d,f,h,g,l,n,m,p;f=k?1:0;d=0<=c&&c<=a.length-1?c:0>c?a.length-1+c:0;c=0>d-1?a.length-(1+f):d-1;f=d+1>a.length-1?f:d+1;h=a[c];f=a[f];g=h.plotX;h=h.plotY;l=f.plotX;n=f.plotY;f=a[d].plotX;d=a[d].plotY;g=(1.5*f+g)/2.5;h=(1.5*d+h)/2.5;l=(1.5*f+l)/2.5;m=(1.5*d+n)/2.5;n=Math.sqrt(Math.pow(g-f,2)+Math.pow(h-
d,2));p=Math.sqrt(Math.pow(l-f,2)+Math.pow(m-d,2));g=Math.atan2(h-d,g-f);m=Math.PI/2+(g+Math.atan2(m-d,l-f))/2;Math.abs(g-m)>Math.PI/2&&(m-=Math.PI);g=f+Math.cos(m)*n;h=d+Math.sin(m)*n;l=f+Math.cos(Math.PI+m)*p;m=d+Math.sin(Math.PI+m)*p;f={rightContX:l,rightContY:m,leftContX:g,leftContY:h,plotX:f,plotY:d};b&&(f.prevPointCont=this.getConnectors(a,c,!1,k));return f},r(g,"buildKDTree",function(a){this.chart.polar&&(this.kdByAngle?this.searchPoint=this.searchPointByAngle:this.options.findNearestPointBy=
"xy");a.apply(this)}),g.toXY=function(a){var c,b=this.chart,k=a.plotX;c=a.plotY;a.rectPlotX=k;a.rectPlotY=c;c=this.xAxis.postTranslate(a.plotX,this.yAxis.len-c);a.plotX=a.polarPlotX=c.x-b.plotLeft;a.plotY=a.polarPlotY=c.y-b.plotTop;this.kdByAngle?(b=(k/Math.PI*180+this.xAxis.pane.options.startAngle)%360,0>b&&(b+=360),a.clientX=b):a.clientX=a.plotX},p.spline&&(r(p.spline.prototype,"getPointSpline",function(a,c,b,k){this.chart.polar?k?(a=this.getConnectors(c,k,!0,this.connectEnds),a=["C",a.prevPointCont.rightContX,
a.prevPointCont.rightContY,a.leftContX,a.leftContY,a.plotX,a.plotY]):a=["M",b.plotX,b.plotY]:a=a.call(this,c,b,k);return a}),p.areasplinerange&&(p.areasplinerange.prototype.getPointSpline=p.spline.prototype.getPointSpline)),b.addEvent(u,"afterTranslate",function(){var a=this.chart,c,d;if(a.polar){this.kdByAngle=a.tooltip&&a.tooltip.shared;if(!this.preventPostTranslate)for(c=this.points,d=c.length;d--;)this.toXY(c[d]);this.hasClipCircleSetter||(this.hasClipCircleSetter=!!b.addEvent(this,"afterRender",
function(){var c;a.polar&&(c=this.yAxis.center,this.group.clip(a.renderer.clipCircle(c[0],c[1],c[2]/2)),this.setClip=b.noop)}))}}),r(g,"getGraphPath",function(a,c){var b=this,g,e,f;if(this.chart.polar){c=c||this.points;for(g=0;g<c.length;g++)if(!c[g].isNull){e=g;break}!1!==this.options.connectEnds&&void 0!==e&&(this.connectEnds=!0,c.splice(c.length,0,c[e]),f=!0);q(c,function(a){void 0===a.polarPlotY&&b.toXY(a)})}g=a.apply(this,[].slice.call(arguments,1));f&&c.pop();return g}),u=function(a,c){var b=
this.chart,g=this.options.animation,e=this.group,f=this.markerGroup,h=this.xAxis.center,m=b.plotLeft,l=b.plotTop;b.polar?b.renderer.isSVG&&(!0===g&&(g={}),c?(a={translateX:h[0]+m,translateY:h[1]+l,scaleX:.001,scaleY:.001},e.attr(a),f&&f.attr(a)):(a={translateX:m,translateY:l,scaleX:1,scaleY:1},e.animate(a,g),f&&f.animate(a,g),this.animate=null)):a.call(this,c)},r(g,"animate",u),p.column&&(p=p.column.prototype,p.polarArc=function(a,b,d,g){var c=this.xAxis.center,f=this.yAxis.len;return this.chart.renderer.symbols.arc(c[0],
c[1],f-b,null,{start:d,end:g,innerR:f-v(a,f)})},r(p,"animate",u),r(p,"translate",function(a){var b=this.xAxis,d=b.startAngleRad,g,e,f;this.preventPostTranslate=!0;a.call(this);if(b.isRadial)for(g=this.points,f=g.length;f--;)e=g[f],a=e.barX+d,e.shapeType="path",e.shapeArgs={d:this.polarArc(e.yBottom,e.plotY,a,a+e.pointWidth)},this.toXY(e),e.tooltipPos=[e.plotX,e.plotY],e.ttBelow=e.plotY>b.center[1]}),r(p,"alignDataLabel",function(a,b,d,k,e,f){this.chart.polar?(a=b.rectPlotX/Math.PI*180,null===k.align&&
(k.align=20<a&&160>a?"left":200<a&&340>a?"right":"center"),null===k.verticalAlign&&(k.verticalAlign=45>a||315<a?"bottom":135<a&&225>a?"top":"middle"),g.alignDataLabel.call(this,b,d,k,e,f)):a.call(this,b,d,k,e,f)})),r(m,"getCoordinates",function(a,b){var c=this.chart,g={xAxis:[],yAxis:[]};c.polar?q(c.axes,function(a){var d=a.isXAxis,e=a.center,k=b.chartX-e[0]-c.plotLeft,e=b.chartY-e[1]-c.plotTop;g[d?"xAxis":"yAxis"].push({axis:a,value:a.translate(d?Math.PI-Math.atan2(k,e):Math.sqrt(Math.pow(k,2)+Math.pow(e,
2)),!0)})}):g=a.call(this,b);return g}),b.SVGRenderer.prototype.clipCircle=function(a,c,d){var g=b.uniqueKey(),e=this.createElement("clipPath").attr({id:g}).add(this.defs);a=this.circle(a,c,d).add(e);a.id=g;a.clipPath=e;return a},b.addEvent(b.Chart,"getAxes",function(){this.pane||(this.pane=[]);q(b.splat(this.options.pane),function(a){new b.Pane(a,this)},this)}),b.addEvent(b.Chart,"afterDrawChartBox",function(){q(this.pane,function(a){a.render()})}),r(b.Chart.prototype,"get",function(a,c){return b.find(this.pane,
function(a){return a.options.id===c})||a.call(this,c)}))})(w)});
