/*
 Highcharts JS v6.1.0-modified (2018-05-17)

 3D features for Highcharts JS

 @license: www.highcharts.com/license
*/
(function(A){"object"===typeof module&&module.exports?module.exports=A:A(Highcharts)})(function(A){(function(b){var t=b.deg2rad,x=b.pick;b.perspective3D=function(b,q,y){q=0<y&&y<Number.POSITIVE_INFINITY?y/(b.z+q.z+y):1;return{x:b.x*q,y:b.y*q}};b.perspective=function(r,q,y){var z=q.options.chart.options3d,n=y?q.inverted:!1,g={x:q.plotWidth/2,y:q.plotHeight/2,z:z.depth/2,vd:x(z.depth,1)*x(z.viewDistance,0)},w=q.scale3d||1,v=t*z.beta*(n?-1:1),z=t*z.alpha*(n?-1:1),k=Math.cos(z),a=Math.cos(-v),e=Math.sin(z),
l=Math.sin(-v);y||(g.x+=q.plotLeft,g.y+=q.plotTop);return b.map(r,function(f){var h;h=(n?f.y:f.x)-g.x;var d=(n?f.x:f.y)-g.y;f=(f.z||0)-g.z;h={x:a*h-l*f,y:-e*l*h+k*d-a*e*f,z:k*l*h+e*d+k*a*f};d=b.perspective3D(h,g,g.vd);d.x=d.x*w+g.x;d.y=d.y*w+g.y;d.z=h.z*w+g.z;return{x:n?d.y:d.x,y:n?d.x:d.y,z:d.z}})};b.pointCameraDistance=function(b,q){var r=q.options.chart.options3d,z=q.plotWidth/2;q=q.plotHeight/2;r=x(r.depth,1)*x(r.viewDistance,0)+r.depth;return Math.sqrt(Math.pow(z-b.plotX,2)+Math.pow(q-b.plotY,
2)+Math.pow(r-b.plotZ,2))};b.shapeArea=function(b){var q=0,r,z;for(r=0;r<b.length;r++)z=(r+1)%b.length,q+=b[r].x*b[z].y-b[z].x*b[r].y;return q/2};b.shapeArea3d=function(r,q,y){return b.shapeArea(b.perspective(r,q,y))}})(A);(function(b){function t(a,c,d,b,e,f,h,k){var B=[],m=f-e;return f>e&&f-e>Math.PI/2+.0001?(B=B.concat(t(a,c,d,b,e,e+Math.PI/2,h,k)),B=B.concat(t(a,c,d,b,e+Math.PI/2,f,h,k))):f<e&&e-f>Math.PI/2+.0001?(B=B.concat(t(a,c,d,b,e,e-Math.PI/2,h,k)),B=B.concat(t(a,c,d,b,e-Math.PI/2,f,h,k))):
["C",a+d*Math.cos(e)-d*u*m*Math.sin(e)+h,c+b*Math.sin(e)+b*u*m*Math.cos(e)+k,a+d*Math.cos(f)+d*u*m*Math.sin(f)+h,c+b*Math.sin(f)-b*u*m*Math.cos(f)+k,a+d*Math.cos(f)+h,c+b*Math.sin(f)+k]}var x=Math.cos,r=Math.PI,q=Math.sin,y=b.animObject,z=b.charts,n=b.color,g=b.defined,w=b.deg2rad,v=b.each,k=b.extend,a=b.inArray,e=b.map,l=b.merge,f=b.perspective,h=b.pick,d=b.SVGElement,c=b.SVGRenderer,p=b.wrap,u=4*(Math.sqrt(2)-1)/3/(r/2);c.prototype.toLinePath=function(a,c){var d=[];v(a,function(a){d.push("L",a.x,
a.y)});a.length&&(d[0]="M",c&&d.push("Z"));return d};c.prototype.toLineSegments=function(a){var c=[],d=!0;v(a,function(a){c.push(d?"M":"L",a.x,a.y);d=!d});return c};c.prototype.face3d=function(a){var c=this,d=this.createElement("path");d.vertexes=[];d.insidePlotArea=!1;d.enabled=!0;p(d,"attr",function(a,d){if("object"===typeof d&&(g(d.enabled)||g(d.vertexes)||g(d.insidePlotArea))){this.enabled=h(d.enabled,this.enabled);this.vertexes=h(d.vertexes,this.vertexes);this.insidePlotArea=h(d.insidePlotArea,
this.insidePlotArea);delete d.enabled;delete d.vertexes;delete d.insidePlotArea;var e=f(this.vertexes,z[c.chartIndex],this.insidePlotArea),B=c.toLinePath(e,!0),e=b.shapeArea(e),e=this.enabled&&0<e?"visible":"hidden";d.d=B;d.visibility=e}return a.apply(this,[].slice.call(arguments,1))});p(d,"animate",function(a,d){if("object"===typeof d&&(g(d.enabled)||g(d.vertexes)||g(d.insidePlotArea))){this.enabled=h(d.enabled,this.enabled);this.vertexes=h(d.vertexes,this.vertexes);this.insidePlotArea=h(d.insidePlotArea,
this.insidePlotArea);delete d.enabled;delete d.vertexes;delete d.insidePlotArea;var e=f(this.vertexes,z[c.chartIndex],this.insidePlotArea),B=c.toLinePath(e,!0),e=b.shapeArea(e),e=this.enabled&&0<e?"visible":"hidden";d.d=B;this.attr("visibility",e)}return a.apply(this,[].slice.call(arguments,1))});return d.attr(a)};c.prototype.polyhedron=function(a){var d=this,c=this.g(),b=c.destroy;c.attr({"stroke-linejoin":"round"});c.faces=[];c.destroy=function(){for(var a=0;a<c.faces.length;a++)c.faces[a].destroy();
return b.call(this)};p(c,"attr",function(a,b,e,m,f){if("object"===typeof b&&g(b.faces)){for(;c.faces.length>b.faces.length;)c.faces.pop().destroy();for(;c.faces.length<b.faces.length;)c.faces.push(d.face3d().add(c));for(var F=0;F<b.faces.length;F++)c.faces[F].attr(b.faces[F],null,m,f);delete b.faces}return a.apply(this,[].slice.call(arguments,1))});p(c,"animate",function(a,b,e,m){if(b&&b.faces){for(;c.faces.length>b.faces.length;)c.faces.pop().destroy();for(;c.faces.length<b.faces.length;)c.faces.push(d.face3d().add(c));
for(var f=0;f<b.faces.length;f++)c.faces[f].animate(b.faces[f],e,m);delete b.faces}return a.apply(this,[].slice.call(arguments,1))});return c.attr(a)};c.prototype.cuboid=function(a){var c=this.g(),b=c.destroy;a=this.cuboidPath(a);c.attr({"stroke-linejoin":"round"});c.front=this.path(a[0]).attr({"class":"highcharts-3d-front"}).add(c);c.top=this.path(a[1]).attr({"class":"highcharts-3d-top"}).add(c);c.side=this.path(a[2]).attr({"class":"highcharts-3d-side"}).add(c);c.fillSetter=function(a){this.front.attr({fill:a});
this.top.attr({fill:n(a).brighten(.1).get()});this.side.attr({fill:n(a).brighten(-.1).get()});this.color=a;c.fill=a;return this};c.opacitySetter=function(a){this.front.attr({opacity:a});this.top.attr({opacity:a});this.side.attr({opacity:a});return this};c.attr=function(a,c,b,e){if("string"===typeof a&&"undefined"!==typeof c){var f=a;a={};a[f]=c}if(a.shapeArgs||g(a.x))a=this.renderer.cuboidPath(a.shapeArgs||a),this.front.attr({d:a[0]}),this.top.attr({d:a[1]}),this.side.attr({d:a[2]});else return d.prototype.attr.call(this,
a,void 0,b,e);return this};c.animate=function(a,c,b){g(a.x)&&g(a.y)?(a=this.renderer.cuboidPath(a),this.front.animate({d:a[0]},c,b),this.top.animate({d:a[1]},c,b),this.side.animate({d:a[2]},c,b),this.attr({zIndex:-a[3]})):a.opacity?(this.front.animate(a,c,b),this.top.animate(a,c,b),this.side.animate(a,c,b)):d.prototype.animate.call(this,a,c,b);return this};c.destroy=function(){this.front.destroy();this.top.destroy();this.side.destroy();return b.call(this)};c.attr({zIndex:-a[3]});return c};b.SVGRenderer.prototype.cuboidPath=
function(a){function c(a){return g[a]}var d=a.x,h=a.y,m=a.z,k=a.height,u=a.width,l=a.depth,p=z[this.chartIndex],v,n,q=p.options.chart.options3d.alpha,r=0,g=[{x:d,y:h,z:m},{x:d+u,y:h,z:m},{x:d+u,y:h+k,z:m},{x:d,y:h+k,z:m},{x:d,y:h+k,z:m+l},{x:d+u,y:h+k,z:m+l},{x:d+u,y:h,z:m+l},{x:d,y:h,z:m+l}],g=f(g,p,a.insidePlotArea);n=function(a,d){var f=[[],-1];a=e(a,c);d=e(d,c);0>b.shapeArea(a)?f=[a,0]:0>b.shapeArea(d)&&(f=[d,1]);return f};v=n([3,2,1,0],[7,6,5,4]);a=v[0];u=v[1];v=n([1,6,7,0],[4,5,2,3]);k=v[0];
l=v[1];v=n([1,2,5,6],[0,7,4,3]);n=v[0];v=v[1];1===v?r+=1E4*(1E3-d):v||(r+=1E4*d);r+=10*(!l||0<=q&&180>=q||360>q&&357.5<q?p.plotHeight-h:10+h);1===u?r+=100*m:u||(r+=100*(1E3-m));r=-Math.round(r);return[this.toLinePath(a,!0),this.toLinePath(k,!0),this.toLinePath(n,!0),r]};b.SVGRenderer.prototype.arc3d=function(c){function b(c){var d=!1,e={};c=l(c);for(var b in c)-1!==a(b,m)&&(e[b]=c[b],delete c[b],d=!0);return d?e:!1}var e=this.g(),f=e.renderer,m="x y r innerR start end".split(" ");c=l(c);c.alpha*=
w;c.beta*=w;e.top=f.path();e.side1=f.path();e.side2=f.path();e.inn=f.path();e.out=f.path();e.onAdd=function(){var a=e.parentGroup,c=e.attr("class");e.top.add(e);v(["out","inn","side1","side2"],function(d){e[d].attr({"class":c+" highcharts-3d-side"}).add(a)})};v(["addClass","removeClass"],function(a){e[a]=function(){var c=arguments;v(["top","out","inn","side1","side2"],function(d){e[d][a].apply(e[d],c)})}});e.setPaths=function(a){var c=e.renderer.arc3dPath(a),d=100*c.zTop;e.attribs=a;e.top.attr({d:c.top,
zIndex:c.zTop});e.inn.attr({d:c.inn,zIndex:c.zInn});e.out.attr({d:c.out,zIndex:c.zOut});e.side1.attr({d:c.side1,zIndex:c.zSide1});e.side2.attr({d:c.side2,zIndex:c.zSide2});e.zIndex=d;e.attr({zIndex:d});a.center&&(e.top.setRadialReference(a.center),delete a.center)};e.setPaths(c);e.fillSetter=function(a){var c=n(a).brighten(-.1).get();this.fill=a;this.side1.attr({fill:c});this.side2.attr({fill:c});this.inn.attr({fill:c});this.out.attr({fill:c});this.top.attr({fill:a});return this};v(["opacity","translateX",
"translateY","visibility"],function(a){e[a+"Setter"]=function(a,c){e[c]=a;v(["out","inn","side1","side2","top"],function(d){e[d].attr(c,a)})}});p(e,"attr",function(a,c){var d;"object"===typeof c&&(d=b(c))&&(k(e.attribs,d),e.setPaths(e.attribs));return a.apply(this,[].slice.call(arguments,1))});p(e,"animate",function(a,c,d,f){var k,m=this.attribs,u;delete c.center;delete c.z;delete c.depth;delete c.alpha;delete c.beta;u=y(h(d,this.renderer.globalAnimation));u.duration&&(k=b(c),c.dummy=e.dummy++,k&&
(u.step=function(a,c){function d(a){return m[a]+(h(k[a],m[a])-m[a])*c.pos}"dummy"===c.prop&&c.elem.setPaths(l(m,{x:d("x"),y:d("y"),r:d("r"),innerR:d("innerR"),start:d("start"),end:d("end")}))}),d=u);return a.call(this,c,d,f)});e.dummy=0;e.destroy=function(){this.top.destroy();this.out.destroy();this.inn.destroy();this.side1.destroy();this.side2.destroy();d.prototype.destroy.call(this)};e.hide=function(){this.top.hide();this.out.hide();this.inn.hide();this.side1.hide();this.side2.hide()};e.show=function(){this.top.show();
this.out.show();this.inn.show();this.side1.show();this.side2.show()};return e};c.prototype.arc3dPath=function(a){function c(a){a%=2*Math.PI;a>Math.PI&&(a=2*Math.PI-a);return a}var d=a.x,e=a.y,b=a.start,f=a.end-.00001,h=a.r,k=a.innerR,u=a.depth,m=a.alpha,l=a.beta,p=Math.cos(b),v=Math.sin(b);a=Math.cos(f);var n=Math.sin(f),g=h*Math.cos(l),h=h*Math.cos(m),z=k*Math.cos(l),y=k*Math.cos(m),k=u*Math.sin(l),w=u*Math.sin(m),u=["M",d+g*p,e+h*v],u=u.concat(t(d,e,g,h,b,f,0,0)),u=u.concat(["L",d+z*a,e+y*n]),u=
u.concat(t(d,e,z,y,f,b,0,0)),u=u.concat(["Z"]),A=0<l?Math.PI/2:0,l=0<m?0:Math.PI/2,A=b>-A?b:f>-A?-A:b,C=f<r-l?f:b<r-l?r-l:f,D=2*r-l,m=["M",d+g*x(A),e+h*q(A)],m=m.concat(t(d,e,g,h,A,C,0,0));f>D&&b<D?(m=m.concat(["L",d+g*x(C)+k,e+h*q(C)+w]),m=m.concat(t(d,e,g,h,C,D,k,w)),m=m.concat(["L",d+g*x(D),e+h*q(D)]),m=m.concat(t(d,e,g,h,D,f,0,0)),m=m.concat(["L",d+g*x(f)+k,e+h*q(f)+w]),m=m.concat(t(d,e,g,h,f,D,k,w)),m=m.concat(["L",d+g*x(D),e+h*q(D)]),m=m.concat(t(d,e,g,h,D,C,0,0))):f>r-l&&b<r-l&&(m=m.concat(["L",
d+g*Math.cos(C)+k,e+h*Math.sin(C)+w]),m=m.concat(t(d,e,g,h,C,f,k,w)),m=m.concat(["L",d+g*Math.cos(f),e+h*Math.sin(f)]),m=m.concat(t(d,e,g,h,f,C,0,0)));m=m.concat(["L",d+g*Math.cos(C)+k,e+h*Math.sin(C)+w]);m=m.concat(t(d,e,g,h,C,A,k,w));m=m.concat(["Z"]);l=["M",d+z*p,e+y*v];l=l.concat(t(d,e,z,y,b,f,0,0));l=l.concat(["L",d+z*Math.cos(f)+k,e+y*Math.sin(f)+w]);l=l.concat(t(d,e,z,y,f,b,k,w));l=l.concat(["Z"]);p=["M",d+g*p,e+h*v,"L",d+g*p+k,e+h*v+w,"L",d+z*p+k,e+y*v+w,"L",d+z*p,e+y*v,"Z"];d=["M",d+g*a,
e+h*n,"L",d+g*a+k,e+h*n+w,"L",d+z*a+k,e+y*n+w,"L",d+z*a,e+y*n,"Z"];n=Math.atan2(w,-k);e=Math.abs(f+n);a=Math.abs(b+n);b=Math.abs((b+f)/2+n);e=c(e);a=c(a);b=c(b);b*=1E5;f=1E5*a;e*=1E5;return{top:u,zTop:1E5*Math.PI+1,out:m,zOut:Math.max(b,f,e),inn:l,zInn:Math.max(b,f,e),side1:p,zSide1:.99*e,side2:d,zSide2:.99*f}}})(A);(function(b){function t(b,k){var a=b.plotLeft,e=b.plotWidth+a,l=b.plotTop,f=b.plotHeight+l,h=a+b.plotWidth/2,d=l+b.plotHeight/2,c=Number.MAX_VALUE,p=-Number.MAX_VALUE,u=Number.MAX_VALUE,
m=-Number.MAX_VALUE,v,n=1;v=[{x:a,y:l,z:0},{x:a,y:l,z:k}];q([0,1],function(a){v.push({x:e,y:v[a].y,z:v[a].z})});q([0,1,2,3],function(a){v.push({x:v[a].x,y:f,z:v[a].z})});v=z(v,b,!1);q(v,function(a){c=Math.min(c,a.x);p=Math.max(p,a.x);u=Math.min(u,a.y);m=Math.max(m,a.y)});a>c&&(n=Math.min(n,1-Math.abs((a+h)/(c+h))%1));e<p&&(n=Math.min(n,(e-h)/(p-h)));l>u&&(n=0>u?Math.min(n,(l+d)/(-u+l+d)):Math.min(n,1-(l+d)/(u+d)%1));f<m&&(n=Math.min(n,Math.abs((f-d)/(m-d))));return n}var x=b.addEvent,r=b.Chart,q=
b.each,y=b.merge,z=b.perspective,n=b.pick,g=b.wrap;r.prototype.is3d=function(){return this.options.chart.options3d&&this.options.chart.options3d.enabled};r.prototype.propsRequireDirtyBox.push("chart.options3d");r.prototype.propsRequireUpdateSeries.push("chart.options3d");x(r,"afterInit",function(){var b=this.options;this.is3d()&&q(b.series,function(k){"scatter"===(k.type||b.chart.type||b.chart.defaultSeriesType)&&(k.type="scatter3d")})});b.wrap(b.Chart.prototype,"isInsidePlot",function(b){return this.is3d()||
b.apply(this,[].slice.call(arguments,1))});var w=b.getOptions();y(!0,w,{chart:{options3d:{enabled:!1,alpha:0,beta:0,depth:100,fitToPlot:!0,viewDistance:25,axisLabelPosition:"default",frame:{visible:"default",size:1,bottom:{},top:{},left:{},right:{},back:{},front:{}}}}});g(r.prototype,"setClassName",function(b){b.apply(this,[].slice.call(arguments,1));this.is3d()&&(this.container.className+=" highcharts-3d-chart")});x(b.Chart,"afterSetChartSize",function(){var b=this.options.chart.options3d;if(this.is3d()){var k=
this.inverted,a=this.clipBox,e=this.margin;a[k?"y":"x"]=-(e[3]||0);a[k?"x":"y"]=-(e[0]||0);a[k?"height":"width"]=this.chartWidth+(e[3]||0)+(e[1]||0);a[k?"width":"height"]=this.chartHeight+(e[0]||0)+(e[2]||0);this.scale3d=1;!0===b.fitToPlot&&(this.scale3d=t(this,b.depth));this.frame3d=this.get3dFrame()}});x(r,"beforeRedraw",function(){this.is3d()&&(this.isDirtyBox=!0)});x(r,"beforeRender",function(){this.is3d()&&(this.frame3d=this.get3dFrame())});g(r.prototype,"renderSeries",function(b){var k=this.series.length;
if(this.is3d())for(;k--;)b=this.series[k],b.translate(),b.render();else b.call(this)});x(r,"afterDrawChartBox",function(){if(this.is3d()){var n=this.renderer,k=this.options.chart.options3d,a=this.get3dFrame(),e=this.plotLeft,l=this.plotLeft+this.plotWidth,f=this.plotTop,h=this.plotTop+this.plotHeight,k=k.depth,d=e-(a.left.visible?a.left.size:0),c=l+(a.right.visible?a.right.size:0),p=f-(a.top.visible?a.top.size:0),u=h+(a.bottom.visible?a.bottom.size:0),m=0-(a.front.visible?a.front.size:0),g=k+(a.back.visible?
a.back.size:0),q=this.hasRendered?"animate":"attr";this.frame3d=a;this.frameShapes||(this.frameShapes={bottom:n.polyhedron().add(),top:n.polyhedron().add(),left:n.polyhedron().add(),right:n.polyhedron().add(),back:n.polyhedron().add(),front:n.polyhedron().add()});this.frameShapes.bottom[q]({"class":"highcharts-3d-frame highcharts-3d-frame-bottom",zIndex:a.bottom.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.bottom.color).brighten(.1).get(),vertexes:[{x:d,y:u,z:m},{x:c,y:u,z:m},{x:c,y:u,z:g},{x:d,y:u,
z:g}],enabled:a.bottom.visible},{fill:b.color(a.bottom.color).brighten(.1).get(),vertexes:[{x:e,y:h,z:k},{x:l,y:h,z:k},{x:l,y:h,z:0},{x:e,y:h,z:0}],enabled:a.bottom.visible},{fill:b.color(a.bottom.color).brighten(-.1).get(),vertexes:[{x:d,y:u,z:m},{x:d,y:u,z:g},{x:e,y:h,z:k},{x:e,y:h,z:0}],enabled:a.bottom.visible&&!a.left.visible},{fill:b.color(a.bottom.color).brighten(-.1).get(),vertexes:[{x:c,y:u,z:g},{x:c,y:u,z:m},{x:l,y:h,z:0},{x:l,y:h,z:k}],enabled:a.bottom.visible&&!a.right.visible},{fill:b.color(a.bottom.color).get(),
vertexes:[{x:c,y:u,z:m},{x:d,y:u,z:m},{x:e,y:h,z:0},{x:l,y:h,z:0}],enabled:a.bottom.visible&&!a.front.visible},{fill:b.color(a.bottom.color).get(),vertexes:[{x:d,y:u,z:g},{x:c,y:u,z:g},{x:l,y:h,z:k},{x:e,y:h,z:k}],enabled:a.bottom.visible&&!a.back.visible}]});this.frameShapes.top[q]({"class":"highcharts-3d-frame highcharts-3d-frame-top",zIndex:a.top.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.top.color).brighten(.1).get(),vertexes:[{x:d,y:p,z:g},{x:c,y:p,z:g},{x:c,y:p,z:m},{x:d,y:p,z:m}],enabled:a.top.visible},
{fill:b.color(a.top.color).brighten(.1).get(),vertexes:[{x:e,y:f,z:0},{x:l,y:f,z:0},{x:l,y:f,z:k},{x:e,y:f,z:k}],enabled:a.top.visible},{fill:b.color(a.top.color).brighten(-.1).get(),vertexes:[{x:d,y:p,z:g},{x:d,y:p,z:m},{x:e,y:f,z:0},{x:e,y:f,z:k}],enabled:a.top.visible&&!a.left.visible},{fill:b.color(a.top.color).brighten(-.1).get(),vertexes:[{x:c,y:p,z:m},{x:c,y:p,z:g},{x:l,y:f,z:k},{x:l,y:f,z:0}],enabled:a.top.visible&&!a.right.visible},{fill:b.color(a.top.color).get(),vertexes:[{x:d,y:p,z:m},
{x:c,y:p,z:m},{x:l,y:f,z:0},{x:e,y:f,z:0}],enabled:a.top.visible&&!a.front.visible},{fill:b.color(a.top.color).get(),vertexes:[{x:c,y:p,z:g},{x:d,y:p,z:g},{x:e,y:f,z:k},{x:l,y:f,z:k}],enabled:a.top.visible&&!a.back.visible}]});this.frameShapes.left[q]({"class":"highcharts-3d-frame highcharts-3d-frame-left",zIndex:a.left.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.left.color).brighten(.1).get(),vertexes:[{x:d,y:u,z:m},{x:e,y:h,z:0},{x:e,y:h,z:k},{x:d,y:u,z:g}],enabled:a.left.visible&&!a.bottom.visible},
{fill:b.color(a.left.color).brighten(.1).get(),vertexes:[{x:d,y:p,z:g},{x:e,y:f,z:k},{x:e,y:f,z:0},{x:d,y:p,z:m}],enabled:a.left.visible&&!a.top.visible},{fill:b.color(a.left.color).brighten(-.1).get(),vertexes:[{x:d,y:u,z:g},{x:d,y:p,z:g},{x:d,y:p,z:m},{x:d,y:u,z:m}],enabled:a.left.visible},{fill:b.color(a.left.color).brighten(-.1).get(),vertexes:[{x:e,y:f,z:k},{x:e,y:h,z:k},{x:e,y:h,z:0},{x:e,y:f,z:0}],enabled:a.left.visible},{fill:b.color(a.left.color).get(),vertexes:[{x:d,y:u,z:m},{x:d,y:p,z:m},
{x:e,y:f,z:0},{x:e,y:h,z:0}],enabled:a.left.visible&&!a.front.visible},{fill:b.color(a.left.color).get(),vertexes:[{x:d,y:p,z:g},{x:d,y:u,z:g},{x:e,y:h,z:k},{x:e,y:f,z:k}],enabled:a.left.visible&&!a.back.visible}]});this.frameShapes.right[q]({"class":"highcharts-3d-frame highcharts-3d-frame-right",zIndex:a.right.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.right.color).brighten(.1).get(),vertexes:[{x:c,y:u,z:g},{x:l,y:h,z:k},{x:l,y:h,z:0},{x:c,y:u,z:m}],enabled:a.right.visible&&!a.bottom.visible},
{fill:b.color(a.right.color).brighten(.1).get(),vertexes:[{x:c,y:p,z:m},{x:l,y:f,z:0},{x:l,y:f,z:k},{x:c,y:p,z:g}],enabled:a.right.visible&&!a.top.visible},{fill:b.color(a.right.color).brighten(-.1).get(),vertexes:[{x:l,y:f,z:0},{x:l,y:h,z:0},{x:l,y:h,z:k},{x:l,y:f,z:k}],enabled:a.right.visible},{fill:b.color(a.right.color).brighten(-.1).get(),vertexes:[{x:c,y:u,z:m},{x:c,y:p,z:m},{x:c,y:p,z:g},{x:c,y:u,z:g}],enabled:a.right.visible},{fill:b.color(a.right.color).get(),vertexes:[{x:c,y:p,z:m},{x:c,
y:u,z:m},{x:l,y:h,z:0},{x:l,y:f,z:0}],enabled:a.right.visible&&!a.front.visible},{fill:b.color(a.right.color).get(),vertexes:[{x:c,y:u,z:g},{x:c,y:p,z:g},{x:l,y:f,z:k},{x:l,y:h,z:k}],enabled:a.right.visible&&!a.back.visible}]});this.frameShapes.back[q]({"class":"highcharts-3d-frame highcharts-3d-frame-back",zIndex:a.back.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.back.color).brighten(.1).get(),vertexes:[{x:c,y:u,z:g},{x:d,y:u,z:g},{x:e,y:h,z:k},{x:l,y:h,z:k}],enabled:a.back.visible&&!a.bottom.visible},
{fill:b.color(a.back.color).brighten(.1).get(),vertexes:[{x:d,y:p,z:g},{x:c,y:p,z:g},{x:l,y:f,z:k},{x:e,y:f,z:k}],enabled:a.back.visible&&!a.top.visible},{fill:b.color(a.back.color).brighten(-.1).get(),vertexes:[{x:d,y:u,z:g},{x:d,y:p,z:g},{x:e,y:f,z:k},{x:e,y:h,z:k}],enabled:a.back.visible&&!a.left.visible},{fill:b.color(a.back.color).brighten(-.1).get(),vertexes:[{x:c,y:p,z:g},{x:c,y:u,z:g},{x:l,y:h,z:k},{x:l,y:f,z:k}],enabled:a.back.visible&&!a.right.visible},{fill:b.color(a.back.color).get(),
vertexes:[{x:e,y:f,z:k},{x:l,y:f,z:k},{x:l,y:h,z:k},{x:e,y:h,z:k}],enabled:a.back.visible},{fill:b.color(a.back.color).get(),vertexes:[{x:d,y:u,z:g},{x:c,y:u,z:g},{x:c,y:p,z:g},{x:d,y:p,z:g}],enabled:a.back.visible}]});this.frameShapes.front[q]({"class":"highcharts-3d-frame highcharts-3d-frame-front",zIndex:a.front.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.front.color).brighten(.1).get(),vertexes:[{x:d,y:u,z:m},{x:c,y:u,z:m},{x:l,y:h,z:0},{x:e,y:h,z:0}],enabled:a.front.visible&&!a.bottom.visible},
{fill:b.color(a.front.color).brighten(.1).get(),vertexes:[{x:c,y:p,z:m},{x:d,y:p,z:m},{x:e,y:f,z:0},{x:l,y:f,z:0}],enabled:a.front.visible&&!a.top.visible},{fill:b.color(a.front.color).brighten(-.1).get(),vertexes:[{x:d,y:p,z:m},{x:d,y:u,z:m},{x:e,y:h,z:0},{x:e,y:f,z:0}],enabled:a.front.visible&&!a.left.visible},{fill:b.color(a.front.color).brighten(-.1).get(),vertexes:[{x:c,y:u,z:m},{x:c,y:p,z:m},{x:l,y:f,z:0},{x:l,y:h,z:0}],enabled:a.front.visible&&!a.right.visible},{fill:b.color(a.front.color).get(),
vertexes:[{x:l,y:f,z:0},{x:e,y:f,z:0},{x:e,y:h,z:0},{x:l,y:h,z:0}],enabled:a.front.visible},{fill:b.color(a.front.color).get(),vertexes:[{x:c,y:u,z:m},{x:d,y:u,z:m},{x:d,y:p,z:m},{x:c,y:p,z:m}],enabled:a.front.visible}]})}});r.prototype.retrieveStacks=function(b){var k=this.series,a={},e,l=1;q(this.series,function(f){e=n(f.options.stack,b?0:k.length-1-f.index);a[e]?a[e].series.push(f):(a[e]={series:[f],position:l},l++)});a.totalStacks=l+1;return a};r.prototype.get3dFrame=function(){var g=this,k=g.options.chart.options3d,
a=k.frame,e=g.plotLeft,l=g.plotLeft+g.plotWidth,f=g.plotTop,h=g.plotTop+g.plotHeight,d=k.depth,c=function(a){a=b.shapeArea3d(a,g);return.5<a?1:-.5>a?-1:0},p=c([{x:e,y:h,z:d},{x:l,y:h,z:d},{x:l,y:h,z:0},{x:e,y:h,z:0}]),u=c([{x:e,y:f,z:0},{x:l,y:f,z:0},{x:l,y:f,z:d},{x:e,y:f,z:d}]),m=c([{x:e,y:f,z:0},{x:e,y:f,z:d},{x:e,y:h,z:d},{x:e,y:h,z:0}]),r=c([{x:l,y:f,z:d},{x:l,y:f,z:0},{x:l,y:h,z:0},{x:l,y:h,z:d}]),y=c([{x:e,y:h,z:0},{x:l,y:h,z:0},{x:l,y:f,z:0},{x:e,y:f,z:0}]),c=c([{x:e,y:f,z:d},{x:l,y:f,z:d},
{x:l,y:h,z:d},{x:e,y:h,z:d}]),w=!1,t=!1,x=!1,A=!1;q([].concat(g.xAxis,g.yAxis,g.zAxis),function(a){a&&(a.horiz?a.opposite?t=!0:w=!0:a.opposite?A=!0:x=!0)});var E=function(a,c,d){for(var e=["size","color","visible"],b={},f=0;f<e.length;f++)for(var h=e[f],m=0;m<a.length;m++)if("object"===typeof a[m]){var k=a[m][h];if(void 0!==k&&null!==k){b[h]=k;break}}a=d;!0===b.visible||!1===b.visible?a=b.visible:"auto"===b.visible&&(a=0<c);return{size:n(b.size,1),color:n(b.color,"none"),frontFacing:0<c,visible:a}},
a={bottom:E([a.bottom,a.top,a],p,w),top:E([a.top,a.bottom,a],u,t),left:E([a.left,a.right,a.side,a],m,x),right:E([a.right,a.left,a.side,a],r,A),back:E([a.back,a.front,a],c,!0),front:E([a.front,a.back,a],y,!1)};"auto"===k.axisLabelPosition?(r=function(a,c){return a.visible!==c.visible||a.visible&&c.visible&&a.frontFacing!==c.frontFacing},k=[],r(a.left,a.front)&&k.push({y:(f+h)/2,x:e,z:0,xDir:{x:1,y:0,z:0}}),r(a.left,a.back)&&k.push({y:(f+h)/2,x:e,z:d,xDir:{x:0,y:0,z:-1}}),r(a.right,a.front)&&k.push({y:(f+
h)/2,x:l,z:0,xDir:{x:0,y:0,z:1}}),r(a.right,a.back)&&k.push({y:(f+h)/2,x:l,z:d,xDir:{x:-1,y:0,z:0}}),p=[],r(a.bottom,a.front)&&p.push({x:(e+l)/2,y:h,z:0,xDir:{x:1,y:0,z:0}}),r(a.bottom,a.back)&&p.push({x:(e+l)/2,y:h,z:d,xDir:{x:-1,y:0,z:0}}),u=[],r(a.top,a.front)&&u.push({x:(e+l)/2,y:f,z:0,xDir:{x:1,y:0,z:0}}),r(a.top,a.back)&&u.push({x:(e+l)/2,y:f,z:d,xDir:{x:-1,y:0,z:0}}),m=[],r(a.bottom,a.left)&&m.push({z:(0+d)/2,y:h,x:e,xDir:{x:0,y:0,z:-1}}),r(a.bottom,a.right)&&m.push({z:(0+d)/2,y:h,x:l,xDir:{x:0,
y:0,z:1}}),h=[],r(a.top,a.left)&&h.push({z:(0+d)/2,y:f,x:e,xDir:{x:0,y:0,z:-1}}),r(a.top,a.right)&&h.push({z:(0+d)/2,y:f,x:l,xDir:{x:0,y:0,z:1}}),e=function(a,c,d){if(0===a.length)return null;if(1===a.length)return a[0];for(var b=0,e=z(a,g,!1),f=1;f<e.length;f++)d*e[f][c]>d*e[b][c]?b=f:d*e[f][c]===d*e[b][c]&&e[f].z<e[b].z&&(b=f);return a[b]},a.axes={y:{left:e(k,"x",-1),right:e(k,"x",1)},x:{top:e(u,"y",-1),bottom:e(p,"y",1)},z:{top:e(h,"y",-1),bottom:e(m,"y",1)}}):a.axes={y:{left:{x:e,z:0,xDir:{x:1,
y:0,z:0}},right:{x:l,z:0,xDir:{x:0,y:0,z:1}}},x:{top:{y:f,z:0,xDir:{x:1,y:0,z:0}},bottom:{y:h,z:0,xDir:{x:1,y:0,z:0}}},z:{top:{x:x?l:e,y:f,xDir:x?{x:0,y:0,z:1}:{x:0,y:0,z:-1}},bottom:{x:x?l:e,y:h,xDir:x?{x:0,y:0,z:1}:{x:0,y:0,z:-1}}}};return a};b.Fx.prototype.matrixSetter=function(){var g;if(1>this.pos&&(b.isArray(this.start)||b.isArray(this.end))){var k=this.start||[1,0,0,1,0,0],a=this.end||[1,0,0,1,0,0];g=[];for(var e=0;6>e;e++)g.push(this.pos*a[e]+(1-this.pos)*k[e])}else g=this.end;this.elem.attr(this.prop,
g,null,!0)}})(A);(function(b){function t(d,c,b){if(!d.chart.is3d()||"colorAxis"===d.coll)return c;var f=d.chart,h=z*f.options.chart.options3d.alpha,k=z*f.options.chart.options3d.beta,l=a(b&&d.options.title.position3d,d.options.labels.position3d);b=a(b&&d.options.title.skew3d,d.options.labels.skew3d);var g=f.frame3d,p=f.plotLeft,n=f.plotWidth+p,q=f.plotTop,r=f.plotHeight+q,f=!1,w=0,y=0,t={x:0,y:1,z:0};c=d.swapZ({x:c.x,y:c.y,z:0});if(d.isZAxis)if(d.opposite){if(null===g.axes.z.top)return{};y=c.y-q;
c.x=g.axes.z.top.x;c.y=g.axes.z.top.y;p=g.axes.z.top.xDir;f=!g.top.frontFacing}else{if(null===g.axes.z.bottom)return{};y=c.y-r;c.x=g.axes.z.bottom.x;c.y=g.axes.z.bottom.y;p=g.axes.z.bottom.xDir;f=!g.bottom.frontFacing}else if(d.horiz)if(d.opposite){if(null===g.axes.x.top)return{};y=c.y-q;c.y=g.axes.x.top.y;c.z=g.axes.x.top.z;p=g.axes.x.top.xDir;f=!g.top.frontFacing}else{if(null===g.axes.x.bottom)return{};y=c.y-r;c.y=g.axes.x.bottom.y;c.z=g.axes.x.bottom.z;p=g.axes.x.bottom.xDir;f=!g.bottom.frontFacing}else if(d.opposite){if(null===
g.axes.y.right)return{};w=c.x-n;c.x=g.axes.y.right.x;c.z=g.axes.y.right.z;p=g.axes.y.right.xDir;p={x:p.z,y:p.y,z:-p.x}}else{if(null===g.axes.y.left)return{};w=c.x-p;c.x=g.axes.y.left.x;c.z=g.axes.y.left.z;p=g.axes.y.left.xDir}"chart"!==l&&("flap"===l?d.horiz?(k=Math.sin(h),h=Math.cos(h),d.opposite&&(k=-k),f&&(k=-k),t={x:p.z*k,y:h,z:-p.x*k}):p={x:Math.cos(k),y:0,z:Math.sin(k)}:"ortho"===l?d.horiz?(t=Math.cos(h),l=Math.sin(k)*t,h=-Math.sin(h),k=-t*Math.cos(k),t={x:p.y*k-p.z*h,y:p.z*l-p.x*k,z:p.x*h-
p.y*l},h=1/Math.sqrt(t.x*t.x+t.y*t.y+t.z*t.z),f&&(h=-h),t={x:h*t.x,y:h*t.y,z:h*t.z}):p={x:Math.cos(k),y:0,z:Math.sin(k)}:d.horiz?t={x:Math.sin(k)*Math.sin(h),y:Math.cos(h),z:-Math.cos(k)*Math.sin(h)}:p={x:Math.cos(k),y:0,z:Math.sin(k)});c.x+=w*p.x+y*t.x;c.y+=w*p.y+y*t.y;c.z+=w*p.z+y*t.z;f=v([c],d.chart)[0];b?(0>e(v([c,{x:c.x+p.x,y:c.y+p.y,z:c.z+p.z},{x:c.x+t.x,y:c.y+t.y,z:c.z+t.z}],d.chart))&&(p={x:-p.x,y:-p.y,z:-p.z}),d=v([{x:c.x,y:c.y,z:c.z},{x:c.x+p.x,y:c.y+p.y,z:c.z+p.z},{x:c.x+t.x,y:c.y+t.y,
z:c.z+t.z}],d.chart),f.matrix=[d[1].x-d[0].x,d[1].y-d[0].y,d[2].x-d[0].x,d[2].y-d[0].y,f.x,f.y],f.matrix[4]-=f.x*f.matrix[0]+f.y*f.matrix[2],f.matrix[5]-=f.x*f.matrix[1]+f.y*f.matrix[3]):f.matrix=null;return f}var x,r=b.addEvent,q=b.Axis,y=b.Chart,z=b.deg2rad,n=b.each,g=b.extend,w=b.merge,v=b.perspective,k=b.perspective3D,a=b.pick,e=b.shapeArea,l=b.splat,f=b.Tick,h=b.wrap;w(!0,q.prototype.defaultOptions,{labels:{position3d:"offset",skew3d:!1},title:{position3d:null,skew3d:null}});r(q,"afterSetOptions",
function(){var d;this.chart.is3d&&this.chart.is3d()&&"colorAxis"!==this.coll&&(d=this.options,d.tickWidth=a(d.tickWidth,0),d.gridLineWidth=a(d.gridLineWidth,1))});h(q.prototype,"getPlotLinePath",function(a){var c=a.apply(this,[].slice.call(arguments,1));if(!this.chart.is3d()||"colorAxis"===this.coll||null===c)return c;var d=this.chart,b=d.options.chart.options3d,b=this.isZAxis?d.plotWidth:b.depth,d=d.frame3d,c=[this.swapZ({x:c[1],y:c[2],z:0}),this.swapZ({x:c[1],y:c[2],z:b}),this.swapZ({x:c[4],y:c[5],
z:0}),this.swapZ({x:c[4],y:c[5],z:b})],b=[];this.horiz?(this.isZAxis?(d.left.visible&&b.push(c[0],c[2]),d.right.visible&&b.push(c[1],c[3])):(d.front.visible&&b.push(c[0],c[2]),d.back.visible&&b.push(c[1],c[3])),d.top.visible&&b.push(c[0],c[1]),d.bottom.visible&&b.push(c[2],c[3])):(d.front.visible&&b.push(c[0],c[2]),d.back.visible&&b.push(c[1],c[3]),d.left.visible&&b.push(c[0],c[1]),d.right.visible&&b.push(c[2],c[3]));b=v(b,this.chart,!1);return this.chart.renderer.toLineSegments(b)});h(q.prototype,
"getLinePath",function(a){return this.chart.is3d()&&"colorAxis"!==this.coll?[]:a.apply(this,[].slice.call(arguments,1))});h(q.prototype,"getPlotBandPath",function(a){if(!this.chart.is3d()||"colorAxis"===this.coll)return a.apply(this,[].slice.call(arguments,1));var c=arguments,d=c[2],b=[],c=this.getPlotLinePath(c[1]),d=this.getPlotLinePath(d);if(c&&d)for(var e=0;e<c.length;e+=6)b.push("M",c[e+1],c[e+2],"L",c[e+4],c[e+5],"L",d[e+4],d[e+5],"L",d[e+1],d[e+2],"Z");return b});h(f.prototype,"getMarkPath",
function(a){var c=a.apply(this,[].slice.call(arguments,1)),c=[t(this.axis,{x:c[1],y:c[2],z:0}),t(this.axis,{x:c[4],y:c[5],z:0})];return this.axis.chart.renderer.toLineSegments(c)});r(f,"afterGetLabelPosition",function(a){g(a.pos,t(this.axis,a.pos))});h(q.prototype,"getTitlePosition",function(a){var c=a.apply(this,[].slice.call(arguments,1));return t(this,c,!0)});r(q,"drawCrosshair",function(a){this.chart.is3d()&&"colorAxis"!==this.coll&&a.point&&(a.point.crosshairPos=this.isXAxis?a.point.axisXpos:
this.len-a.point.axisYpos)});r(q,"destroy",function(){n(["backFrame","bottomFrame","sideFrame"],function(a){this[a]&&(this[a]=this[a].destroy())},this)});q.prototype.swapZ=function(a,c){return this.isZAxis?(c=c?0:this.chart.plotLeft,{x:c+a.z,y:a.y,z:a.x-c}):a};x=b.ZAxis=function(){this.init.apply(this,arguments)};g(x.prototype,q.prototype);g(x.prototype,{isZAxis:!0,setOptions:function(a){a=w({offset:0,lineWidth:0},a);q.prototype.setOptions.call(this,a);this.coll="zAxis"},setAxisSize:function(){q.prototype.setAxisSize.call(this);
this.width=this.len=this.chart.options.chart.options3d.depth;this.right=this.chart.chartWidth-this.width-this.left},getSeriesExtremes:function(){var d=this,c=d.chart;d.hasVisibleSeries=!1;d.dataMin=d.dataMax=d.ignoreMinPadding=d.ignoreMaxPadding=null;d.buildStacks&&d.buildStacks();n(d.series,function(b){if(b.visible||!c.options.chart.ignoreHiddenSeries)d.hasVisibleSeries=!0,b=b.zData,b.length&&(d.dataMin=Math.min(a(d.dataMin,b[0]),Math.min.apply(null,b)),d.dataMax=Math.max(a(d.dataMax,b[0]),Math.max.apply(null,
b)))})}});r(y,"afterGetAxes",function(){var a=this,c=this.options,c=c.zAxis=l(c.zAxis||{});a.is3d()&&(this.zAxis=[],n(c,function(c,b){c.index=b;c.isX=!0;(new x(a,c)).setScale()}))});h(q.prototype,"getSlotWidth",function(b,c){if(this.chart.is3d()&&c&&c.label&&this.categories){var d=this.chart,e=this.ticks,f=this.gridGroup.element.getBBox(),h=d.options.chart.options3d,d={x:d.plotWidth/2,y:d.plotHeight/2,z:h.depth/2,vd:a(h.depth,1)*a(h.viewDistance,0)},g,h=c.pos,e=e[h-1];0!==h&&e&&(g=k({x:e.label.xy.x,
y:e.label.xy.y,z:null},d,d.vd));e={x:c.label.xy.x,y:c.label.xy.y,z:null};e=k(e,d,d.vd);return g?e.x-g.x:f.x-e.x}return b.apply(this,[].slice.call(arguments,1))})})(A);(function(b){var t=b.addEvent,x=b.perspective,r=b.pick;t(b.Series,"afterTranslate",function(){this.chart.is3d()&&this.translate3dPoints()});b.Series.prototype.translate3dPoints=function(){var b=this.chart,t=r(this.zAxis,b.options.zAxis[0]),z=[],n,g,w;for(w=0;w<this.data.length;w++)n=this.data[w],t&&t.translate?(g=t.isLog&&t.val2lin?
t.val2lin(n.z):n.z,n.plotZ=t.translate(g),n.isInside=n.isInside?g>=t.min&&g<=t.max:!1):n.plotZ=0,n.axisXpos=n.plotX,n.axisYpos=n.plotY,n.axisZpos=n.plotZ,z.push({x:n.plotX,y:n.plotY,z:n.plotZ});b=x(z,b,!0);for(w=0;w<this.data.length;w++)n=this.data[w],t=b[w],n.plotX=t.x,n.plotY=t.y,n.plotZ=t.z}})(A);(function(b){function t(b){var a=b.apply(this,[].slice.call(arguments,1));this.chart.is3d&&this.chart.is3d()&&(a.stroke=this.options.edgeColor||a.fill,a["stroke-width"]=y(this.options.edgeWidth,1));return a}
var x=b.addEvent,r=b.each,q=b.perspective,y=b.pick,z=b.Series,n=b.seriesTypes,g=b.inArray,w=b.svg,v=b.wrap;v(n.column.prototype,"translate",function(b){b.apply(this,[].slice.call(arguments,1));this.chart.is3d()&&this.translate3dShapes()});v(b.Series.prototype,"alignDataLabel",function(b){arguments[3].outside3dPlot=arguments[1].outside3dPlot;b.apply(this,[].slice.call(arguments,1))});v(b.Series.prototype,"justifyDataLabel",function(b){return arguments[2].outside3dPlot?!1:b.apply(this,[].slice.call(arguments,
1))});n.column.prototype.translate3dPoints=function(){};n.column.prototype.translate3dShapes=function(){var b=this,a=b.chart,e=b.options,g=e.depth||25,f=(e.stacking?e.stack||0:b.index)*(g+(e.groupZPadding||1)),h=b.borderWidth%2?.5:0;a.inverted&&!b.yAxis.reversed&&(h*=-1);!1!==e.grouping&&(f=0);f+=e.groupZPadding||1;r(b.data,function(d){d.outside3dPlot=null;if(null!==d.y){var c=d.shapeArgs,e=d.tooltipPos,k;r([["x","width"],["y","height"]],function(a){k=c[a[0]]-h;0>k&&(c[a[1]]+=c[a[0]]+h,c[a[0]]=-h,
k=0);k+c[a[1]]>b[a[0]+"Axis"].len&&0!==c[a[1]]&&(c[a[1]]=b[a[0]+"Axis"].len-c[a[0]]);if(0!==c[a[1]]&&(c[a[0]]>=b[a[0]+"Axis"].len||c[a[0]]+c[a[1]]<=h)){for(var e in c)c[e]=0;d.outside3dPlot=!0}});d.shapeType="cuboid";c.z=f;c.depth=g;c.insidePlotArea=!0;e=q([{x:e[0],y:e[1],z:f}],a,!0)[0];d.tooltipPos=[e.x,e.y]}});b.z=f};v(n.column.prototype,"animate",function(b){if(this.chart.is3d()){var a=arguments[1],e=this.yAxis,g=this,f=this.yAxis.reversed;w&&(a?r(g.data,function(a){null!==a.y&&(a.height=a.shapeArgs.height,
a.shapey=a.shapeArgs.y,a.shapeArgs.height=1,f||(a.shapeArgs.y=a.stackY?a.plotY+e.translate(a.stackY):a.plotY+(a.negative?-a.height:a.height)))}):(r(g.data,function(a){null!==a.y&&(a.shapeArgs.height=a.height,a.shapeArgs.y=a.shapey,a.graphic&&a.graphic.animate(a.shapeArgs,g.options.animation))}),this.drawDataLabels(),g.animate=null))}else b.apply(this,[].slice.call(arguments,1))});v(n.column.prototype,"plotGroup",function(b,a,e,g,f,h){this.chart.is3d()&&h&&!this[a]&&(this.chart.columnGroup||(this.chart.columnGroup=
this.chart.renderer.g("columnGroup").add(h)),this[a]=this.chart.columnGroup,this.chart.columnGroup.attr(this.getPlotBox()),this[a].survive=!0);return b.apply(this,Array.prototype.slice.call(arguments,1))});v(n.column.prototype,"setVisible",function(b,a){var e=this,k;e.chart.is3d()&&r(e.data,function(b){k=(b.visible=b.options.visible=a=void 0===a?!b.visible:a)?"visible":"hidden";e.options.data[g(b,e.data)]=b.options;b.graphic&&b.graphic.attr({visibility:k})});b.apply(this,Array.prototype.slice.call(arguments,
1))});n.column.prototype.handle3dGrouping=!0;x(z,"afterInit",function(){if(this.chart.is3d()&&this.handle3dGrouping){var b=this.options,a=b.grouping,e=b.stacking,g=y(this.yAxis.options.reversedStacks,!0),f=0;if(void 0===a||a){a=this.chart.retrieveStacks(e);f=b.stack||0;for(e=0;e<a[f].series.length&&a[f].series[e]!==this;e++);f=10*(a.totalStacks-a[f].position)+(g?e:-e);this.xAxis.reversed||(f=10*a.totalStacks-f)}b.zIndex=f}});v(n.column.prototype,"pointAttribs",t);n.columnrange&&(v(n.columnrange.prototype,
"pointAttribs",t),n.columnrange.prototype.plotGroup=n.column.prototype.plotGroup,n.columnrange.prototype.setVisible=n.column.prototype.setVisible);v(z.prototype,"alignDataLabel",function(b){if(this.chart.is3d()&&("column"===this.type||"columnrange"===this.type)){var a=arguments,e=a[4],a=a[1],g={x:e.x,y:e.y,z:this.z},g=q([g],this.chart,!0)[0];e.x=g.x;e.y=a.outside3dPlot?-9E9:g.y}b.apply(this,[].slice.call(arguments,1))});v(b.StackItem.prototype,"getStackBox",function(g,a){var e=g.apply(this,[].slice.call(arguments,
1));if(a.is3d()){var k={x:e.x,y:e.y,z:0},k=b.perspective([k],a,!0)[0];e.x=k.x;e.y=k.y}return e})})(A);(function(b){var t=b.deg2rad,x=b.each,r=b.pick,q=b.seriesTypes,y=b.svg;b=b.wrap;b(q.pie.prototype,"translate",function(b){b.apply(this,[].slice.call(arguments,1));if(this.chart.is3d()){var n=this,g=n.options,r=g.depth||0,q=n.chart.options.chart.options3d,k=q.alpha,a=q.beta,e=g.stacking?(g.stack||0)*r:n._i*r,e=e+r/2;!1!==g.grouping&&(e=0);x(n.data,function(b){var f=b.shapeArgs;b.shapeType="arc3d";
f.z=e;f.depth=.75*r;f.alpha=k;f.beta=a;f.center=n.center;f=(f.end+f.start)/2;b.slicedTranslation={translateX:Math.round(Math.cos(f)*g.slicedOffset*Math.cos(k*t)),translateY:Math.round(Math.sin(f)*g.slicedOffset*Math.cos(k*t))}})}});b(q.pie.prototype.pointClass.prototype,"haloPath",function(b){var n=arguments;return this.series.chart.is3d()?[]:b.call(this,n[1])});b(q.pie.prototype,"pointAttribs",function(b,n,g){b=b.call(this,n,g);g=this.options;this.chart.is3d()&&(b.stroke=g.edgeColor||n.color||this.color,
b["stroke-width"]=r(g.edgeWidth,1));return b});b(q.pie.prototype,"drawPoints",function(b){b.apply(this,[].slice.call(arguments,1));this.chart.is3d()&&x(this.points,function(b){var g=b.graphic;if(g)g[b.y&&b.visible?"show":"hide"]()})});b(q.pie.prototype,"drawDataLabels",function(b){if(this.chart.is3d()){var n=this.chart.options.chart.options3d;x(this.data,function(b){var g=b.shapeArgs,r=g.r,k=(g.start+g.end)/2,a=b.labelPos,e=-r*(1-Math.cos((g.alpha||n.alpha)*t))*Math.sin(k),l=r*(Math.cos((g.beta||
n.beta)*t)-1)*Math.cos(k);x([0,2,4],function(b){a[b]+=l;a[b+1]+=e})})}b.apply(this,[].slice.call(arguments,1))});b(q.pie.prototype,"addPoint",function(b){b.apply(this,[].slice.call(arguments,1));this.chart.is3d()&&this.update(this.userOptions,!0)});b(q.pie.prototype,"animate",function(b){if(this.chart.is3d()){var n=arguments[1],g=this.options.animation,r=this.center,q=this.group,k=this.markerGroup;y&&(!0===g&&(g={}),n?(q.oldtranslateX=q.translateX,q.oldtranslateY=q.translateY,n={translateX:r[0],translateY:r[1],
scaleX:.001,scaleY:.001},q.attr(n),k&&(k.attrSetters=q.attrSetters,k.attr(n))):(n={translateX:q.oldtranslateX,translateY:q.oldtranslateY,scaleX:1,scaleY:1},q.animate(n,g),k&&k.animate(n,g),this.animate=null))}else b.apply(this,[].slice.call(arguments,1))})})(A);(function(b){var t=b.Point,x=b.seriesType,r=b.seriesTypes;x("scatter3d","scatter",{tooltip:{pointFormat:"x: \x3cb\x3e{point.x}\x3c/b\x3e\x3cbr/\x3ey: \x3cb\x3e{point.y}\x3c/b\x3e\x3cbr/\x3ez: \x3cb\x3e{point.z}\x3c/b\x3e\x3cbr/\x3e"}},{pointAttribs:function(q){var t=
r.scatter.prototype.pointAttribs.apply(this,arguments);this.chart.is3d()&&q&&(t.zIndex=b.pointCameraDistance(q,this.chart));return t},axisTypes:["xAxis","yAxis","zAxis"],pointArrayMap:["x","y","z"],parallelArrays:["x","y","z"],directTouch:!0},{applyOptions:function(){t.prototype.applyOptions.apply(this,arguments);void 0===this.z&&(this.z=0);return this}})})(A);(function(b){var t=b.addEvent,x=b.Axis,r=b.SVGRenderer,q=b.VMLRenderer;q&&(b.setOptions({animate:!1}),q.prototype.face3d=r.prototype.face3d,
q.prototype.polyhedron=r.prototype.polyhedron,q.prototype.cuboid=r.prototype.cuboid,q.prototype.cuboidPath=r.prototype.cuboidPath,q.prototype.toLinePath=r.prototype.toLinePath,q.prototype.toLineSegments=r.prototype.toLineSegments,q.prototype.createElement3D=r.prototype.createElement3D,q.prototype.arc3d=function(b){b=r.prototype.arc3d.call(this,b);b.css({zIndex:b.zIndex});return b},b.VMLRenderer.prototype.arc3dPath=b.SVGRenderer.prototype.arc3dPath,t(x,"render",function(){this.sideFrame&&(this.sideFrame.css({zIndex:0}),
this.sideFrame.front.attr({fill:this.sideFrame.color}));this.bottomFrame&&(this.bottomFrame.css({zIndex:1}),this.bottomFrame.front.attr({fill:this.bottomFrame.color}));this.backFrame&&(this.backFrame.css({zIndex:0}),this.backFrame.front.attr({fill:this.backFrame.color}))}))})(A)});
