/*
 Highcharts JS v6.1.0-modified (2018-05-17)
 Highstock as a plugin for Highcharts

 (c) 2017 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(J){"object"===typeof module&&module.exports?module.exports=J:J(Highcharts)})(function(J){(function(a){var C=a.addEvent,v=a.Axis,G=a.Chart,A=a.css,D=a.defined,F=a.each,B=a.extend,w=a.noop,u=a.pick,r=a.timeUnits,x=a.wrap;x(a.Series.prototype,"init",function(g){var a;g.apply(this,Array.prototype.slice.call(arguments,1));(a=this.xAxis)&&a.options.ordinal&&C(this,"updatedData",function(){delete a.ordinalIndex})});x(v.prototype,"getTimeTicks",function(g,a,d,p,t,k,l,c){var b=0,f,q,m={},z,h,I,n=
[],y=-Number.MAX_VALUE,E=this.options.tickPixelInterval,K=this.chart.time;if(!this.options.ordinal&&!this.options.breaks||!k||3>k.length||void 0===d)return g.call(this,a,d,p,t);h=k.length;for(f=0;f<h;f++){I=f&&k[f-1]>p;k[f]<d&&(b=f);if(f===h-1||k[f+1]-k[f]>5*l||I){if(k[f]>y){for(q=g.call(this,a,k[b],k[f],t);q.length&&q[0]<=y;)q.shift();q.length&&(y=q[q.length-1]);n=n.concat(q)}b=f+1}if(I)break}g=q.info;if(c&&g.unitRange<=r.hour){f=n.length-1;for(b=1;b<f;b++)K.dateFormat("%d",n[b])!==K.dateFormat("%d",
n[b-1])&&(m[n[b]]="day",z=!0);z&&(m[n[0]]="day");g.higherRanks=m}n.info=g;if(c&&D(E)){c=K=n.length;f=[];var H;for(z=[];c--;)b=this.translate(n[c]),H&&(z[c]=H-b),f[c]=H=b;z.sort();z=z[Math.floor(z.length/2)];z<.6*E&&(z=null);c=n[K-1]>p?K-1:K;for(H=void 0;c--;)b=f[c],p=Math.abs(H-b),H&&p<.8*E&&(null===z||p<.8*z)?(m[n[c]]&&!m[n[c+1]]?(p=c+1,H=b):p=c,n.splice(p,1)):H=b}return n});B(v.prototype,{beforeSetTickPositions:function(){var a,e=[],d=!1,p,t=this.getExtremes(),k=t.min,l=t.max,c,b=this.isXAxis&&
!!this.options.breaks,t=this.options.ordinal,f=Number.MAX_VALUE,q=this.chart.options.chart.ignoreHiddenSeries;p="highcharts-navigator-xaxis"===this.options.className;!this.options.overscroll||this.max!==this.dataMax||this.chart.mouseIsDown&&!p||this.eventArgs&&(!this.eventArgs||"navigator"===this.eventArgs.trigger)||(this.max+=this.options.overscroll,!p&&D(this.userMin)&&(this.min+=this.options.overscroll));if(t||b){F(this.series,function(c,z){if(!(q&&!1===c.visible||!1===c.takeOrdinalPosition&&!b)&&
(e=e.concat(c.processedXData),a=e.length,e.sort(function(b,c){return b-c}),f=Math.min(f,u(c.closestPointRange,f)),a))for(z=a-1;z--;)e[z]===e[z+1]&&e.splice(z,1)});a=e.length;if(2<a){p=e[1]-e[0];for(c=a-1;c--&&!d;)e[c+1]-e[c]!==p&&(d=!0);!this.options.keepOrdinalPadding&&(e[0]-k>p||l-e[e.length-1]>p)&&(d=!0)}else this.options.overscroll&&(2===a?f=e[1]-e[0]:1===a?(f=this.options.overscroll,e=[e[0],e[0]+f]):f=this.overscrollPointsRange);d?(this.options.overscroll&&(this.overscrollPointsRange=f,e=e.concat(this.getOverscrollPositions())),
this.ordinalPositions=e,p=this.ordinal2lin(Math.max(k,e[0]),!0),c=Math.max(this.ordinal2lin(Math.min(l,e[e.length-1]),!0),1),this.ordinalSlope=l=(l-k)/(c-p),this.ordinalOffset=k-p*l):(this.overscrollPointsRange=u(this.closestPointRange,this.overscrollPointsRange),this.ordinalPositions=this.ordinalSlope=this.ordinalOffset=void 0)}this.isOrdinal=t&&d;this.groupIntervalFactor=null},val2lin:function(a,e){var d=this.ordinalPositions;if(d){var g=d.length,t,k;for(t=g;t--;)if(d[t]===a){k=t;break}for(t=g-
1;t--;)if(a>d[t]||0===t){a=(a-d[t])/(d[t+1]-d[t]);k=t+a;break}e=e?k:this.ordinalSlope*(k||0)+this.ordinalOffset}else e=a;return e},lin2val:function(a,e){var d=this.ordinalPositions;if(d){var g=this.ordinalSlope,t=this.ordinalOffset,k=d.length-1,l;if(e)0>a?a=d[0]:a>k?a=d[k]:(k=Math.floor(a),l=a-k);else for(;k--;)if(e=g*k+t,a>=e){g=g*(k+1)+t;l=(a-e)/(g-e);break}return void 0!==l&&void 0!==d[k]?d[k]+(l?l*(d[k+1]-d[k]):0):a}return a},getExtendedPositions:function(){var a=this,e=a.chart,d=a.series[0].currentDataGrouping,
p=a.ordinalIndex,t=d?d.count+d.unitName:"raw",k=a.options.overscroll,l=a.getExtremes(),c,b;p||(p=a.ordinalIndex={});p[t]||(c={series:[],chart:e,getExtremes:function(){return{min:l.dataMin,max:l.dataMax+k}},options:{ordinal:!0},val2lin:v.prototype.val2lin,ordinal2lin:v.prototype.ordinal2lin},F(a.series,function(f){b={xAxis:c,xData:f.xData.slice(),chart:e,destroyGroupedData:w};b.xData=b.xData.concat(a.getOverscrollPositions());b.options={dataGrouping:d?{enabled:!0,forced:!0,approximation:"open",units:[[d.unitName,
[d.count]]]}:{enabled:!1}};f.processData.apply(b);c.series.push(b)}),a.beforeSetTickPositions.apply(c),p[t]=c.ordinalPositions);return p[t]},getOverscrollPositions:function(){var g=this.options.overscroll,e=this.overscrollPointsRange,d=[],p=this.dataMax;if(a.defined(e))for(d.push(p);p<=this.dataMax+g;)p+=e,d.push(p);return d},getGroupIntervalFactor:function(a,e,d){var g;d=d.processedXData;var t=d.length,k=[];g=this.groupIntervalFactor;if(!g){for(g=0;g<t-1;g++)k[g]=d[g+1]-d[g];k.sort(function(a,c){return a-
c});k=k[Math.floor(t/2)];a=Math.max(a,d[0]);e=Math.min(e,d[t-1]);this.groupIntervalFactor=g=t*k/(e-a)}return g},postProcessTickInterval:function(a){var g=this.ordinalSlope;return g?this.options.breaks?this.closestPointRange||a:a/(g/this.closestPointRange):a}});v.prototype.ordinal2lin=v.prototype.val2lin;x(G.prototype,"pan",function(a,e){var d=this.xAxis[0],g=d.options.overscroll,t=e.chartX,k=!1;if(d.options.ordinal&&d.series.length){var l=this.mouseDownX,c=d.getExtremes(),b=c.dataMax,f=c.min,q=c.max,
m=this.hoverPoints,z=d.closestPointRange||d.overscrollPointsRange,l=(l-t)/(d.translationSlope*(d.ordinalSlope||z)),h={ordinalPositions:d.getExtendedPositions()},z=d.lin2val,I=d.val2lin,n;h.ordinalPositions?1<Math.abs(l)&&(m&&F(m,function(n){n.setState()}),0>l?(m=h,n=d.ordinalPositions?d:h):(m=d.ordinalPositions?d:h,n=h),h=n.ordinalPositions,b>h[h.length-1]&&h.push(b),this.fixedRange=q-f,l=d.toFixedRange(null,null,z.apply(m,[I.apply(m,[f,!0])+l,!0]),z.apply(n,[I.apply(n,[q,!0])+l,!0])),l.min>=Math.min(c.dataMin,
f)&&l.max<=Math.max(b,q)+g&&d.setExtremes(l.min,l.max,!0,!1,{trigger:"pan"}),this.mouseDownX=t,A(this.container,{cursor:"move"})):k=!0}else k=!0;k&&(g&&(d.max=d.dataMax+g),a.apply(this,Array.prototype.slice.call(arguments,1)))})})(J);(function(a){function C(){return Array.prototype.slice.call(arguments,1)}function v(a){a.apply(this);this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,A(this.pointArrayMap,["y"]))}var G=a.addEvent,A=a.pick,D=a.wrap,F=a.each,B=a.extend,w=a.isArray,u=a.fireEvent,
r=a.Axis,x=a.Series;B(r.prototype,{isInBreak:function(a,e){var d=a.repeat||Infinity,g=a.from,t=a.to-a.from;e=e>=g?(e-g)%d:d-(g-e)%d;return a.inclusive?e<=t:e<t&&0!==e},isInAnyBreak:function(a,e){var d=this.options.breaks,g=d&&d.length,t,k,l;if(g){for(;g--;)this.isInBreak(d[g],a)&&(t=!0,k||(k=A(d[g].showPoints,this.isXAxis?!1:!0)));l=t&&e?t&&!k:t}return l}});G(r,"afterSetTickPositions",function(){if(this.options.breaks){var a=this.tickPositions,e=this.tickPositions.info,d=[],p;for(p=0;p<a.length;p++)this.isInAnyBreak(a[p])||
d.push(a[p]);this.tickPositions=d;this.tickPositions.info=e}});G(r,"afterSetOptions",function(){this.options.breaks&&this.options.breaks.length&&(this.options.ordinal=!1)});G(r,"afterInit",function(){var a=this,e;e=this.options.breaks;a.isBroken=w(e)&&!!e.length;a.isBroken&&(a.val2lin=function(d){var e=d,g,k;for(k=0;k<a.breakArray.length;k++)if(g=a.breakArray[k],g.to<=d)e-=g.len;else if(g.from>=d)break;else if(a.isInBreak(g,d)){e-=d-g.from;break}return e},a.lin2val=function(d){var e,g;for(g=0;g<a.breakArray.length&&
!(e=a.breakArray[g],e.from>=d);g++)e.to<d?d+=e.len:a.isInBreak(e,d)&&(d+=e.len);return d},a.setExtremes=function(a,e,g,k,l){for(;this.isInAnyBreak(a);)a-=this.closestPointRange;for(;this.isInAnyBreak(e);)e-=this.closestPointRange;r.prototype.setExtremes.call(this,a,e,g,k,l)},a.setAxisTranslation=function(d){r.prototype.setAxisTranslation.call(this,d);d=a.options.breaks;var e=[],g=[],k=0,l,c,b=a.userMin||a.min,f=a.userMax||a.max,q=A(a.pointRangePadding,0),m,z;F(d,function(h){c=h.repeat||Infinity;a.isInBreak(h,
b)&&(b+=h.to%c-b%c);a.isInBreak(h,f)&&(f-=f%c-h.from%c)});F(d,function(a){m=a.from;for(c=a.repeat||Infinity;m-c>b;)m-=c;for(;m<b;)m+=c;for(z=m;z<f;z+=c)e.push({value:z,move:"in"}),e.push({value:z+(a.to-a.from),move:"out",size:a.breakSize})});e.sort(function(a,b){return a.value===b.value?("in"===a.move?0:1)-("in"===b.move?0:1):a.value-b.value});l=0;m=b;F(e,function(a){l+="in"===a.move?1:-1;1===l&&"in"===a.move&&(m=a.value);0===l&&(g.push({from:m,to:a.value,len:a.value-m-(a.size||0)}),k+=a.value-m-
(a.size||0))});a.breakArray=g;a.unitLength=f-b-k+q;u(a,"afterBreaks");a.options.staticScale?a.transA=a.options.staticScale:a.unitLength&&(a.transA*=(f-a.min+q)/a.unitLength);q&&(a.minPixelPadding=a.transA*a.minPointOffset);a.min=b;a.max=f})});D(x.prototype,"generatePoints",function(a){a.apply(this,C(arguments));var e=this.xAxis,d=this.yAxis,g=this.points,t,k=g.length,l=this.options.connectNulls,c;if(e&&d&&(e.options.breaks||d.options.breaks))for(;k--;)t=g[k],c=null===t.y&&!1===l,c||!e.isInAnyBreak(t.x,
!0)&&!d.isInAnyBreak(t.y,!0)||(g.splice(k,1),this.data[k]&&this.data[k].destroyElements())});a.Series.prototype.drawBreaks=function(a,e){var d=this,g=d.points,t,k,l,c;a&&F(e,function(b){t=a.breakArray||[];k=a.isXAxis?a.min:A(d.options.threshold,a.min);F(g,function(f){c=A(f["stack"+b.toUpperCase()],f[b]);F(t,function(b){l=!1;if(k<b.from&&c>b.to||k>b.from&&c<b.from)l="pointBreak";else if(k<b.from&&c>b.from&&c<b.to||k>b.from&&c>b.to&&c<b.from)l="pointInBreak";l&&u(a,l,{point:f,brk:b})})})})};a.Series.prototype.gappedPath=
function(){var g=this.currentDataGrouping,e=g&&g.totalRange,g=this.options.gapSize,d=this.points.slice(),p=d.length-1,t=this.yAxis;if(g&&0<p)for("value"!==this.options.gapUnit&&(g*=this.closestPointRange),e&&e>g&&(g=e);p--;)d[p+1].x-d[p].x>g&&(e=(d[p].x+d[p+1].x)/2,d.splice(p+1,0,{isNull:!0,x:e}),this.options.stacking&&(e=t.stacks[this.stackKey][e]=new a.StackItem(t,t.options.stackLabels,!1,e,this.stack),e.total=0));return this.getGraphPath(d)};D(a.seriesTypes.column.prototype,"drawPoints",v);D(a.Series.prototype,
"drawPoints",v)})(J);(function(a){var C=a.addEvent,v=a.arrayMax,G=a.arrayMin,A=a.Axis,D=a.defaultPlotOptions,F=a.defined,B=a.each,w=a.extend,u=a.format,r=a.isNumber,x=a.merge,g=a.pick,e=a.Point,d=a.Series,p=a.Tooltip,t=a.wrap,k=d.prototype,l=k.processData,c=k.generatePoints,b={approximation:"average",groupPixelWidth:2,dateTimeLabelFormats:{millisecond:["%A, %b %e, %H:%M:%S.%L","%A, %b %e, %H:%M:%S.%L","-%H:%M:%S.%L"],second:["%A, %b %e, %H:%M:%S","%A, %b %e, %H:%M:%S","-%H:%M:%S"],minute:["%A, %b %e, %H:%M",
"%A, %b %e, %H:%M","-%H:%M"],hour:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],day:["%A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],week:["Week from %A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],month:["%B %Y","%B","-%B %Y"],year:["%Y","%Y","-%Y"]}},f={line:{},spline:{},area:{},areaspline:{},column:{approximation:"sum",groupPixelWidth:10},arearange:{approximation:"range"},areasplinerange:{approximation:"range"},columnrange:{approximation:"range",groupPixelWidth:10},candlestick:{approximation:"ohlc",
groupPixelWidth:10},ohlc:{approximation:"ohlc",groupPixelWidth:5}},q=a.defaultDataGroupingUnits=[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1]],["week",[1]],["month",[1,3,6]],["year",null]],m=a.approximations={sum:function(a){var b=a.length,c;if(!b&&a.hasNulls)c=null;else if(b)for(c=0;b--;)c+=a[b];return c},average:function(a){var b=a.length;a=m.sum(a);r(a)&&b&&(a/=b);return a},averages:function(){var a=
[];B(arguments,function(b){a.push(m.average(b))});return void 0===a[0]?void 0:a},open:function(a){return a.length?a[0]:a.hasNulls?null:void 0},high:function(a){return a.length?v(a):a.hasNulls?null:void 0},low:function(a){return a.length?G(a):a.hasNulls?null:void 0},close:function(a){return a.length?a[a.length-1]:a.hasNulls?null:void 0},ohlc:function(a,b,c,n){a=m.open(a);b=m.high(b);c=m.low(c);n=m.close(n);if(r(a)||r(b)||r(c)||r(n))return[a,b,c,n]},range:function(a,b){a=m.low(a);b=m.high(b);if(r(a)||
r(b))return[a,b];if(null===a&&null===b)return null}};k.groupData=function(a,c,l,n){var y=this.data,E=this.options.data,h=[],H=[],q=[],z=a.length,d,e,I=!!c,g=[];n="function"===typeof n?n:m[n]||f[this.type]&&m[f[this.type].approximation]||m[b.approximation];var k=this.pointArrayMap,p=k&&k.length,t=0;e=0;var u,x;p?B(k,function(){g.push([])}):g.push([]);u=p||1;for(x=0;x<=z&&!(a[x]>=l[0]);x++);for(x;x<=z;x++){for(;void 0!==l[t+1]&&a[x]>=l[t+1]||x===z;){d=l[t];this.dataGroupInfo={start:e,length:g[0].length};
e=n.apply(this,g);void 0!==e&&(h.push(d),H.push(e),q.push(this.dataGroupInfo));e=x;for(d=0;d<u;d++)g[d].length=0,g[d].hasNulls=!1;t+=1;if(x===z)break}if(x===z)break;if(k){d=this.cropStart+x;var w=y&&y[d]||this.pointClass.prototype.applyOptions.apply({series:this},[E[d]]),D;for(d=0;d<p;d++)D=w[k[d]],r(D)?g[d].push(D):null===D&&(g[d].hasNulls=!0)}else d=I?c[x]:null,r(d)?g[0].push(d):null===d&&(g[0].hasNulls=!0)}return[h,H,q]};k.processData=function(){var a=this.chart,b=this.options.dataGrouping,c=!1!==
this.allowDG&&b&&g(b.enabled,a.options.isStock),n=this.visible||!a.options.chart.ignoreHiddenSeries,y,E=this.currentDataGrouping,f;this.forceCrop=c;this.groupPixelWidth=null;this.hasProcessed=!0;if(!1!==l.apply(this,arguments)&&c){this.destroyGroupedData();var H,d=b.groupAll?this.xData:this.processedXData,m=b.groupAll?this.yData:this.processedYData,e=a.plotSizeX,a=this.xAxis,p=a.options.ordinal,t=this.groupPixelWidth=a.getGroupPixelWidth&&a.getGroupPixelWidth();if(t){this.isDirty=y=!0;this.points=
null;c=a.getExtremes();f=c.min;c=c.max;p=p&&a.getGroupIntervalFactor(f,c,this)||1;t=t*(c-f)/e*p;e=a.getTimeTicks(a.normalizeTimeTickInterval(t,b.units||q),Math.min(f,d[0]),Math.max(c,d[d.length-1]),a.options.startOfWeek,d,this.closestPointRange);m=k.groupData.apply(this,[d,m,e,b.approximation]);d=m[0];p=m[1];if(b.smoothed&&d.length){H=d.length-1;for(d[H]=Math.min(d[H],c);H--&&0<H;)d[H]+=t/2;d[0]=Math.max(d[0],f)}f=e.info;this.closestPointRange=e.info.totalRange;this.groupMap=m[2];F(d[0])&&d[0]<a.dataMin&&
n&&(a.min<=a.dataMin&&(a.min=d[0]),a.dataMin=d[0]);b.groupAll&&(b=this.cropData(d,p,a.min,a.max,1),d=b.xData,p=b.yData);this.processedXData=d;this.processedYData=p}else this.groupMap=null;this.hasGroupedData=y;this.currentDataGrouping=f;this.preventGraphAnimation=(E&&E.totalRange)!==(f&&f.totalRange)}};k.destroyGroupedData=function(){var a=this.groupedData;B(a||[],function(b,c){b&&(a[c]=b.destroy?b.destroy():null)});this.groupedData=null};k.generatePoints=function(){c.apply(this);this.destroyGroupedData();
this.groupedData=this.hasGroupedData?this.points:null};C(e,"update",function(){if(this.dataGroup)return a.error(24),!1});t(p.prototype,"tooltipFooterHeaderFormatter",function(a,b,c){var n=this.chart.time,y=b.series,f=y.tooltipOptions,d=y.options.dataGrouping,l=f.xDateFormat,m,q=y.xAxis;return q&&"datetime"===q.options.type&&d&&r(b.key)?(a=y.currentDataGrouping,d=d.dateTimeLabelFormats,a?(q=d[a.unitName],1===a.count?l=q[0]:(l=q[1],m=q[2])):!l&&d&&(l=this.getXDateFormat(b,f,q)),l=n.dateFormat(l,b.key),
m&&(l+=n.dateFormat(m,b.key+a.totalRange-1)),u(f[(c?"footer":"header")+"Format"],{point:w(b.point,{key:l}),series:y},n)):a.call(this,b,c)});C(d,"destroy",k.destroyGroupedData);C(d,"afterSetOptions",function(a){a=a.options;var c=this.type,l=this.chart.options.plotOptions,n=D[c].dataGrouping,y=this.useCommonDataGrouping&&b;if(f[c]||y)n||(n=x(b,f[c])),a.dataGrouping=x(y,n,l.series&&l.series.dataGrouping,l[c].dataGrouping,this.userOptions.dataGrouping);this.chart.options.isStock&&(this.requireSorting=
!0)});C(A,"afterSetScale",function(){B(this.series,function(a){a.hasProcessed=!1})});A.prototype.getGroupPixelWidth=function(){var a=this.series,b=a.length,c,n=0,y=!1,f;for(c=b;c--;)(f=a[c].options.dataGrouping)&&(n=Math.max(n,f.groupPixelWidth));for(c=b;c--;)(f=a[c].options.dataGrouping)&&a[c].hasProcessed&&(b=(a[c].processedXData||a[c].data).length,a[c].groupPixelWidth||b>this.chart.plotSizeX/n||b&&f.forced)&&(y=!0);return y?n:0};A.prototype.setDataGrouping=function(a,b){var c;b=g(b,!0);a||(a={forced:!1,
units:null});if(this instanceof A)for(c=this.series.length;c--;)this.series[c].update({dataGrouping:a},!1);else B(this.chart.options.series,function(b){b.dataGrouping=a},!1);this.ordinalSlope=null;b&&this.chart.redraw()}})(J);(function(a){var C=a.each,v=a.Point,G=a.seriesType,A=a.seriesTypes;G("ohlc","column",{lineWidth:1,tooltip:{pointFormat:'\x3cspan class\x3d"highcharts-color-{point.colorIndex}"\x3e\u25cf\x3c/span\x3e \x3cb\x3e {series.name}\x3c/b\x3e\x3cbr/\x3eOpen: {point.open}\x3cbr/\x3eHigh: {point.high}\x3cbr/\x3eLow: {point.low}\x3cbr/\x3eClose: {point.close}\x3cbr/\x3e'},
threshold:null,stickyTracking:!0},{directTouch:!1,pointArrayMap:["open","high","low","close"],toYData:function(a){return[a.open,a.high,a.low,a.close]},pointValKey:"close",translate:function(){var a=this,v=a.yAxis,B=!!a.modifyValue,w=["plotOpen","plotHigh","plotLow","plotClose","yBottom"];A.column.prototype.translate.apply(a);C(a.points,function(u){C([u.open,u.high,u.low,u.close,u.low],function(r,x){null!==r&&(B&&(r=a.modifyValue(r)),u[w[x]]=v.toPixels(r,!0))});u.tooltipPos[1]=u.plotHigh+v.pos-a.chart.plotTop})},
drawPoints:function(){var a=this,v=a.chart;C(a.points,function(B){var w,u,r,x,g=B.graphic,e,d=!g;void 0!==B.plotY&&(g||(B.graphic=g=v.renderer.path().add(a.group)),u=g.strokeWidth()%2/2,e=Math.round(B.plotX)-u,r=Math.round(B.shapeArgs.width/2),x=["M",e,Math.round(B.yBottom),"L",e,Math.round(B.plotHigh)],null!==B.open&&(w=Math.round(B.plotOpen)+u,x.push("M",e,w,"L",e-r,w)),null!==B.close&&(w=Math.round(B.plotClose)+u,x.push("M",e,w,"L",e+r,w)),g[d?"attr":"animate"]({d:x}).addClass(B.getClassName(),
!0))})},animate:null},{getClassName:function(){return v.prototype.getClassName.call(this)+(this.open<this.close?" highcharts-point-up":" highcharts-point-down")}})})(J);(function(a){var C=a.defaultPlotOptions,v=a.each,G=a.merge;a=a.seriesType;a("candlestick","ohlc",G(C.column,{states:{hover:{lineWidth:2}},tooltip:C.ohlc.tooltip,threshold:null,stickyTracking:!0}),{drawPoints:function(){var a=this,D=a.chart;v(a.points,function(v){var B=v.graphic,w,u,r,x,g,e,d,p=!B;void 0!==v.plotY&&(B||(v.graphic=B=
D.renderer.path().add(a.group)),g=B.strokeWidth()%2/2,e=Math.round(v.plotX)-g,w=v.plotOpen,u=v.plotClose,r=Math.min(w,u),w=Math.max(w,u),d=Math.round(v.shapeArgs.width/2),u=Math.round(r)!==Math.round(v.plotHigh),x=w!==v.yBottom,r=Math.round(r)+g,w=Math.round(w)+g,g=[],g.push("M",e-d,w,"L",e-d,r,"L",e+d,r,"L",e+d,w,"Z","M",e,r,"L",e,u?Math.round(v.plotHigh):r,"M",e,w,"L",e,x?Math.round(v.yBottom):w),B[p?"attr":"animate"]({d:g}).addClass(v.getClassName(),!0))})}})})(J);var V=function(a){var C=a.each,
v=a.defined,G=a.seriesTypes,A=a.stableSort;return{getPlotBox:function(){return a.Series.prototype.getPlotBox.call(this.options.onSeries&&this.chart.get(this.options.onSeries)||this)},translate:function(){G.column.prototype.translate.apply(this);var a=this.options,F=this.chart,B=this.points,w=B.length-1,u,r,x=a.onSeries,x=x&&F.get(x),a=a.onKey||"y",g=x&&x.options.step,e=x&&x.points,d=e&&e.length,p=F.inverted,t=this.xAxis,k=this.yAxis,l=0,c,b,f,q;if(x&&x.visible&&d)for(l=(x.pointXOffset||0)+(x.barW||
0)/2,u=x.currentDataGrouping,b=e[d-1].x+(u?u.totalRange:0),A(B,function(a,b){return a.x-b.x}),a="plot"+a[0].toUpperCase()+a.substr(1);d--&&B[w]&&!(c=e[d],u=B[w],u.y=c.y,c.x<=u.x&&void 0!==c[a]&&(u.x<=b&&(u.plotY=c[a],c.x<u.x&&!g&&(f=e[d+1])&&void 0!==f[a]&&(q=(u.x-c.x)/(f.x-c.x),u.plotY+=q*(f[a]-c[a]),u.y+=q*(f.y-c.y))),w--,d++,0>w)););C(B,function(a,b){var c;a.plotX+=l;if(void 0===a.plotY||p)0<=a.plotX&&a.plotX<=t.len?p?(a.plotY=t.translate(a.x,0,1,0,1),a.plotX=v(a.y)?k.translate(a.y,0,0,0,1):0):
a.plotY=F.chartHeight-t.bottom-(t.opposite?t.height:0)+t.offset-k.top:a.shapeArgs={};(r=B[b-1])&&r.plotX===a.plotX&&(void 0===r.stackIndex&&(r.stackIndex=0),c=r.stackIndex+1);a.stackIndex=c});this.onSeries=x}}}(J);(function(a,C){function v(a){w[a+"pin"]=function(r,x,g,e,d){var p=d&&d.anchorX;d=d&&d.anchorY;"circle"===a&&e>g&&(r-=Math.round((e-g)/2),g=e);r=w[a](r,x,g,e);p&&d&&(r.push("M","circle"===a?r[1]-r[4]:r[1]+r[4]/2,x>d?x:x+e,"L",p,d),r=r.concat(w.circle(p-1,d-1,2,2)));return r}}var G=a.addEvent,
A=a.each,D=a.noop,F=a.seriesType,B=a.TrackerMixin,w=a.SVGRenderer.prototype.symbols;F("flags","column",{pointRange:0,allowOverlapX:!1,shape:"flag",stackDistance:12,textAlign:"center",tooltip:{pointFormat:"{point.text}\x3cbr/\x3e"},threshold:null,y:-30},{sorted:!1,noSharedTooltip:!0,allowDG:!1,takeOrdinalPosition:!1,trackerGroups:["markerGroup"],forceCrop:!0,init:a.Series.prototype.init,translate:C.translate,getPlotBox:C.getPlotBox,drawPoints:function(){var u=this.points,r=this.chart,x=r.renderer,
g,e,d=r.inverted,p=this.options,t=p.y,k,l,c,b,f,q,m=this.yAxis,z={},h=[];for(l=u.length;l--;)c=u[l],q=(d?c.plotY:c.plotX)>this.xAxis.len,g=c.plotX,b=c.stackIndex,k=c.options.shape||p.shape,e=c.plotY,void 0!==e&&(e=c.plotY+t-(void 0!==b&&b*p.stackDistance)),c.anchorX=b?void 0:c.plotX,f=b?void 0:c.plotY,b=c.graphic,void 0!==e&&0<=g&&!q?(b||(b=c.graphic=x.label("",null,null,k,null,null,p.useHTML).attr({align:"flag"===k?"left":"center",width:p.width,height:p.height,"text-align":p.textAlign}).addClass("highcharts-point").add(this.markerGroup),
c.graphic.div&&(c.graphic.div.point=c),b.isNew=!0),0<g&&(g-=b.strokeWidth()%2),k={y:e,anchorY:f},p.allowOverlapX&&(k.x=g,k.anchorX=c.anchorX),b.attr({text:c.options.title||p.title||"A"})[b.isNew?"attr":"animate"](k),p.allowOverlapX||(z[c.plotX]?z[c.plotX].size=Math.max(z[c.plotX].size,b.width):z[c.plotX]={align:0,size:b.width,target:g,anchorX:g}),c.tooltipPos=[g,e+m.pos-r.plotTop]):b&&(c.graphic=b.destroy());p.allowOverlapX||(a.objectEach(z,function(a){a.plotX=a.anchorX;h.push(a)}),a.distribute(h,
d?m.len:this.xAxis.len,100),A(u,function(a){var b=a.graphic&&z[a.plotX];b&&(a.graphic[a.graphic.isNew?"attr":"animate"]({x:b.pos,anchorX:a.anchorX}),a.graphic.isNew=!1)}));p.useHTML&&a.wrap(this.markerGroup,"on",function(b){return a.SVGElement.prototype.on.apply(b.apply(this,[].slice.call(arguments,1)),[].slice.call(arguments,1))})},drawTracker:function(){var a=this.points;B.drawTrackerPoint.apply(this);A(a,function(r){var x=r.graphic;x&&G(x.element,"mouseover",function(){0<r.stackIndex&&!r.raised&&
(r._y=x.y,x.attr({y:r._y-8}),r.raised=!0);A(a,function(a){a!==r&&a.raised&&a.graphic&&(a.graphic.attr({y:a._y}),a.raised=!1)})})})},animate:D,buildKDTree:D,setClip:D,invertGroups:D});w.flag=function(a,r,x,g,e){var d=e&&e.anchorX||a;e=e&&e.anchorY||r;return w.circle(d-1,e-1,2,2).concat(["M",d,e,"L",a,r+g,a,r,a+x,r,a+x,r+g,a,r+g,"Z"])};v("circle");v("square")})(J,V);(function(a){function C(a,c,b){this.init(a,c,b)}var v=a.addEvent,G=a.Axis,A=a.correctFloat,D=a.defaultOptions,F=a.defined,B=a.destroyObjectProperties,
w=a.each,u=a.fireEvent,r=a.hasTouch,x=a.isTouchDevice,g=a.merge,e=a.pick,d=a.removeEvent,p=a.wrap,t,k={height:x?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:a.svg&&!x,margin:10,minWidth:6,step:.2,zIndex:3};D.scrollbar=g(!0,k,D.scrollbar);a.swapXY=t=function(a,c){var b=a.length,f;if(c)for(c=0;c<b;c+=3)f=a[c+1],a[c+1]=a[c+2],a[c+2]=f;return a};C.prototype={init:function(a,c,b){this.scrollbarButtons=[];this.renderer=a;this.userOptions=c;this.options=g(k,c);this.chart=b;this.size=e(this.options.size,
this.options.height);c.enabled&&(this.render(),this.initEvents(),this.addEvents())},render:function(){var a=this.renderer,c=this.options,b=this.size,f;this.group=f=a.g("scrollbar").attr({zIndex:c.zIndex,translateY:-99999}).add();this.track=a.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:c.trackBorderRadius||0,height:b,width:b}).add(f);this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=a.g().add(f);this.scrollbar=a.rect().addClass("highcharts-scrollbar-thumb").attr({height:b,
width:b,r:c.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=a.path(t(["M",-3,b/4,"L",-3,2*b/3,"M",0,b/4,"L",0,2*b/3,"M",3,b/4,"L",3,2*b/3],c.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)},position:function(a,c,b,f){var d=this.options.vertical,l=0,e=
this.rendered?"animate":"attr";this.x=a;this.y=c+this.trackBorderWidth;this.width=b;this.xOffset=this.height=f;this.yOffset=l;d?(this.width=this.yOffset=b=l=this.size,this.xOffset=c=0,this.barWidth=f-2*b,this.x=a+=this.options.margin):(this.height=this.xOffset=f=c=this.size,this.barWidth=b-2*f,this.y+=this.options.margin);this.group[e]({translateX:a,translateY:this.y});this.track[e]({width:b,height:f});this.scrollbarButtons[1][e]({translateX:d?0:b-c,translateY:d?f-l:0})},drawScrollbarButton:function(a){var c=
this.renderer,b=this.scrollbarButtons,f=this.options,d=this.size,l;l=c.g().add(this.group);b.push(l);l=c.rect().addClass("highcharts-scrollbar-button").add(l);l.attr(l.crisp({x:-.5,y:-.5,width:d+1,height:d+1,r:f.buttonBorderRadius},l.strokeWidth()));c.path(t(["M",d/2+(a?-1:1),d/2-3,"L",d/2+(a?-1:1),d/2+3,"L",d/2+(a?2:-2),d/2],f.vertical)).addClass("highcharts-scrollbar-arrow").add(b[a])},setRange:function(a,c){var b=this.options,f=b.vertical,d=b.minWidth,l=this.barWidth,e,h,g=this.rendered&&!this.hasDragged?
"animate":"attr";F(l)&&(a=Math.max(a,0),e=Math.ceil(l*a),this.calculatedWidth=h=A(l*Math.min(c,1)-e),h<d&&(e=(l-d+h)*a,h=d),d=Math.floor(e+this.xOffset+this.yOffset),l=h/2-.5,this.from=a,this.to=c,f?(this.scrollbarGroup[g]({translateY:d}),this.scrollbar[g]({height:h}),this.scrollbarRifles[g]({translateY:l}),this.scrollbarTop=d,this.scrollbarLeft=0):(this.scrollbarGroup[g]({translateX:d}),this.scrollbar[g]({width:h}),this.scrollbarRifles[g]({translateX:l}),this.scrollbarLeft=d,this.scrollbarTop=0),
12>=h?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0),!1===b.showFull&&(0>=a&&1<=c?this.group.hide():this.group.show()),this.rendered=!0)},initEvents:function(){var a=this;a.mouseMoveHandler=function(c){var b=a.chart.pointer.normalize(c),d=a.options.vertical?"chartY":"chartX",e=a.initPositions;!a.grabbedCenter||c.touches&&0===c.touches[0][d]||(b=a.cursorToScrollbarPosition(b)[d],d=a[d],d=b-d,a.hasDragged=!0,a.updatePosition(e[0]+d,e[1]+d),a.hasDragged&&u(a,"changed",{from:a.from,to:a.to,
trigger:"scrollbar",DOMType:c.type,DOMEvent:c}))};a.mouseUpHandler=function(c){a.hasDragged&&u(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMType:c.type,DOMEvent:c});a.grabbedCenter=a.hasDragged=a.chartX=a.chartY=null};a.mouseDownHandler=function(c){c=a.chart.pointer.normalize(c);c=a.cursorToScrollbarPosition(c);a.chartX=c.chartX;a.chartY=c.chartY;a.initPositions=[a.from,a.to];a.grabbedCenter=!0};a.buttonToMinClick=function(c){var b=A(a.to-a.from)*a.options.step;a.updatePosition(A(a.from-
b),A(a.to-b));u(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:c})};a.buttonToMaxClick=function(c){var b=(a.to-a.from)*a.options.step;a.updatePosition(a.from+b,a.to+b);u(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:c})};a.trackClick=function(c){var b=a.chart.pointer.normalize(c),d=a.to-a.from,e=a.y+a.scrollbarTop,m=a.x+a.scrollbarLeft;a.options.vertical&&b.chartY>e||!a.options.vertical&&b.chartX>m?a.updatePosition(a.from+d,a.to+d):a.updatePosition(a.from-d,a.to-d);
u(a,"changed",{from:a.from,to:a.to,trigger:"scrollbar",DOMEvent:c})}},cursorToScrollbarPosition:function(a){var c=this.options,c=c.minWidth>this.calculatedWidth?c.minWidth:0;return{chartX:(a.chartX-this.x-this.xOffset)/(this.barWidth-c),chartY:(a.chartY-this.y-this.yOffset)/(this.barWidth-c)}},updatePosition:function(a,c){1<c&&(a=A(1-A(c-a)),c=1);0>a&&(c=A(c-a),a=0);this.from=a;this.to=c},update:function(a){this.destroy();this.init(this.chart.renderer,g(!0,this.options,a),this.chart)},addEvents:function(){var a=
this.options.inverted?[1,0]:[0,1],c=this.scrollbarButtons,b=this.scrollbarGroup.element,d=this.mouseDownHandler,e=this.mouseMoveHandler,m=this.mouseUpHandler,a=[[c[a[0]].element,"click",this.buttonToMinClick],[c[a[1]].element,"click",this.buttonToMaxClick],[this.track.element,"click",this.trackClick],[b,"mousedown",d],[b.ownerDocument,"mousemove",e],[b.ownerDocument,"mouseup",m]];r&&a.push([b,"touchstart",d],[b.ownerDocument,"touchmove",e],[b.ownerDocument,"touchend",m]);w(a,function(a){v.apply(null,
a)});this._events=a},removeEvents:function(){w(this._events,function(a){d.apply(null,a)});this._events.length=0},destroy:function(){var a=this.chart.scroller;this.removeEvents();w(["track","scrollbarRifles","scrollbar","scrollbarGroup","group"],function(a){this[a]&&this[a].destroy&&(this[a]=this[a].destroy())},this);a&&this===a.scrollbar&&(a.scrollbar=null,B(a.scrollbarButtons))}};p(G.prototype,"init",function(a){var c=this;a.apply(c,Array.prototype.slice.call(arguments,1));c.options.scrollbar&&c.options.scrollbar.enabled&&
(c.options.scrollbar.vertical=!c.horiz,c.options.startOnTick=c.options.endOnTick=!1,c.scrollbar=new C(c.chart.renderer,c.options.scrollbar,c.chart),v(c.scrollbar,"changed",function(a){var b=Math.min(e(c.options.min,c.min),c.min,c.dataMin),d=Math.max(e(c.options.max,c.max),c.max,c.dataMax)-b,m;c.horiz&&!c.reversed||!c.horiz&&c.reversed?(m=b+d*this.to,b+=d*this.from):(m=b+d*(1-this.from),b+=d*(1-this.to));c.setExtremes(b,m,!0,!1,a)}))});p(G.prototype,"render",function(a){var c=Math.min(e(this.options.min,
this.min),this.min,e(this.dataMin,this.min)),b=Math.max(e(this.options.max,this.max),this.max,e(this.dataMax,this.max)),d=this.scrollbar,q=this.titleOffset||0;a.apply(this,Array.prototype.slice.call(arguments,1));if(d){this.horiz?(d.position(this.left,this.top+this.height+2+this.chart.scrollbarsOffsets[1]+(this.opposite?0:q+this.axisTitleMargin+this.offset),this.width,this.height),q=1):(d.position(this.left+this.width+2+this.chart.scrollbarsOffsets[0]+(this.opposite?q+this.axisTitleMargin+this.offset:
0),this.top,this.width,this.height),q=0);if(!this.opposite&&!this.horiz||this.opposite&&this.horiz)this.chart.scrollbarsOffsets[q]+=this.scrollbar.size+this.scrollbar.options.margin;isNaN(c)||isNaN(b)||!F(this.min)||!F(this.max)?d.setRange(0,0):(q=(this.min-c)/(b-c),c=(this.max-c)/(b-c),this.horiz&&!this.reversed||!this.horiz&&this.reversed?d.setRange(q,c):d.setRange(1-c,1-q))}});p(G.prototype,"getOffset",function(a){var c=this.horiz?2:1,b=this.scrollbar;a.apply(this,Array.prototype.slice.call(arguments,
1));b&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[c]+=b.size+b.options.margin)});p(G.prototype,"destroy",function(a){this.scrollbar&&(this.scrollbar=this.scrollbar.destroy());a.apply(this,Array.prototype.slice.call(arguments,1))});a.Scrollbar=C})(J);(function(a){function C(a){this.init(a)}var v=a.addEvent,G=a.Axis,A=a.Chart,D=a.defaultOptions,F=a.defined,B=a.destroyObjectProperties,w=a.each,u=a.erase,r=a.error,x=a.extend,g=a.grep,e=a.hasTouch,d=a.isArray,p=a.isNumber,t=a.isObject,k=
a.isTouchDevice,l=a.merge,c=a.pick,b=a.removeEvent,f=a.Scrollbar,q=a.Series,m=a.seriesTypes,z=a.wrap,h=[].concat(a.defaultDataGroupingUnits),I=function(a){var b=g(arguments,p);if(b.length)return Math[a].apply(0,b)};h[4]=["day",[1,2,3,4]];h[5]=["week",[1,2,3]];x(D,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0},series:{type:void 0===m.areaspline?"line":"areaspline",compare:null,dataGrouping:{approximation:"average",
enabled:!0,groupPixelWidth:2,smoothed:!0,units:h},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},pointRange:0,threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",tickLength:0,tickPixelInterval:200,labels:{align:"left",x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},
tickLength:0,tickWidth:0}}});a.Renderer.prototype.symbols["navigator-handle"]=function(a,b,c,d,f){a=f.width/2;b=Math.round(a/3)+.5;f=f.height;return["M",-a-1,.5,"L",a,.5,"L",a,f+.5,"L",-a-1,f+.5,"L",-a-1,.5,"M",-b,4,"L",-b,f-3,"M",b-1,4,"L",b-1,f-3]};C.prototype={drawHandle:function(a,b,c,d){var n=this.navigatorOptions.handles.height;this.handles[b][d](c?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+parseInt(a,10)+.5-n)}:{translateX:Math.round(this.left+parseInt(a,
10)),translateY:Math.round(this.top+this.height/2-n/2-1)})},drawOutline:function(a,b,c,d){var n=this.navigatorOptions.maskInside,y=this.outline.strokeWidth(),f=y/2,y=y%2/2,E=this.outlineHeight,e=this.scrollbarHeight,q=this.size,m=this.left-e,h=this.top;c?(m-=f,c=h+b+y,b=h+a+y,a=["M",m+E,h-e-y,"L",m+E,c,"L",m,c,"L",m,b,"L",m+E,b,"L",m+E,h+q+e].concat(n?["M",m+E,c-f,"L",m+E,b+f]:[])):(a+=m+e-y,b+=m+e-y,h+=f,a=["M",m,h,"L",a,h,"L",a,h+E,"L",b,h+E,"L",b,h,"L",m+q+2*e,h].concat(n?["M",a-f,h,"L",b+f,h]:
[]));this.outline[d]({d:a})},drawMasks:function(a,b,c,d){var n=this.left,y=this.top,f=this.height,E,e,m,q;c?(m=[n,n,n],q=[y,y+a,y+b],e=[f,f,f],E=[a,b-a,this.size-b]):(m=[n,n+a,n+b],q=[y,y,y],e=[a,b-a,this.size-b],E=[f,f,f]);w(this.shades,function(a,b){a[d]({x:m[b],y:q[b],width:e[b],height:E[b]})})},renderElements:function(){var a=this,b=a.navigatorOptions,c=b.maskInside,d=a.chart,f=d.renderer,e;a.navigatorGroup=e=f.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();w([!c,c,!c],function(b,n){a.shades[n]=
f.rect().addClass("highcharts-navigator-mask"+(1===n?"-inside":"-outside")).add(e)});a.outline=f.path().addClass("highcharts-navigator-outline").add(e);b.handles.enabled&&w([0,1],function(n){b.handles.inverted=d.inverted;a.handles[n]=f.symbol(b.handles.symbols[n],-b.handles.width/2-1,0,b.handles.width,b.handles.height,b.handles);a.handles[n].attr({zIndex:7-n}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][n]).add(e)})},update:function(a){w(this.series||[],function(a){a.baseSeries&&
delete a.baseSeries.navigatorSeries});this.destroy();l(!0,this.chart.options.navigator,this.options,a);this.init(this.chart)},render:function(b,d,f,e){var n=this.chart,y,E,m=this.scrollbarHeight,q,h=this.xAxis;y=h.fake?n.xAxis[0]:h;var g=this.navigatorEnabled,K,k=this.rendered;E=n.inverted;var z,I=n.xAxis[0].minRange,l=n.xAxis[0].options.maxRange;if(!this.hasDragged||F(f)){if(!p(b)||!p(d))if(k)f=0,e=c(h.width,y.width);else return;this.left=c(h.left,n.plotLeft+m+(E?n.plotWidth:0));this.size=K=q=c(h.len,
(E?n.plotHeight:n.plotWidth)-2*m);n=E?m:q+2*m;f=c(f,h.toPixels(b,!0));e=c(e,h.toPixels(d,!0));p(f)&&Infinity!==Math.abs(f)||(f=0,e=n);b=h.toValue(f,!0);d=h.toValue(e,!0);z=Math.abs(a.correctFloat(d-b));z<I?this.grabbedLeft?f=h.toPixels(d-I,!0):this.grabbedRight&&(e=h.toPixels(b+I,!0)):F(l)&&z>l&&(this.grabbedLeft?f=h.toPixels(d-l,!0):this.grabbedRight&&(e=h.toPixels(b+l,!0)));this.zoomedMax=Math.min(Math.max(f,e,0),K);this.zoomedMin=Math.min(Math.max(this.fixedWidth?this.zoomedMax-this.fixedWidth:
Math.min(f,e),0),K);this.range=this.zoomedMax-this.zoomedMin;K=Math.round(this.zoomedMax);f=Math.round(this.zoomedMin);g&&(this.navigatorGroup.attr({visibility:"visible"}),k=k&&!this.hasDragged?"animate":"attr",this.drawMasks(f,K,E,k),this.drawOutline(f,K,E,k),this.navigatorOptions.handles.enabled&&(this.drawHandle(f,0,E,k),this.drawHandle(K,1,E,k)));this.scrollbar&&(E?(E=this.top-m,y=this.left-m+(g||!y.opposite?0:(y.titleOffset||0)+y.axisTitleMargin),m=q+2*m):(E=this.top+(g?this.height:-m),y=this.left-
m),this.scrollbar.position(y,E,n,m),this.scrollbar.setRange(this.zoomedMin/q,this.zoomedMax/q));this.rendered=!0}},addMouseEvents:function(){var a=this,b=a.chart,c=b.container,d=[],f,m;a.mouseMoveHandler=f=function(b){a.onMouseMove(b)};a.mouseUpHandler=m=function(b){a.onMouseUp(b)};d=a.getPartsEvents("mousedown");d.push(v(c,"mousemove",f),v(c.ownerDocument,"mouseup",m));e&&(d.push(v(c,"touchmove",f),v(c.ownerDocument,"touchend",m)),d.concat(a.getPartsEvents("touchstart")));a.eventsToUnbind=d;a.series&&
a.series[0]&&d.push(v(a.series[0].xAxis,"foundExtremes",function(){b.navigator.modifyNavigatorAxisExtremes()}))},getPartsEvents:function(a){var b=this,n=[];w(["shades","handles"],function(c){w(b[c],function(d,f){n.push(v(d.element,a,function(a){b[c+"Mousedown"](a,f)}))})});return n},shadesMousedown:function(a,b){a=this.chart.pointer.normalize(a);var c=this.chart,d=this.xAxis,n=this.zoomedMin,f=this.left,e=this.size,y=this.range,m=a.chartX,h,q;c.inverted&&(m=a.chartY,f=this.top);1===b?(this.grabbedCenter=
m,this.fixedWidth=y,this.dragOffset=m-n):(a=m-f-y/2,0===b?a=Math.max(0,a):2===b&&a+y>=e&&(a=e-y,d.reversed?(a-=y,q=this.getUnionExtremes().dataMin):h=this.getUnionExtremes().dataMax),a!==n&&(this.fixedWidth=y,b=d.toFixedRange(a,a+y,q,h),F(b.min)&&c.xAxis[0].setExtremes(Math.min(b.min,b.max),Math.max(b.min,b.max),!0,null,{trigger:"navigator"})))},handlesMousedown:function(a,b){this.chart.pointer.normalize(a);a=this.chart;var c=a.xAxis[0],d=a.inverted&&!c.reversed||!a.inverted&&c.reversed;0===b?(this.grabbedLeft=
!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=d?c.min:c.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=d?c.max:c.min);a.fixedRange=null},onMouseMove:function(a){var b=this,c=b.chart,d=b.left,n=b.navigatorSize,f=b.range,e=b.dragOffset,m=c.inverted;a.touches&&0===a.touches[0].pageX||(a=c.pointer.normalize(a),c=a.chartX,m&&(d=b.top,c=a.chartY),b.grabbedLeft?(b.hasDragged=!0,b.render(0,0,c-d,b.otherHandlePos)):b.grabbedRight?(b.hasDragged=!0,b.render(0,0,b.otherHandlePos,
c-d)):b.grabbedCenter&&(b.hasDragged=!0,c<e?c=e:c>n+e-f&&(c=n+e-f),b.render(0,0,c-e,c-e+f)),b.hasDragged&&b.scrollbar&&b.scrollbar.options.liveRedraw&&(a.DOMType=a.type,setTimeout(function(){b.onMouseUp(a)},0)))},onMouseUp:function(a){var b=this.chart,c=this.xAxis,d=c&&c.reversed,n=this.scrollbar,f,e,m=a.DOMEvent||a;(!this.hasDragged||n&&n.hasDragged)&&"scrollbar"!==a.trigger||(n=this.getUnionExtremes(),this.zoomedMin===this.otherHandlePos?f=this.fixedExtreme:this.zoomedMax===this.otherHandlePos&&
(e=this.fixedExtreme),this.zoomedMax===this.size&&(e=d?n.dataMin:n.dataMax),0===this.zoomedMin&&(f=d?n.dataMax:n.dataMin),c=c.toFixedRange(this.zoomedMin,this.zoomedMax,f,e),F(c.min)&&b.xAxis[0].setExtremes(Math.min(c.min,c.max),Math.max(c.min,c.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:m}));"mousemove"!==a.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=
null)},removeEvents:function(){this.eventsToUnbind&&(w(this.eventsToUnbind,function(a){a()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()},removeBaseSeriesEvents:function(){var a=this.baseSeries||[];this.navigatorEnabled&&a[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&w(a,function(a){b(a,"updatedData",this.updatedDataHandler)},this),a[0].xAxis&&b(a[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))},init:function(a){var b=a.options,d=b.navigator,n=d.enabled,e=b.scrollbar,m=
e.enabled,b=n?d.height:0,h=m?e.height:0;this.handles=[];this.shades=[];this.chart=a;this.setBaseSeries();this.height=b;this.scrollbarHeight=h;this.scrollbarEnabled=m;this.navigatorEnabled=n;this.navigatorOptions=d;this.scrollbarOptions=e;this.outlineHeight=b+h;this.opposite=c(d.opposite,!n&&a.inverted);var q=this,e=q.baseSeries,m=a.xAxis.length,g=a.yAxis.length,k=e&&e[0]&&e[0].xAxis||a.xAxis[0]||{options:{}};a.extraMargin={type:q.opposite?"plotTop":"marginBottom",value:(n||!a.inverted?q.outlineHeight:
0)+d.margin};a.inverted&&(a.extraMargin.type=q.opposite?"marginRight":"plotLeft");a.isDirtyBox=!0;q.navigatorEnabled?(q.xAxis=new G(a,l({breaks:k.options.breaks,ordinal:k.options.ordinal},d.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:m,offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},a.inverted?{offsets:[h,0,-h,0],width:b}:{offsets:[0,-h,0,h],height:b})),q.yAxis=new G(a,l(d.yAxis,{id:"navigator-y-axis",alignTicks:!1,
offset:0,index:g,zoomEnabled:!1},a.inverted?{width:b}:{height:b})),e||d.series.data?q.updateNavigatorSeries(!1):0===a.series.length&&(q.unbindRedraw=v(a,"beforeRedraw",function(){0<a.series.length&&!q.series&&(q.setBaseSeries(),q.unbindRedraw())})),q.renderElements(),q.addMouseEvents()):q.xAxis={translate:function(b,c){var d=a.xAxis[0],f=d.getExtremes(),n=d.len-2*h,e=I("min",d.options.min,f.dataMin),d=I("max",d.options.max,f.dataMax)-e;return c?b*d/n+e:n*(b-e)/d},toPixels:function(a){return this.translate(a)},
toValue:function(a){return this.translate(a,!0)},toFixedRange:G.prototype.toFixedRange,fake:!0};a.options.scrollbar.enabled&&(a.scrollbar=q.scrollbar=new f(a.renderer,l(a.options.scrollbar,{margin:q.navigatorEnabled?0:10,vertical:a.inverted}),a),v(q.scrollbar,"changed",function(b){var c=q.size,d=c*this.to,c=c*this.from;q.hasDragged=q.scrollbar.hasDragged;q.render(0,0,c,d);(a.options.scrollbar.liveRedraw||"mousemove"!==b.DOMType&&"touchmove"!==b.DOMType)&&setTimeout(function(){q.onMouseUp(b)})}));
q.addBaseSeriesEvents();q.addChartEvents()},getUnionExtremes:function(a){var b=this.chart.xAxis[0],d=this.xAxis,f=d.options,n=b.options,e;a&&null===b.dataMin||(e={dataMin:c(f&&f.min,I("min",n.min,b.dataMin,d.dataMin,d.min)),dataMax:c(f&&f.max,I("max",n.max,b.dataMax,d.dataMax,d.max))});return e},setBaseSeries:function(a,b){var c=this.chart,d=this.baseSeries=[];a=a||c.options&&c.options.navigator.baseSeries||0;w(c.series||[],function(b,c){b.options.isInternal||!b.options.showInNavigator&&(c!==a&&b.options.id!==
a||!1===b.options.showInNavigator)||d.push(b)});this.xAxis&&!this.xAxis.fake&&this.updateNavigatorSeries(!0,b)},updateNavigatorSeries:function(c,f){var e=this,n=e.chart,m=e.baseSeries,q,h,y=e.navigatorOptions.series,g,k={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:!1,isInternal:!0,visible:!0},z=e.series=a.grep(e.series||[],function(c){var d=c.baseSeries;return 0>a.inArray(d,m)?(d&&(b(d,"updatedData",
e.updatedDataHandler),delete d.navigatorSeries),c.destroy(),!1):!0});m&&m.length&&w(m,function(a){var b=a.navigatorSeries,c=x({color:a.color},d(y)?D.navigator.series:y);b&&!1===e.navigatorOptions.adaptToUpdatedData||(k.name="Navigator "+m.length,q=a.options||{},g=q.navigatorOptions||{},h=l(q,k,c,g),c=g.data||c.data,e.hasNavigatorData=e.hasNavigatorData||!!c,h.data=c||q.data&&q.data.slice(0),b&&b.options?b.update(h,f):(a.navigatorSeries=n.initSeries(h),a.navigatorSeries.baseSeries=a,z.push(a.navigatorSeries)))});
if(y.data&&(!m||!m.length)||d(y))e.hasNavigatorData=!1,y=a.splat(y),w(y,function(a,b){k.name="Navigator "+(z.length+1);h=l(D.navigator.series,{color:n.series[b]&&!n.series[b].options.isInternal&&n.series[b].color||n.options.colors[b]||n.options.colors[0]},k,a);h.data=a.data;h.data&&(e.hasNavigatorData=!0,z.push(n.initSeries(h)))});c&&this.addBaseSeriesEvents()},addBaseSeriesEvents:function(){var a=this,b=a.baseSeries||[];b[0]&&b[0].xAxis&&v(b[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);
w(b,function(b){v(b,"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,!1)});v(b,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&b.xAxis&&v(b,"updatedData",this.updatedDataHandler);v(b,"remove",function(){this.navigatorSeries&&(u(a.series,this.navigatorSeries),F(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)},modifyNavigatorAxisExtremes:function(){var a=
this.xAxis,b;a.getExtremes&&(!(b=this.getUnionExtremes(!0))||b.dataMin===a.min&&b.dataMax===a.max||(a.min=b.dataMin,a.max=b.dataMax))},modifyBaseAxisExtremes:function(){var a=this.chart.navigator,b=this.getExtremes(),d=b.dataMin,f=b.dataMax,b=b.max-b.min,e=a.stickToMin,m=a.stickToMax,q=c(this.options.overscroll,0),h,g,k=a.series&&a.series[0],z=!!this.setExtremes;this.eventArgs&&"rangeSelectorButton"===this.eventArgs.trigger||(e&&(g=d,h=g+b),m&&(h=f+q,e||(g=Math.max(h-b,k&&k.xData?k.xData[0]:-Number.MAX_VALUE))),
z&&(e||m)&&p(g)&&(this.min=this.userMin=g,this.max=this.userMax=h));a.stickToMin=a.stickToMax=null},updatedDataHandler:function(){var a=this.chart.navigator,b=this.navigatorSeries;a.stickToMax=a.xAxis.reversed?0===Math.round(a.zoomedMin):Math.round(a.zoomedMax)>=Math.round(a.size);a.stickToMin=p(this.xAxis.min)&&this.xAxis.min<=this.xData[0]&&(!this.chart.fixedRange||!a.stickToMax);b&&!a.hasNavigatorData&&(b.options.pointStart=this.xData[0],b.setData(this.options.data,!1,null,!1))},addChartEvents:function(){v(this.chart,
"redraw",function(){var a=this.navigator,b=a&&(a.baseSeries&&a.baseSeries[0]&&a.baseSeries[0].xAxis||a.scrollbar&&this.xAxis[0]);b&&a.render(b.min,b.max)})},destroy:function(){this.removeEvents();this.xAxis&&(u(this.chart.xAxis,this.xAxis),u(this.chart.axes,this.xAxis));this.yAxis&&(u(this.chart.yAxis,this.yAxis),u(this.chart.axes,this.yAxis));w(this.series||[],function(a){a.destroy&&a.destroy()});w("series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" "),
function(a){this[a]&&this[a].destroy&&this[a].destroy();this[a]=null},this);w([this.handles],function(a){B(a)},this)}};a.Navigator=C;z(G.prototype,"zoom",function(a,b,c){var d=this.chart,f=d.options,e=f.chart.zoomType,m=f.chart.pinchType,n=f.navigator,f=f.rangeSelector,q;this.isXAxis&&(n&&n.enabled||f&&f.enabled)&&(!k&&"x"===e||k&&"x"===m?d.resetZoomButton="blocked":"y"===e?q=!1:(!k&&"xy"===e||k&&"xy"===m)&&this.options.range&&(d=this.previousZoom,F(b)?this.previousZoom=[this.min,this.max]:d&&(b=
d[0],c=d[1],delete this.previousZoom)));return void 0!==q?q:a.call(this,b,c)});v(A,"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=this.navigator=new C(this)});v(A,"afterSetChartSize",function(){var a=this.legend,b=this.navigator,d,f,e,m;b&&(f=a&&a.options,e=b.xAxis,m=b.yAxis,d=b.scrollbarHeight,this.inverted?(b.left=b.opposite?this.chartWidth-d-b.height:this.spacing[3]+d,b.top=this.plotTop+d):(b.left=this.plotLeft+d,b.top=b.navigatorOptions.top||
this.chartHeight-b.height-d-this.spacing[2]-(this.rangeSelector&&this.extraBottomMargin?this.rangeSelector.getHeight():0)-(f&&"bottom"===f.verticalAlign&&f.enabled&&!f.floating?a.legendHeight+c(f.margin,10):0)),e&&m&&(this.inverted?e.options.left=m.options.left=b.left:e.options.top=m.options.top=b.top,e.setAxisSize(),m.setAxisSize()))});z(q.prototype,"addPoint",function(a,b,c,d,f){var e=this.options.turboThreshold;e&&this.xData.length>e&&t(b,!0)&&this.chart.navigator&&r(20,!0);a.call(this,b,c,d,f)});
v(A,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,!1)});v(q,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)});A.prototype.callbacks.push(function(a){var b=a.navigator;b&&a.xAxis[0]&&(a=a.xAxis[0].getExtremes(),b.render(a.min,a.max))})})(J);(function(a){function C(a){this.init(a)}var v=a.addEvent,G=a.Axis,A=a.Chart,D=a.css,F=a.createElement,B=a.defaultOptions,w=a.defined,u=a.destroyObjectProperties,
r=a.discardElement,x=a.each,g=a.extend,e=a.fireEvent,d=a.isNumber,p=a.merge,t=a.pick,k=a.pInt,l=a.splat,c=a.wrap;g(B,{rangeSelector:{verticalAlign:"top",buttonTheme:{"stroke-width":0,width:28,height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0}}});B.lang=p(B.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});C.prototype={clickButton:function(a,c){var b=this,f=b.chart,e=b.buttonOptions[a],
h=f.xAxis[0],g=f.scroller&&f.scroller.getUnionExtremes()||h||{},n=g.dataMin,k=g.dataMax,p,r=h&&Math.round(Math.min(h.max,t(k,h.max))),H=e.type,u,g=e._range,w,B,A,C=e.dataGrouping;if(null!==n&&null!==k){f.fixedRange=g;C&&(this.forcedDataGrouping=!0,G.prototype.setDataGrouping.call(h||{chart:this.chart},C,!1));if("month"===H||"year"===H)h?(H={range:e,max:r,chart:f,dataMin:n,dataMax:k},p=h.minFromRange.call(H),d(H.newMax)&&(r=H.newMax)):g=e;else if(g)p=Math.max(r-g,n),r=Math.min(p+g,k);else if("ytd"===
H)if(h)void 0===k&&(n=Number.MAX_VALUE,k=Number.MIN_VALUE,x(f.series,function(a){a=a.xData;n=Math.min(a[0],n);k=Math.max(a[a.length-1],k)}),c=!1),r=b.getYTDExtremes(k,n,f.time.useUTC),p=w=r.min,r=r.max;else{v(f,"beforeRender",function(){b.clickButton(a)});return}else"all"===H&&h&&(p=n,r=k);p+=e._offsetMin;r+=e._offsetMax;b.setSelected(a);h?h.setExtremes(p,r,t(c,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:e}):(u=l(f.options.xAxis)[0],A=u.range,u.range=g,B=u.min,u.min=w,v(f,"load",function(){u.range=
A;u.min=B}))}},setSelected:function(a){this.selected=this.options.selected=a},defaultButtons:[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},{type:"all",text:"All"}],init:function(a){var b=this,c=a.options.rangeSelector,d=c.buttons||[].concat(b.defaultButtons),g=c.selected,h=function(){var a=b.minInput,c=b.maxInput;a&&a.blur&&e(a,"blur");c&&c.blur&&e(c,"blur")};b.chart=a;b.options=c;b.buttons=
[];a.extraTopMargin=c.height;b.buttonOptions=d;this.unMouseDown=v(a.container,"mousedown",h);this.unResize=v(a,"resize",h);x(d,b.computeButtonRange);void 0!==g&&d[g]&&this.clickButton(g,!1);v(a,"load",function(){a.xAxis&&a.xAxis[0]&&v(a.xAxis[0],"setExtremes",function(c){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==c.trigger&&"updatedData"!==c.trigger&&b.forcedDataGrouping&&this.setDataGrouping(!1,!1)})})},updateButtonStates:function(){var a=this.chart,c=a.xAxis[0],e=Math.round(c.max-
c.min),m=!c.hasVisibleSeries,g=a.scroller&&a.scroller.getUnionExtremes()||c,h=g.dataMin,k=g.dataMax,a=this.getYTDExtremes(k,h,a.time.useUTC),n=a.min,p=a.max,l=this.selected,t=d(l),r=this.options.allButtonsEnabled,v=this.buttons;x(this.buttonOptions,function(a,b){var d=a._range,f=a.type,q=a.count||1,g=v[b],y=0;a=a._offsetMax-a._offsetMin;b=b===l;var z=d>k-h,E=d<c.minRange,I=!1,H=!1,d=d===e;("month"===f||"year"===f)&&e+36E5>=864E5*{month:28,year:365}[f]*q-a&&e-36E5<=864E5*{month:31,year:366}[f]*q+a?
d=!0:"ytd"===f?(d=p-n+a===e,I=!b):"all"===f&&(d=c.max-c.min>=k-h,H=!b&&t&&d);f=!r&&(z||E||H||m);q=b&&d||d&&!t&&!I;f?y=3:q&&(t=!0,y=2);g.state!==y&&g.setState(y)})},computeButtonRange:function(a){var b=a.type,c=a.count||1,d={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(d[b])a._range=d[b]*c;else if("month"===b||"year"===b)a._range=864E5*{month:30,year:365}[b]*c;a._offsetMin=t(a.offsetMin,0);a._offsetMax=t(a.offsetMax,0);a._range+=a._offsetMax-a._offsetMin},setInputValue:function(a,
c){var b=this.chart.options.rangeSelector,d=this.chart.time,e=this[a+"Input"];w(c)&&(e.previousValue=e.HCTime,e.HCTime=c);e.value=d.dateFormat(b.inputEditDateFormat||"%Y-%m-%d",e.HCTime);this[a+"DateBox"].attr({text:d.dateFormat(b.inputDateFormat||"%b %e, %Y",e.HCTime)})},showInput:function(a){var b=this.inputGroup,c=this[a+"DateBox"];D(this[a+"Input"],{left:b.translateX+c.x+"px",top:b.translateY+"px",width:c.width-2+"px",height:c.height-2+"px",border:"2px solid silver"})},hideInput:function(a){D(this[a+
"Input"],{border:0,width:"1px",height:"1px"});this.setInputValue(a)},drawInput:function(a){function b(){var a=l.value,b=(h.inputDateParser||Date.parse)(a),f=e.xAxis[0],m=e.scroller&&e.scroller.xAxis?e.scroller.xAxis:f,q=m.dataMin,m=m.dataMax;b!==l.previousValue&&(l.previousValue=b,d(b)||(b=a.split("-"),b=Date.UTC(k(b[0]),k(b[1])-1,k(b[2]))),d(b)&&(e.time.useUTC||(b+=6E4*(new Date).getTimezoneOffset()),n?b>c.maxInput.HCTime?b=void 0:b<q&&(b=q):b<c.minInput.HCTime?b=void 0:b>m&&(b=m),void 0!==b&&f.setExtremes(n?
b:f.min,n?f.max:b,void 0,void 0,{trigger:"rangeSelectorInput"})))}var c=this,e=c.chart,g=e.renderer,h=e.options.rangeSelector,p=c.div,n="min"===a,l,t,r=this.inputGroup;this[a+"Label"]=t=g.label(B.lang[n?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(r);r.offset+=t.width+5;this[a+"DateBox"]=g=g.label("",r.offset).addClass("highcharts-range-input").attr({padding:2,width:h.inputBoxWidth||90,height:h.inputBoxHeight||17,stroke:h.inputBoxBorderColor||
"#cccccc","stroke-width":1,"text-align":"center"}).on("click",function(){c.showInput(a);c[a+"Input"].focus()}).add(r);r.offset+=g.width+(n?10:0);this[a+"Input"]=l=F("input",{name:a,className:"highcharts-range-selector",type:"text"},{top:e.plotTop+"px"},p);l.onfocus=function(){c.showInput(a)};l.onblur=function(){c.hideInput(a)};l.onchange=b;l.onkeypress=function(a){13===a.keyCode&&b()}},getPosition:function(){var a=this.chart,c=a.options.rangeSelector,a="top"===c.verticalAlign?a.plotTop-a.axisOffset[0]:
0;return{buttonTop:a+c.buttonPosition.y,inputTop:a+c.inputPosition.y-10}},getYTDExtremes:function(a,c,d){var b=this.chart.time,e=new b.Date(a),f=b.get("FullYear",e);d=d?b.Date.UTC(f,0,1):+new b.Date(f,0,1);c=Math.max(c||0,d);e=e.getTime();return{max:Math.min(a||e,e),min:c}},render:function(a,c){var b=this,d=b.chart,e=d.renderer,f=d.container,g=d.options,n=g.exporting&&!1!==g.exporting.enabled&&g.navigation&&g.navigation.buttonOptions,k=B.lang,l=b.div,p=g.rangeSelector,g=p.floating,r=b.buttons,l=b.inputGroup,
v=p.buttonTheme,u=p.buttonPosition,w=p.inputPosition,A=p.inputEnabled,C=v&&v.states,D=d.plotLeft,G,L=b.buttonGroup,J;J=b.rendered;var P=b.options.verticalAlign,R=d.legend,S=R&&R.options,T=u.y,Q=w.y,U=J||!1,O=0,M=0,N;if(!1!==p.enabled){J||(b.group=J=e.g("range-selector-group").attr({zIndex:7}).add(),b.buttonGroup=L=e.g("range-selector-buttons").add(J),b.zoomText=e.text(k.rangeSelectorZoom,t(D+u.x,D),15).css(p.labelStyle).add(L),G=t(D+u.x,D)+b.zoomText.getBBox().width+5,x(b.buttonOptions,function(a,
c){r[c]=e.button(a.text,G,0,function(){var d=a.events&&a.events.click,e;d&&(e=d.call(a));!1!==e&&b.clickButton(c);b.isActive=!0},v,C&&C.hover,C&&C.select,C&&C.disabled).attr({"text-align":"center"}).add(L);G+=r[c].width+t(p.buttonSpacing,5)}),!1!==A&&(b.div=l=F("div",null,{position:"relative",height:0,zIndex:1}),f.parentNode.insertBefore(l,f),b.inputGroup=l=e.g("input-group").add(J),l.offset=0,b.drawInput("min"),b.drawInput("max")));D=d.plotLeft-d.spacing[3];b.updateButtonStates();n&&this.titleCollision(d)&&
"top"===P&&"right"===u.align&&u.y+L.getBBox().height-12<(n.y||0)+n.height&&(O=-40);"left"===u.align?N=u.x-d.spacing[3]:"right"===u.align&&(N=u.x+O-d.spacing[1]);L.align({y:u.y,width:L.getBBox().width,align:u.align,x:N},!0,d.spacingBox);b.group.placed=U;b.buttonGroup.placed=U;!1!==A&&(O=n&&this.titleCollision(d)&&"top"===P&&"right"===w.align&&w.y-l.getBBox().height-12<(n.y||0)+n.height+d.spacing[0]?-40:0,"left"===w.align?N=D:"right"===w.align&&(N=-Math.max(d.axisOffset[1],-O)),l.align({y:w.y,width:l.getBBox().width,
align:w.align,x:w.x+N-2},!0,d.spacingBox),f=l.alignAttr.translateX+l.alignOptions.x-O+l.getBBox().x+2,n=l.alignOptions.width,k=L.alignAttr.translateX+L.getBBox().x,N=L.getBBox().width+20,(w.align===u.align||k+N>f&&f+n>k&&T<Q+l.getBBox().height)&&l.attr({translateX:l.alignAttr.translateX+(d.axisOffset[1]>=-O?0:-O),translateY:l.alignAttr.translateY+L.getBBox().height+10}),b.setInputValue("min",a),b.setInputValue("max",c),b.inputGroup.placed=U);b.group.align({verticalAlign:P},!0,d.spacingBox);a=b.group.getBBox().height+
20;c=b.group.alignAttr.translateY;"bottom"===P&&(R=S&&"bottom"===S.verticalAlign&&S.enabled&&!S.floating?R.legendHeight+t(S.margin,10):0,a=a+R-20,M=c-a-(g?0:p.y)-10);if("top"===P)g&&(M=0),d.titleOffset&&(M=d.titleOffset+d.options.title.margin),M+=d.margin[0]-d.spacing[0]||0;else if("middle"===P)if(Q===T)M=0>Q?c+void 0:c;else if(Q||T)M=0>Q||0>T?M-Math.min(Q,T):c-a+NaN;b.group.translate(p.x,p.y+Math.floor(M));!1!==A&&(b.minInput.style.marginTop=b.group.translateY+"px",b.maxInput.style.marginTop=b.group.translateY+
"px");b.rendered=!0}},getHeight:function(){var a=this.options,c=this.group,d=a.y,e=a.buttonPosition.y,a=a.inputPosition.y,c=c?c.getBBox(!0).height+13+d:0,d=Math.min(a,e);if(0>a&&0>e||0<a&&0<e)c+=Math.abs(d);return c},titleCollision:function(a){return!(a.options.title.text||a.options.subtitle.text)},update:function(a){var b=this.chart;p(!0,b.options.rangeSelector,a);this.destroy();this.init(b);b.rangeSelector.render()},destroy:function(){var b=this,c=b.minInput,d=b.maxInput;b.unMouseDown();b.unResize();
u(b.buttons);c&&(c.onfocus=c.onblur=c.onchange=null);d&&(d.onfocus=d.onblur=d.onchange=null);a.objectEach(b,function(a,c){a&&"chart"!==c&&(a.destroy?a.destroy():a.nodeType&&r(this[c]));a!==C.prototype[c]&&(b[c]=null)},this)}};G.prototype.toFixedRange=function(a,c,e,g){var b=this.chart&&this.chart.fixedRange;a=t(e,this.translate(a,!0,!this.horiz));c=t(g,this.translate(c,!0,!this.horiz));e=b&&(c-a)/b;.7<e&&1.3>e&&(g?a=c-b:c=a+b);d(a)&&d(c)||(a=c=void 0);return{min:a,max:c}};G.prototype.minFromRange=
function(){var a=this.range,c={month:"Month",year:"FullYear"}[a.type],e,g=this.max,k,h,l=function(a,b){var d=new Date(a),e=d["get"+c]();d["set"+c](e+b);e===d["get"+c]()&&d.setDate(0);return d.getTime()-a};d(a)?(e=g-a,h=a):(e=g+l(g,-a.count),this.chart&&(this.chart.fixedRange=g-e));k=t(this.dataMin,Number.MIN_VALUE);d(e)||(e=k);e<=k&&(e=k,void 0===h&&(h=l(e,a.count)),this.newMax=Math.min(e+h,this.dataMax));d(g)||(e=void 0);return e};v(A,"afterGetContainer",function(){this.options.rangeSelector.enabled&&
(this.rangeSelector=new C(this))});c(A.prototype,"render",function(a,c,d){var b=this.axes,e=this.rangeSelector;e&&(x(b,function(a){a.updateNames();a.setScale()}),this.getAxisMargins(),e.render(),b=e.options.verticalAlign,e.options.floating||("bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=!0)));a.call(this,c,d)});v(A,"update",function(a){var b=a.options;a=this.rangeSelector;this.extraTopMargin=this.extraBottomMargin=!1;this.isDirtyBox=!0;a&&(a.render(),b=b.rangeSelector&&
b.rangeSelector.verticalAlign||a.options&&a.options.verticalAlign,a.options.floating||("bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=!0)))});c(A.prototype,"redraw",function(a,c,d){var b=this.rangeSelector;b&&!b.options.floating&&(b.render(),b=b.options.verticalAlign,"bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=!0));a.call(this,c,d)});A.prototype.adjustPlotArea=function(){var a=this.rangeSelector;this.rangeSelector&&(a=a.getHeight(),this.extraTopMargin&&
(this.plotTop+=a),this.extraBottomMargin&&(this.marginBottom+=a))};A.prototype.callbacks.push(function(a){function b(){c=a.xAxis[0].getExtremes();d(c.min)&&e.render(c.min,c.max)}var c,e=a.rangeSelector,g,h;e&&(h=v(a.xAxis[0],"afterSetExtremes",function(a){e.render(a.min,a.max)}),g=v(a,"redraw",b),b());v(a,"destroy",function(){e&&(g(),h())})});a.RangeSelector=C})(J);(function(a){var C=a.addEvent,v=a.arrayMax,G=a.arrayMin,A=a.Axis,D=a.Chart,F=a.defined,B=a.each,w=a.format,u=a.grep,r=a.inArray,x=a.isNumber,
g=a.isString,e=a.map,d=a.merge,p=a.pick,t=a.Point,k=a.Series,l=a.splat,c=a.SVGRenderer,b=a.wrap,f=k.prototype,q=f.init,m=f.processData,z=t.prototype.tooltipFormatter;a.StockChart=a.stockChart=function(b,c,f){var n=g(b)||b.nodeName,h=arguments[n?1:0],k=h.series,m=a.getOptions(),q,r=p(h.navigator&&h.navigator.enabled,m.navigator.enabled,!0),t=r?{startOnTick:!1,endOnTick:!1}:null,u={marker:{enabled:!1,radius:2}},v={shadow:!1,borderWidth:0};h.xAxis=e(l(h.xAxis||{}),function(a,b){return d({minPadding:0,
maxPadding:0,overscroll:0,ordinal:!0,title:{text:null},labels:{overflow:"justify"},showLastLabel:!0},m.xAxis,m.xAxis&&m.xAxis[b],a,{type:"datetime",categories:null},t)});h.yAxis=e(l(h.yAxis||{}),function(a,b){q=p(a.opposite,!0);return d({labels:{y:-2},opposite:q,showLastLabel:!(!a.categories&&"category"!==a.type),title:{text:null}},m.yAxis,m.yAxis&&m.yAxis[b],a)});h.series=null;h=d({chart:{panning:!0,pinchType:"x"},navigator:{enabled:r},scrollbar:{enabled:p(m.scrollbar.enabled,!0)},rangeSelector:{enabled:p(m.rangeSelector.enabled,
!0)},title:{text:null},tooltip:{split:p(m.tooltip.split,!0),crosshairs:!0},legend:{enabled:!1},plotOptions:{line:u,spline:u,area:u,areaspline:u,arearange:u,areasplinerange:u,column:v,columnrange:v,candlestick:v,ohlc:v}},h,{isStock:!0});h.series=k;return n?new D(b,h,f):new D(h,c)};b(A.prototype,"autoLabelAlign",function(a){var b=this.chart,c=this.options,b=b._labelPanes=b._labelPanes||{},d=this.options.labels;return this.chart.options.isStock&&"yAxis"===this.coll&&(c=c.top+","+c.height,!b[c]&&d.enabled)?
(15===d.x&&(d.x=0),void 0===d.align&&(d.align="right"),b[c]=this,"right"):a.apply(this,[].slice.call(arguments,1))});C(A,"destroy",function(){var a=this.chart,b=this.options&&this.options.top+","+this.options.height;b&&a._labelPanes&&a._labelPanes[b]===this&&delete a._labelPanes[b]});b(A.prototype,"getPlotLinePath",function(b,c,d,f,k,m){var h=this,n=this.isLinked&&!this.series?this.linkedParent.series:this.series,l=h.chart,q=l.renderer,t=h.left,u=h.top,v,y,w,I,z=[],E=[],A,C;if("xAxis"!==h.coll&&"yAxis"!==
h.coll)return b.apply(this,[].slice.call(arguments,1));E=function(a){var b="xAxis"===a?"yAxis":"xAxis";a=h.options[b];return x(a)?[l[b][a]]:g(a)?[l.get(a)]:e(n,function(a){return a[b]})}(h.coll);B(h.isXAxis?l.yAxis:l.xAxis,function(a){if(F(a.options.id)?-1===a.options.id.indexOf("navigator"):1){var b=a.isXAxis?"yAxis":"xAxis",b=F(a.options[b])?l[b][a.options[b]]:l[b][0];h===b&&E.push(a)}});A=E.length?[]:[h.isXAxis?l.yAxis[0]:l.xAxis[0]];B(E,function(b){-1!==r(b,A)||a.find(A,function(a){return a.pos===
b.pos&&a.len&&b.len})||A.push(b)});C=p(m,h.translate(c,null,null,f));x(C)&&(h.horiz?B(A,function(a){var b;y=a.pos;I=y+a.len;v=w=Math.round(C+h.transB);if(v<t||v>t+h.width)k?v=w=Math.min(Math.max(t,v),t+h.width):b=!0;b||z.push("M",v,y,"L",w,I)}):B(A,function(a){var b;v=a.pos;w=v+a.len;y=I=Math.round(u+h.height-C);if(y<u||y>u+h.height)k?y=I=Math.min(Math.max(u,y),h.top+h.height):b=!0;b||z.push("M",v,y,"L",w,I)}));return 0<z.length?q.crispPolyLine(z,d||1):null});c.prototype.crispPolyLine=function(a,
b){var c;for(c=0;c<a.length;c+=6)a[c+1]===a[c+4]&&(a[c+1]=a[c+4]=Math.round(a[c+1])-b%2/2),a[c+2]===a[c+5]&&(a[c+2]=a[c+5]=Math.round(a[c+2])+b%2/2);return a};b(A.prototype,"hideCrosshair",function(a,b){a.call(this,b);this.crossLabel&&(this.crossLabel=this.crossLabel.hide())});C(A,"afterDrawCrosshair",function(a){var b,c;if(F(this.crosshair.label)&&this.crosshair.label.enabled&&this.cross){var d=this.chart,e=this.options.crosshair.label,f=this.horiz;b=this.opposite;c=this.left;var g=this.top,h=this.crossLabel,
k=e.format,l="",m="inside"===this.options.tickPosition,q=!1!==this.crosshair.snap,t=0,r=a.e||this.cross&&this.cross.e,u=a.point;a=f?"center":b?"right"===this.labelAlign?"right":"left":"left"===this.labelAlign?"left":"center";h||(h=this.crossLabel=d.renderer.label(null,null,null,e.shape||"callout").addClass("highcharts-crosshair-label"+(this.series[0]&&" highcharts-color-"+this.series[0].colorIndex)).attr({align:e.align||a,padding:p(e.padding,8),r:p(e.borderRadius,3),zIndex:2}).add(this.labelGroup));
f?(a=q?u.plotX+c:r.chartX,g+=b?0:this.height):(a=b?this.width+c:0,g=q?u.plotY+g:r.chartY);k||e.formatter||(this.isDatetimeAxis&&(l="%b %d, %Y"),k="{value"+(l?":"+l:"")+"}");l=q?u[this.isXAxis?"x":"y"]:this.toValue(f?r.chartX:r.chartY);h.attr({text:k?w(k,{value:l},d.time):e.formatter.call(this,l),x:a,y:g,visibility:l<this.min||l>this.max?"hidden":"visible"});e=h.getBBox();if(f){if(m&&!b||!m&&b)g=h.y-e.height}else g=h.y-e.height/2;f?(b=c-e.x,c=c+this.width-e.x):(b="left"===this.labelAlign?c:0,c="right"===
this.labelAlign?c+this.width:d.chartWidth);h.translateX<b&&(t=b-h.translateX);h.translateX+e.width>=c&&(t=-(h.translateX+e.width-c));h.attr({x:a+t,y:g,anchorX:f?a:this.opposite?0:d.chartWidth,anchorY:f?this.opposite?d.chartHeight:0:g+e.height/2})}});f.init=function(){q.apply(this,arguments);this.setCompare(this.options.compare)};f.setCompare=function(a){this.modifyValue="value"===a||"percent"===a?function(b,c){var d=this.compareValue;if(void 0!==b&&void 0!==d)return b="value"===a?b-d:b/d*100-(100===
this.options.compareBase?0:100),c&&(c.change=b),b}:null;this.userOptions.compare=a;this.chart.hasRendered&&(this.isDirty=!0)};f.processData=function(){var a,b=-1,c,d,e=!0===this.options.compareStart?0:1,f,g;m.apply(this,arguments);if(this.xAxis&&this.processedYData)for(c=this.processedXData,d=this.processedYData,f=d.length,this.pointArrayMap&&(b=r("close",this.pointArrayMap),-1===b&&(b=r(this.pointValKey||"y",this.pointArrayMap))),a=0;a<f-e;a++)if(g=d[a]&&-1<b?d[a][b]:d[a],x(g)&&c[a+e]>=this.xAxis.min&&
0!==g){this.compareValue=g;break}};b(f,"getExtremes",function(a){var b;a.apply(this,[].slice.call(arguments,1));this.modifyValue&&(b=[this.modifyValue(this.dataMin),this.modifyValue(this.dataMax)],this.dataMin=G(b),this.dataMax=v(b))});A.prototype.setCompare=function(a,b){this.isXAxis||(B(this.series,function(b){b.setCompare(a)}),p(b,!0)&&this.chart.redraw())};t.prototype.tooltipFormatter=function(b){b=b.replace("{point.change}",(0<this.change?"+":"")+a.numberFormat(this.change,p(this.series.tooltipOptions.changeDecimals,
2)));return z.apply(this,[b])};b(k.prototype,"render",function(a){var b;this.chart.is3d&&this.chart.is3d()||this.chart.polar||!this.xAxis||this.xAxis.isRadial||(b=this.yAxis.len-(this.xAxis.axisLine?Math.floor(this.xAxis.axisLine.strokeWidth()/2):0),!this.clipBox&&this.animate?(this.clipBox=d(this.chart.clipBox),this.clipBox.width=this.xAxis.len,this.clipBox.height=b):this.chart[this.sharedClipKey]?this.chart[this.sharedClipKey].attr({width:this.xAxis.len,height:b}):this.clipBox&&(this.clipBox.width=
this.xAxis.len,this.clipBox.height=b));a.call(this)});b(D.prototype,"getSelectedPoints",function(a){var b=a.call(this);B(this.series,function(a){a.hasGroupedData&&(b=b.concat(u(a.points||[],function(a){return a.selected})))});return b});C(D,"update",function(a){a=a.options;"scrollbar"in a&&this.navigator&&(d(!0,this.options.scrollbar,a.scrollbar),this.navigator.update({},!1),delete a.scrollbar)})})(J)});
